### ISSUE TITLE
Default logger is not shared in cross-module of an application

### ISSUE THREAD

**Issue by haquocviet** [gabime/spdlog#1095]
Hello,

First, thank you author for the good library.

I have some issues in using the spdlog 1.3.1 with MSVC 2019.

I have a dll, names "gen_logger.dll", having a function:
```

EXPORT_API std::shared_ptr<spdlog::async_logger> 
make_logger(std::string_view& logName, std::shared_ptr <spdlog::details::thread_pool> tp) 
{
	std::vector<spdlog::sink_ptr> sinks;
	sinks.reserve(5);
	
	auto fileLog = std::make_shared<spdlog::sinks::rotating_file_sink_mt>(fileName.data(), fileSize, maxNumFiles);
	fileLog->set_level(spdlog::level::info);
	sinks.push_back(fileLog);
	
	// if I uncomment two lines below, there will be 16 bytes leaked after the application exits.
	//spdlog::init_thread_pool(1000, 1); <- this causes memleak
	//tp = spdlog::thread_pool();
	
	auto myLogger = std::make_shared <spdlog::async_logger>(logName.data(), sinks.begin(), sinks.end()
			, tp, spdlog::async_overflow_policy::overrun_oldest);
	spdlog::set_default_logger(myLogger);
	
	spdlog::info("inside the dll"); // <-- this is ok. myLogger is invoked correctly.
	
	return myLogger;
}
```

In an application A

```
#ifdef _DEBUG
#define _CRTDBG_MAP_ALLOC
#include <stdlib.h>
#include <crtdbg.h>

#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#define new new(_NORMAL_BLOCK, THIS_FILE, __LINE__)

int main(...)
{
	_CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);

	//	assume gen_logger.dll has been loaded.
	
	spdlog::init_thread_pool(1000, 1);
	auto tp = spdlog::thread_pool();
	auto logger = make_logger("mylogger", tp);
	
	logger->info("outside the dll"); // it's ok.	
	spdlog::info("outside the dll"); // <-- this is not ok. myLogger is not invoked.
		
	spdlog::shutdown();
	
	return 0;
}
```

My questions are:

1) Is the default logger shared in all modules of a program? If so, how can I make a default logger shared in entire of an application?

2) I am quite confused with the leak. Is my usage of the thread_pool correct? 
Please check if the leak exists actually.

Thanks.

**Comment by tt4g** [comment]
It is described in the wiki: https://github.com/gabime/spdlog/wiki/How-to-use-spdlog-in-DLLs

The `registry` object that manages the state of spdlog is not shared between DLLs, so global loggers and thread pool are also not shared.

> 1. Is the default logger shared in all modules of a program? If so, how can I make a default logger shared in entire of an application?

As mentioned above, global logger are not shared, so register the DLL generated logger with the global logger also in application A.

> 2. am quite confused with the leak. Is my usage of the thread_pool correct?
Please check if the leak exists actually.

`spdlog::shutdown()` releases the thread pool. Since the thread pool is initialized in the DLL, it's necessary to invoke `spdlog::shutdown()` before exiting the application, as it is obtained by the code in the DLL.

Perhaps it leaked because the application ended without releasing the thread pool of DLL.

**Comment by haquocviet** [comment]
Thanks tt4g for reply. 
Your information helps me. The leak disappeared when spdlog::shutdown() is called at the end of life of the dll.
