### ISSUE TITLE
segmentation fault in shared library

### ISSUE THREAD

**Issue by abudaev** [gabime/spdlog#1154]
Hello! I try create a logger wrapper for using in shared library.

`#ifndef LIB_LOG_H
#define LIB_LOG_H

#include <spdlog/logger.h>
#include <spdlog/sinks/rotating_file_sink.h>

#define TRACE(...) SPDLOG_TRACE(__VA_ARGS__)
#define ERROR(...) SPDLOG_ERROR(__VA_ARGS__)
#define INFO(...)  SPDLOG_INFO(__VA_ARGS__)
#define DEBUG(...) SPDLOG_DEBUG(__VA_ARGS__)
#define WARNING(...) SPDLOG_WARN(__VA_ARGS__)
namespace demo{
       namespace logger {

             static const std::string logger_name(
                    "cti");
             class log {
             public:
                    static log& instance() {
                           static log driver_logger;
                           return driver_logger;
                    }
                    template<typename... Args>
                    static void info(const Args&... args) {
                           INFO(args...);
                    }
                    template<typename... Args>
                    static void error(const Args&... args) {
                           ERROR(args...);
                    }
                    template<typename... Args>
                    static void warn(const Args&... args) {
                           WARNING(args...);
                    }
                    template<typename... Args>
                    static void debug(const Args&... args) {
                           DEBUG(args...);
                    }
                    template<typename... Args>
                    static void trace(const Args&... args) {
                           TRACE(args...);
                    }
             private:
                    log() {
                           auto check = spdlog::get(logger_name);
                           if (check == nullptr) {

                                  auto sinks = std::make_shared<spdlog::sinks::rotating_file_sink_mt>("logs/driver.txt", 1048576 * 100, 20);
                                  auto logger = std::make_shared<spdlog::logger>(logger_name, sinks);
                                  logger->set_level(spdlog::level::trace);
                                  logger->set_pattern("%Y-%m-%d %H:%M:%S.%f [%P:%t] [%l] [%s:%!] %v");
                                  logger->flush_on(spdlog::level::trace);
                                  spdlog::register_logger(logger);
                                  spdlog::set_default_logger(logger);
                           }
                    };
                    log(const log&) = delete;
                    void operator=(const log&) = delete;
             };
             template < typename... Args >
             static void debug(const Args
                    &... args) {
                    log::instance().debug(args...);
             }
             template < typename... Args >
             static void info(const Args
                    &... args) {
                    log::instance().info(args...);
             }
             template < typename... Args >
             static void warn(const Args
                    &... args) {
                    log::instance().warn(args...);
             }
             template < typename... Args >
             static void error(const Args
                    &... args) {
                    log::instance().error(args...);
             }
             template < typename... Args >
             static void trace(const Args
                    &... args) {
                    log::instance().trace(args...);
             }
       }
};
#endif //LIB_LOG_H`

Then i try call demo::info("test"); my program who using my lib crash with segmentation fault error. What i do incorrect?
I trying to start using spdlog within 7 days, but not success. Sametime i get working code, but when i try using on lib - his crash. Working fine if i use in 1 class only, when i try using in all class i getting an error. Please, help me!

**Comment by tt4g** [comment]
Please check the wiki: https://github.com/gabime/spdlog/wiki/How-to-use-spdlog-in-DLLs

Since spdlog v1.3.1 is a header only library, the spdlog registry is not shared between shared library and application when creating a shared library.

Probably `demo::log::instance()::info(...)` does not cause a problem.
This is because it accesses the shared library spdlog registry.

It seems that `demo::log::info()` directly calls the `SPDLOG_INFO(__VA_ARGS__)` macro.
This macro should be accessing the default logger of the application's spdlog registry.

The shared library spdlog registroy seems to be set up with the `demo::log::log()` constructor, but I do not know if it is set up by the application.

**Comment by abudaev** [comment]
I know by heart this page [https://github.com/gabime/spdlog/wiki/How-to-use-spdlog-in-DLLs
](https://github.com/gabime/spdlog/wiki/How-to-use-spdlog-in-DLLs
).
Constructor call on instance function in static variable driver_logger (i think is it).
In constructor i set register this logger and set as default it mean then i call MACRO he use my logger.

**Comment by tt4g** [comment]
The provided code looks like the contents of the library header file that contains the implementation.
Problems often occur when the library header file contains implementation content.

As you may know, macros are expanded to just strings in preprocessing.
And the header include just copies the contents of the header file.
This means that the same implementation code is defined twice in both the library and the application.

spdlog registry is a global variable.
The spdlog registry address does not match across library boundaries because shared libraries and applications are linked after being built with different translation units, even though they contain the same header file.

**Comment by tt4g** [comment]
I think the simple solution is to leave the declaration in the header file and write the implementation in a separate source file, Then I think that the call to `demo::log::info()` will access the same spdlog registry.

**Comment by gabime** [comment]
Please try using the compiled version v1.4.0. This should help to prevent such problems

**Comment by abudaev** [comment]
Where i can find this version?) In github not release 1.4.0 and any branch or tag match 1.4.0

**Comment by gabime** [comment]
It is in the repo only. Not released yet but pretty stable

**Comment by abudaev** [comment]
But it's not usable for me on many reasons.
1. I'am use closed network without sync repo
2. I'am need lib on Rhel 6.x and Solaris 11.2 - lib missing in standart repo.

I'am need only source for this verison.



I'am try to simple example in my shared lib to 3 string code:
#include <spdlog/spdlog.h>
const std::string logger_name "demo";
auto logger = spdlog::get(logger_name);

And ta-dam - segmentation fault after exec application and loading lib.
It's running on Rhel6.10 with gcc 4.8.2 and some result on Solaris 11.2 and gcc 4.8

**Comment by tt4g** [comment]
`spdlog::get()` is a function to get the logger already registered in spdlog registry.

You need to have registered the logger as `spdlog::register_logger()` or call factory funcion (e.g. `spdlog::rotating_file_logger_mt()`) in spdlog registry: https://github.com/gabime/spdlog/wiki/2.-Creating-loggers#accessing-loggers-using-spdlogget

In the three-line snippet you provided, an invalid `std::shared_ptr` is returned because `spdlog::get(logger_name)` specifies a non-existent logger name.

**Comment by abudaev** [comment]
> `spdlog::get()` is a function to get the logger already registered in spdlog registry.
> 
> You need to have registered the logger as `spdlog::register_logger()` or call factory funcion (e.g. `spdlog::rotating_file_logger_mt()`) in spdlog registry: https://github.com/gabime/spdlog/wiki/2.-Creating-loggers#accessing-loggers-using-spdlogget
> 
> In the three-line snippet you provided, an invalid `std::shared_ptr` is returned because `spdlog::get(logger_name)` specifies a non-existent logger name.

It's return nullptr.
spdlog::info("set");
from https://github.com/gabime/spdlog/Readme.md#basic_usage
 same result.
I'am close a ticket and return after i get working solution in my application.

**Comment by gabime** [comment]
Thanks @tt4g for clearing this out
