### ISSUE TITLE
I guess macros should not be wrapped in conditions

### ISSUE THREAD

**Issue by xahon** [gabime/spdlog#1236]
I guess macros `SPDLOG_XXXX` and `SPDLOG_LOGGER_XXXXX` should be available everytime and level should be controlled by `spdlog::set_default_level` because changing levels in preprocessor causes recompilation and editing the sources of the library (or set define in compilation args and make compilation tool-dependent). 
Anyways macros still refer to underlying `spdlog::xxx` checks if level is correct for logging.
So I can't use `spdlog::xxxx` methods because I need to log filename also

**Comment by gabime** [comment]
The point of the macros is **zero** cost (they are replaced with empty statement at compile time)if the level is not activated. Otherwise there is no point to use them.

Also note that there is no need to recompile the lib sources when changing SPDLOG_ACTIVE_LEVEL. It only affects the macros which are included in the header file.
