### ISSUE TITLE
How can I get the log string?

### ISSUE THREAD

**Issue by hackershi** [gabime/spdlog#1300]
For example:
 string log_string = spdlog::info("my info").str();
I want log_string to be equal to  string("[2019-11-6 21:43:46] [info] [test.cpp] my info").
How can I do it?

**Comment by tt4g** [comment]
IMO.

The sample code API cannot be provided for the following reasons:

* Messages are formatted in two places: logger and sink. In addition, sink delays formatting until `sink::flush()`.
* In order to avoid useless formatting, messages may not be formatted depending on conditions such as log level.

I think you need to inherit `base_sink` and implement interceptor-pattern to steal messages.; https://en.wikipedia.org/wiki/Interceptor_pattern

**Comment by gabime** [comment]
You can use  ostream_sink_mt sink to capture the log into a string

See this [example ](https://github.com/gabime/spdlog/blob/436ce16e79b302a759a5687377aafb668f6d4101/tests/test_pattern_formatter.cpp#L7)on how to achieve this.

**Comment by tt4g** [comment]
> (@tt4g sinks dont delay formatting until sink::flush() is called)

Sorry. It was my misunderstanding.
