### ISSUE TITLE
Linking time

### ISSUE THREAD

**Issue by cmmw** [gabime/spdlog#1375]
Hello,

linking a simple "main.cpp" which only prints "Hello world"  via spdlog::info() takes 15 seconds to build in debug.

I am wondering if that is normal or if there is something wrong on my side? I am using gcc on windows (mingw-w64). Release build takes about 2 seconds, that's fine.

**Comment by tt4g** [comment]
Although not an accurate answer, MinGW is known to be not very fast.
It seems to be slow because a UNIX-like API layer is built on the Windows API.

The following are links that will be helpful.

* [c\+\+ \- Why is gdb so slow in Windows? \- Stack Overflow](https://stackoverflow.com/questions/27380443/why-is-gdb-so-slow-in-windows)
* [c\+\+ \- Why is MinGW very slow? \- Stack Overflow](https://stackoverflow.com/questions/929495/why-is-mingw-very-slow)
* [MinGW \- User \- Debugging with GDB on Windows / MinGW is painfully slow](http://mingw.5.n7.nabble.com/Debugging-with-GDB-on-Windows-MinGW-is-painfully-slow-td23877.html)

**Comment by thomaswillecomme** [comment]
I know it is closed and not a bug so you can keep it that way, just providing some information to people experiencing this problem.
I just switched from boost::log to spdlog as I have a big software using many layers of plugins (boost is not able to unload itself from dynamic library)
By the way very nice library, takes way less time to configure or understand than boost !
So far so good on linux as it usues the dynamic library libspdlog.so, linkage is fast.
On mingw, there is no dynamic library and cmake (spdlog::spdlog) point to the static version which indeed takes ages to link
spdlog.a and fmt.a as the linker have to remove all unused symbols from the 1.5 mbytes of libraries. the cmake files does not provides a way to use the dynamic version of fmt either which would save a bit of linking time/size
using cmake (spdlog::spdlog_header_only) does not help either
I believe the only way is to built it yourself as a dll and provide a cmake config. If i have some time to do it i will share it but i believe there is some reason why it is only static/header only
