### ISSUE TITLE
cloned logger and registry

### ISSUE THREAD

**Issue by mipac** [gabime/spdlog#1395]
Hi,

Is a cloned logger automaticaly add to registry or do we have to register it manually?

I don't understand the registry... it's possible to have loggers in, and some loggers not registered
What is the point if all loggers are registered?
Could it be interesting to systematically add a new logger, or a clone, to the registry?

**Comment by tt4g** [comment]
If you want to add cloned logger to registry, call `spdlog::register_logger(logger->clone())`.

Registered loggers are affected by several registry manipulation API such as `spdlog::set_formatter()`, `spdlog::flush_every()`, `spdlog::apply_all()`.

**Comment by mipac** [comment]
thanks for reply!


you need to give a name to the cloned logger, the api force it

and you have to choose a name not present in the registry when register it

it would be coherent to auto add a clone to registry, if the original
logger was

thx again for your answer

**Comment by tt4g** [comment]
The registry must specify a name to distinguish loggers by name.

Factory functions such as `spdlog::basic_logger_mt()` create a logger and register it in the registry. However, the `spdlog::logger::logger()` constructor does not register in the registry.

I think that the behavior of `spdlog::logger::clone()` is consistent, because registration in the registry is a feature of the factory.
