### ISSUE TITLE
Use compiled version with Makefile

### ISSUE THREAD

**Issue by 0x3333** [gabime/spdlog#1402]
In my application, it is taking an eternity to compile, I'd like to use the compiled version, but I'm not using cmake, I'm using plain makefile. Is that possible?

Thanks!

**Comment by tt4g** [comment]
I'm not an expert because I have little customization experience with autotools.
However, I know you can do what you want on the machine where the library is installed.


Install the spdlog static library on your machine with the following command (https://github.com/gabime/spdlog/tree/v1.5.0#static-lib-version-recommended---much-faster-compile-times that added install step).

```
$ cd ${YOUR_SPDLOG_SOURCE_DIRECTORY} && mkdir build && cd build
$ cmake .. && make -j && make install
```

Then specify the installed spdlog library and the spdlog header path in Makefile.

The following links for help:

* https://stackoverflow.com/questions/11344965/how-to-include-static-library-in-makefile
* https://stackoverflow.com/questions/22618466/is-it-possible-to-set-the-compiling-and-linking-flags-in-makefile-am-instead-of
