### ISSUE TITLE
'spdlog/common.h' not found with <angled> use "quotes" instead in XCode.

### ISSUE THREAD

**Issue by ShazerHD** [gabime/spdlog#1464]
Hello all,

I am trying to use spdlog with a project I am making and I am trying to compile it on MacOS. I currently do not want to use CMake in my project. I am getting the error 'spdlog/common.h' not found with <angled> use "quotes" instead when trying to compile in XCode. Is there any easy fix for this?

Thanks.

**Comment by tt4g** [comment]
Is the spdlog header directory specified in the compiler options?

**Comment by ShazerHD** [comment]
I am using premake to generate project files and I have them included in there. I should also mention that this is coming from the target and not the project.

**Comment by ShazerHD** [comment]
I somehow got it working.

**Comment by henrytien** [comment]
I have the same error,  and I have specified in the compiler options, but it doesn't work.
![image](https://user-images.githubusercontent.com/7891852/77639175-48c58000-6f93-11ea-8cce-4aeb73bf95d4.png)

**Comment by nmrsmn** [comment]
Anyone found the solution yet? I'm having the same problems

**Comment by henrytien** [comment]
@nmrsmn you can check out here https://github.com/gabime/spdlog/issues/1493, c++ Language Dialect should be std=c++11, and I use $(SRCROOT)/xxx in Hear Search Paths.

**Comment by rrafis** [comment]
Hi everyone,

A bit late to the party but maybe it will be useful for others.
Had the same issue with spdlog in particular and other third party libraries as well.
I use premake to generate solution for multiple platforms and encounter this issue as well.

For me solution was simple, put your third party lib include under **sysincludedirs** instead of includedirs. Premake will automatically put them under System Header Search Path for Xcode. _ includedirs_ puts them to User Header Search Path.

Note: resincludedirs doesn't work for me and with externalincludedirs solution wouldn't generate for me. So I settled up with sysincludedirs it works fine with both "" and <>.
