### ISSUE TITLE
backtrace is not working when call log(level, ...) method directly 

### ISSUE THREAD

**Issue by blackball** [gabime/spdlog#1465]
Here are my codes to reproduce the issue. I am using the master. (tag: 0120dcc787b818f2ce3207467e1c1515360f5385 )

```C++

#include <spdlog/sinks/stdout_color_sinks.h>
#include <spdlog/spdlog.h>

int main(int argc, char *argv[]) {
    auto logger = spdlog::stdout_color_mt("console");
    logger->enable_backtrace(32);  
    for (int i = 0; i < 10000; i++) {
        // TODO: call following line will also output all log messages, this is should be bug
        // logger->log(static_cast<spdlog::level::level_enum>(3), "AAAA");
        // But use following line is fine.
        logger->debug("Backtrace message {}", i);  // not logged yet..
    }
    logger->dump_backtrace();  // log them now! show the last 32 messages
    logger->disable_backtrace();
    return 0;
}
```

FYI.

**Comment by tt4g** [comment]
This seems to be a matter of log level differences.

The default value of `spdlog::logger::level()` is `spdlog::level_enum::info`, and the default value of `spdlog::sinks::sink::level()` is `spdlog::level_enum::trace`.

`static_cast<spdlog::level::level_enum>(3)` is `spdlog::level_enum::warn`.
The log is output because it is higher than the logger log level.

However, `spdlog::logger::debug()` is not output because `spdlog::level_enum::debug` is below the log level of the logger.


`spdlog::logger::dump_backtrace()` ignores logger log levels.

**Comment by gabime** [comment]
@tt4g is right. This is the intended behaviour.
