### ISSUE TITLE
undefined reference to `spdlog::default_logger_raw()'

### ISSUE THREAD

**Issue by longuyen97** [gabime/spdlog#1546]
I want to use spdlog for my project but I can not get spdlog started. I always get the following error messages:

```
Scanning dependencies of target main
[ 50%] Building CXX object CMakeFiles/main.dir/main.cpp.o
[100%] Linking CXX executable bin/main
CMakeFiles/main.dir/main.cpp.o: In function `void spdlog::info<char [19]>(char const (&) [19])':
/home/long/.conan/data/spdlog/1.5.0/_/_/package/8247ecba614e24951ef87d11e3eab4c7d91aba06/include/spdlog/spdlog.h:201: undefined reference to `spdlog::default_logger_raw()'
CMakeFiles/main.dir/main.cpp.o: In function `void spdlog::logger::log<char [19], (char (*) [19])0>(spdlog::source_loc, spdlog::level::level_enum, char const (&) [19])':
/home/long/.conan/data/spdlog/1.5.0/_/_/package/8247ecba614e24951ef87d11e3eab4c7d91aba06/include/spdlog/logger.h:148: undefined reference to `spdlog::details::backtracer::enabled() const'
/home/long/.conan/data/spdlog/1.5.0/_/_/package/8247ecba614e24951ef87d11e3eab4c7d91aba06/include/spdlog/logger.h:154: undefined reference to `spdlog::details::log_msg::log_msg(spdlog::source_loc, fmt::v6::basic_string_view<char>, spdlog::level::level_enum, fmt::v6::basic_string_view<char>)'
/home/long/.conan/data/spdlog/1.5.0/_/_/package/8247ecba614e24951ef87d11e3eab4c7d91aba06/include/spdlog/logger.h:155: undefined reference to `spdlog::logger::log_it_(spdlog::details::log_msg const&, bool, bool)'
collect2: error: ld returned 1 exit status
```

This is how I include spdlog in my project with conan:

```
from conans import ConanFile, CMake

class PocoTimerConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    requires = "catch2/2.11.3", "nlohmann_json/3.7.3", "spdlog/1.5.0"
    generators = "cmake"
```

**Comment by tt4g** [comment]
Sounds like conan problem.
However, I am using Conan as well, so I have an idea about the missing settings.

Your project is using CMake? If so, your application must link `${CONAN_LIBS}` or CMake target `CONAN_PKG::spdlog` (`CONAN_PKG::spdlog` is instead of CMake target `spdlog::spdlog`).
This is because [catch2](https://github.com/catchorg/Catch2) and [nlohmann_json](https://github.com/nlohmann/json) are header-only libraries but spdlog provided by conan is compiled library ([look conan spdlog recipe](https://github.com/conan-io/conan-center-index/blob/ba8a320c81c8ddae1efc28a66d261d9732ad86f2/recipes/spdlog/all/conanfile.py#L25), that is not provide header-only spdlog by default).

I recommended read conan official documentation: https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_generator.html

See also official conan and cmake integration tool cmake-conan: https://docs.conan.io/en/latest/howtos/cmake_launch.html#how-to-launch-conan-install-from-cmake and https://github.com/conan-io/cmake-conan

I recommend opening additional questions in the [conan-center-index repo](https://github.com/conan-io/conan-center-index).

**Comment by longuyen97** [comment]
@tt4g Thank for your help. I added the following to my CMake and it worked:

```
add_executable(main main.cpp)
target_link_libraries(main ${CONAN_LIBS})
```

Now I am getting the following error 

`[*** LOG ERROR #0001 ***] [2020-05-08 16:08:29] [] {std::bad_alloc}`

But I think it is another problem

**Comment by tt4g** [comment]
> But I think it is another problem

This message printed by spdlog default error handler.

https://github.com/gabime/spdlog/blob/cf6f1dd01e660d5865d68bf5fa78f6376b89470a/include/spdlog/logger-inl.h#L249

I think `std::bad_alloc` exception was passed to the default error handler.
Usually `std::bad_alloc` is thrown when out-of-memory. Is there enough memory for the process?

**Comment by longuyen97** [comment]
@tt4g I am pretty sure there is enough memory. I have like 64GB RAM on my PC and the process gets started normally without any restriction

**Comment by tt4g** [comment]
Is it possible to debug the source of the error?
