### ISSUE TITLE
Accessing sinks

### ISSUE THREAD

**Issue by OpenSiege** [gabime/spdlog#1561]
We had some code that setup a console logger:

`// always initialize the console logger first`
`auto log = spdlog::stdout_color_mt("log");`

Then we had a helper function that added the console sink to the file sinks as the logs get created (thread safety didn't matter at this point as our app is still booting up):

`// register all output to the console as well`
`auto console = spdlog::get("log")->sinks().back();`
`log->sinks().push_back(console);`

This seemed to be okay according to the wiki but looks like it broke somewhere along the way. What is the best way to do this going forward?

**Comment by mguidry-glodon** [comment]
I made an enhancement request for a named_dist_sink with the full source so you can get your sinks by name and if I understand correctly it seems like it may be able to help you out here. We use something like it to log to several files, streams and consoles with thread safe access while being able to access sinks with a key.

https://github.com/gabime/spdlog/issues/1547

**Comment by tt4g** [comment]
`spdlog::logger::sinks()` returns `std::vector<spdlog::sink_ptr`>&`.
Since this is a reference, calling `std::vector::push_back()` while accessing `std::vector` inside `spdlog::logger` will disable the iterator and cause a bug.

If you are changing `spdlog::sinks::sink` dynamically, then `spdlog::sinks::dist_sink` is thread-safe.

**Comment by gabime** [comment]
Your code looks ok to me..

>  looks like it broke somewhere..

@OpenSiege What do you mean ? could you provide a  sample  code to reproduce?

**Comment by OpenSiege** [comment]
@gabime This below won't compile for me with on Visual Studio 2019 with`std:c++17`
```
int main(int argc, char* argv[])
{
    auto log = spdlog::stdout_color_mt("log");
    auto filelog = spdlog::basic_logger_mt("filelog", "test.log");
    auto console = spdlog::get("log")->sinks().back();
    log->sinks().push_back(console);
    return 0;`
}
```

**Comment by gabime** [comment]
whats the error?

**Comment by tt4g** [comment]
@OpenSiege I write in anticipation. If I am writing something wrong, please ignore it.

I found your project OpenSiege/OpenSiege and Look this commit OpenSiege/OpenSiege@f686f3c0c424936726d4bcd75f47ed9084186107.
This commit removes the statement `#include <spdlog/sinks/file_sinks.h>`.

`spdlog/sinks/file_sinks.h` is present in spdlog v0.17.0 but has been removed in spdlog v1.0.0.
Perhaps the spdlog of your project is very old.
And spdlog v0.17.0 has only `spdlog::logger::sinks() const`.

https://github.com/gabime/spdlog/blob/560df2878ad308b27873b3cc5e810635d69cfad6/include/spdlog/logger.h#L121

`const std::vector` is a compilation error because it cannot call `std::vector::push_back()`.

**Comment by OpenSiege** [comment]
@tt4g Good catch. Looks like the new build system was grabbing the master branch rather than the v1.x branch. After updating to that new branch the errors is gone. Thanks again!
