### ISSUE TITLE
Old files not deleted when max reached and app restarts

### ISSUE THREAD

**Issue by IIFE** [gabime/spdlog#1566]
Hi.

This is sort of a follow up to #1531 

I have daily file sink setup so that it creates a new file every day (rotation hour 0) and keep a max of 7 files.

I tried to test the behaviour by moving the PC date forward one day. A new files gets created but no old files are deleted when the count reaches 8 or above. **Note:** I restart my app that uses spdlog after changing the date. Does the daily sink need the app to keep running in order to delete old files, or should it work when app is restarted?

**Comment by tt4g** [comment]
@IIFE AFAIK, daily sink delete old filed when calling `spdlog::sinks::daily_file_sink::dink_it_()`.
The constructor of `spdlog::sinks::daily_file_sink` doesn't seem to do any rotate deletion.

https://github.com/gabime/spdlog/blob/83b9149930f392d7797b54fe97a66ab3f2120671/include/spdlog/sinks/daily_file_sink.h#L80-L99

In order to avoid throwing an exception by deleting the file in the daily_sink constructor, it is designed to delete the file only when the log is output (Note that I'm writing this as a guess since I didn't add this feature).

https://github.com/gabime/spdlog/blob/83b9149930f392d7797b54fe97a66ab3f2120671/include/spdlog/sinks/daily_file_sink.h#L151-L153

Maybe your application didn't output any logs during testing.

**Comment by IIFE** [comment]
@tt4g Thanks. My app is definitely logging messages on start up. I have debugged the code and the sinkt_it function gets called, however the should_rotate flag is always false.

I don't know if the daily file sink expects the app to continue running in order for old files to be deleted, and it's not handling the case where app is restarted. It's not very clear from the code.

**Comment by tt4g** [comment]
Oh, I'm sorry I missed something.
`should_rotate` is `true` if the time of the message indicates a time in the future from the next rotation time.
Only at this time, the old rotated files will be deleted.
In other words, the application must meet the rotation time as it continues to run.

**Comment by IIFE** [comment]
@tt4g Indeed, however the ctor when setting the next rotation time (next_rotation_tp_) for some reason adds 24 hours when the rotation time is after the current time, i.e.:

```
    log_clock::time_point next_rotation_tp_()
    {
        auto now = log_clock::now();
        tm date = now_tm(now);
        date.tm_hour = rotation_h_;
        date.tm_min = rotation_m_;
        date.tm_sec = 0;
        auto rotation_time = log_clock::from_time_t(std::mktime(&date));
        if (rotation_time > now)
        {
            return rotation_time;
        }
        return {rotation_time + std::chrono::hours(24)};
    }
```

This means that files are never getting deleted when app restarts.

**Comment by tt4g** [comment]
> This means that files are never getting deleted when app restarts.

@IIFE Yes. The `0` of `rotation_hour` means to rotate at midnight every day.
See this comment: https://github.com/gabime/spdlog/issues/1531#issuecomment-619170943

**Comment by IIFE** [comment]
@tt4g So to summarise, the daily file sink needs the app to continue running in order for it to pick up old files for deletion. It does not handle if an app closes and reopens to delete old files? Because I have run the app after setting the clock to midnight, and files don't get deleted.

**Comment by tt4g** [comment]
Right. The date must change to the next day while the application is running.

**Comment by IIFE** [comment]
@tt4g Thanks. I think I need to create a sink that handles when an app closes & reopens to delete old files.

**Comment by tt4g** [comment]
@IIFE I thought about implementing the `spdlog::sniks::daily_file_sink` constructor to remove a rotated file.


https://github.com/gabime/spdlog/blob/3dedb52163c4aa052dee61ea3de126c72faa02a8/include/spdlog/sinks/daily_file_sink.h#L94

**Comment by IIFE** [comment]
@tt4g I'm thinking I could just inherit from the daily file sink, let it do the default behaviour, and in the sink_it method override it with extra logic that deletes old files. Does that sound OK, or is there a better approach?

**Comment by tt4g** [comment]
@IIFE Sorry. I'm not a native speaker, so it took me a while to comment.
Once I've read the comments above, I'd like to share my realizations about rotates in `spdlog::sniks::daily_file_sink` constructor.

If your application outputs a log every day, I'm in agreement with deleting the rotated files with extra logic.

> I could just inherit from the daily file sink

`spdlog::sniks::daily_file_sink` has a final specifier, so you need to remove it.

https://github.com/gabime/spdlog/blob/3dedb52163c4aa052dee61ea3de126c72faa02a8/include/spdlog/sinks/daily_file_sink.h#L45

**Comment by IIFE** [comment]
@tt4g That's no problem.

After thinking about it for a while, I think there are two options I can follow:

- Create a new **rolling** sink, which deletes old files if we reach the max files specified. This happens in both the constructor and the sink_it_ method.
- Modify the existing daily file to behave like the above.

I think it's probably best if we make either change into spdlog itself as it's a common enough functionality.

Are you happy for me to create a PR, and if yes which approach do you prefer?

@gabime tagging you here as well.

**Comment by tt4g** [comment]
> * Create a new rolling sink, which deletes old files if we reach the max files specified. This happens in both the constructor and the sink_it_ method.
> * Modify the existing daily file to behave like the above.

@IIFE IMO. You should be able to create a new rolling sync based on `spdlog::sinks::rotating_file_sink`, which works very similarly.

I think it's okay to delete the rotated files in `spdlog::sniks::daily_file_sink` constructor.
However, in order to keep the existing behavior unchanged, additional optional arguments are added to the constructor arguments. e.g: `rotate_on_open = false`

I think pull requests to add or improve sink would be welcomed.

**Comment by IIFE** [comment]
I have just got the latest spdlog source and found that the version i'm using is slightly out of date with the latest source.

The latest source appears to have `init_filenames_q_` function that I don't. Therefore, I believe the simply fix now can be to ensure that old files are deleted in `sink_it_` function of `daily_file_sink` not only if the message time is after the rotation time, but also if the file names queue is full.

I can work on that fix if it sounds OK to you.

`rotating_file_sink` does not give me the same functionality because it's only based on file size, rather than days.

Thanks.

**Comment by IIFE** [comment]
@tt4g Acutally no, ignore my last comment. The old file deletion needs to happen in the constructor. `sink_it_` can stay with the current behaviour.

One thing I noticed though is that I don't think the file rotation is thread safe. The file queue and the rotation_tp_ are modified without a lock. Shouldn't this be fixed too?

**Comment by tt4g** [comment]
@IIFE No, `spdlog::sinks::daily_file_sink::rotation_tp_` is thread-safe because it is only read/written from `spdlog::sinks::sink::sink_it_()` and constructor.

`spdlog::sinks::daily_file_sink` is an inheritance of `spdlog::sinks::base_sink`, and `sink_it_()` is a virtual function defined in `spdlog::sinks::base_sink`.
And `sink_it_()` is not called in other than `spdlog::sinks::base_sink::log()`.
`spdlog::sinks::base_sink::log()` gets a lock on the `sink_it_()` before calling it, so `sink_it_()` is thread-safe.

https://github.com/gabime/spdlog/blob/3dedb52163c4aa052dee61ea3de126c72faa02a8/include/spdlog/sinks/base_sink.h#L42

https://github.com/gabime/spdlog/blob/3dedb52163c4aa052dee61ea3de126c72faa02a8/include/spdlog/sinks/base_sink-inl.h#L25-L30

This is the design of the spdlog.

**Comment by IIFE** [comment]
You're right, I missed the base implementation.

Currently working on the fix to delete old files in the ctor. Will create a PR once that's ready.

Thanks.

**Comment by IIFE** [comment]
@tt4g PR created now to fix issue. Thanks.
