### ISSUE TITLE
Issues with `stdout_color_sink_mt` and long strings

### ISSUE THREAD

**Issue by wcpfeffer** [gabime/spdlog#1592]
Question.

Are there any known issues or limitations with very large strings?

I have two sinks, a `daily_file_sink` and a `stdout_color_sink_mt` and an `async_logger`. When I log extremely large strings (290k), and if i have both enabled, the result is that it will block for a minute or so upon trying to log the long string. If I disable the `stdout_color_sink_mt` nothing blocks and its fine.

Any ideas what may be causing this issue?

**Comment by tt4g** [comment]
Console output seems to be very slow at times.

Writes to disk are buffered by the OS to make it run faster.
However, the console seems to be slower because it is not buffered.

I referred to the following link:

* [python \- Why is printing to stdout so slow? Can it be sped up? \- Stack Overflow](https://stackoverflow.com/questions/3857052/why-is-printing-to-stdout-so-slow-can-it-be-sped-up)

You can use the `strace -t` command to check if the OS system call is taking a long time.

**Comment by wcpfeffer** [comment]
Gotcha, I think you are correct. It seems to hang on the call to `fflush(...)` in the `ansicolor_sink`. 

Thanks for responding!
