### ISSUE TITLE
Very large binary files in git history

### ISSUE THREAD

**Issue by amurzeau** [gabime/spdlog#1654]
Hi,

I found by cloning the git repository, that it is 40 MiB large.
The reason is that there are binary files in the git history:
```sh
$ git rev-list --objects --all \
> | git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' \
> | sed -n 's/^blob //p' \
> | sort --numeric-sort --key=2 \
> | cut -c 1-12,41- \
> | $(command -v gnumfmt || echo numfmt) --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest
[...]
e94ec338149a  170KiB win64-release/spdlog.dir/Release/spdlog.nativecodeanalysis.sarif
fcc57232552c  197KiB build/gcc/release/factory.o
5b616a2b60d8  328KiB tests/catch.hpp
5585d1e3517a  337KiB tests/catch.hpp
925c6bffa7d5  337KiB tests/catch.hpp
5f13d506dae5  394KiB build/gcc/libc11log.a
02302b8d3e97  540KiB tests/catch.hpp
225f4f0b7bef   39MiB tests/.vs/tests/v15/Browse.VC.db
418fe7456c43   94MiB tests/.vs/tests/v15/ipch/AutoPCH/945b5b8b65520f8e/ERRORS.ipch
```

Especially the last 2 ones: `ERRORS.ipch` and `Browse.VC.db` which are very larges.

I wonder if this is known and maybe an history rewrite might be a solution.
But I would totally understand if it is preferred to keep the history as-is despite the big files to avoid breaking everyone clones.

**Comment by gabime** [comment]
It got in there by mistake. I don't mind removing them but not sure how to do it safetly without messing up the repo.

**Comment by amurzeau** [comment]
If your are not comfortable with removing files from git history, maybe just close this issue.

I've done a bit research to see if another popular git repository rewritten its history, but didn't find anything really relevant.
In most case, it is a matter of:
 - Tell everyone to commit and stop working on the repo
 - Do the git history rewrite
 - Tell everyone to reclone or maybe just rebase their local repo

Maybe github can sort out open PR and rebase the right commits only without trying to duplicate everything, but I don't have an existing case that demonstrate this.

**Comment by gabime** [comment]
I’d rather stay on the safe side and live with it. Thanks for reporting!

**Comment by aloisklink** [comment]
As a work-around, newer versions of `git` allow doing something called a "blobless clone" using `git clone --filter=blob:none https://github.com/gabime/spdlog.git`.

git will then automatically download the required blobs whenever you do a `git blame`/`git log --patch`/`git checkout`.

That way, my `.git` folder for spdlog is only 3.2 MiB instead of 42 MiB!

```console
user@pc:~/$ du --summarize --human-readable spdlog-full-clone/.git spdlog-blobless-clone/.git
42M	spdlog-full-clone/.git
3.2M	spdlog-blobless-clone/.git
```

This is actually what GitHub recommends people to use for checking out repos in most cases (`git clone --depth=1` (shallow clone) is better for CI, but it's super expensive to do `git pull`/`git fetch` on later, so it's not recommended for development), see https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/.
