### ISSUE TITLE
slow slow slow to compile

### ISSUE THREAD

**Issue by alexpanter** [gabime/spdlog#1708]
Hi people,

I will say briefly that I absolutely adore the interface of spdlog. Generally well-designed, so I would like to actually use it.

My problem is, that it is horrendously slow to compile. And because it uses templates, every time I log with a new combination of print-formatted arguments, I need to recompile spdlog.
This is expected and not a bad thing. The bad thing is that it takes usually up to several seconds to do this. And I'm compiling on a high-end I7 processor.

I have tried to include spdlog both as header-only, and as built (both static and dynamic). In all instances, the compile times are just unacceptable.

Does anyone have good recommendations?
Perhaps I can use only a subset of the files, or skip over certain features.

Context: I'm building a game engine, and definitely want to strip out (most) logging of the production builds. So I don't particularly care that runtime-logging is the fastest, but I do care about having to compile it all the time.

Any help is greatly appreciated.
Thanks in advance.
And thank you for making what I truly belive is an amazing logging library.

-- Alexander

**Comment by gabime** [comment]
How do you use the compiled version? It shouldn't be so slow.
Make sure that SPDLOG_COMPILED_LIB is defined

**Comment by alexpanter** [comment]
I'm using premake to generate a bunch of Makefile's. Something along the lines of
* Spdlog
* Engine
* SampleGame

Currently I'm defining SPDLOG_COMPILED_LIB with gcc on the command line, for all projects, and not only when I build Spdlog - is that the correct way of doing it?

But I'm happy to hear you say that it shouldn't be so slow. Then the issue is probably elsewhere.

**Comment by gabime** [comment]
> is that the correct way of doing it?

Yes, this is the way.

**Comment by GaganDhanoa** [comment]
Hey,
I have tried to include spdlog library into my Cmake project (just a main.cpp with basic spdlog functions) using multiple ways.

1. Just copy spdlog folder into my source and use #include directive
2. Use precompiled headers (#include directive for spdlog in pch.h and pch.h added to project using `target_precompile_headers(${PROJECT_NAME} PRIVATE pch.h)`)
3. Use spdlog library(installed via vcpkg) by: `find_package(spdlog REQUIRED); target_link_libraries(${PROJECT_NAME} PRIVATE spdlog::spdlog )`

These are compilation times for the 3 methods when I make a small change in main.cpp (note: precompile time in method 2 is ignored): 

----Method 1
[1/2] Building CXX object CMakeFiles/test.dir/main.cpp.obj
Elapsed time: 22 s. (time), 21.904 s. (clock)
[2/2] Linking CXX executable test.exe
Elapsed time: 18 s. (time), 18.311 s. (clock)
----Method 2
[1/2] Building CXX object CMakeFiles/test.dir/main.cpp.obj
Elapsed time: 18 s. (time), 18.231 s. (clock)
[2/2] Linking CXX executable test.exe
Elapsed time: 22 s. (time), 21.604 s. (clock)
----Method 3
[1/2] Building CXX object CMakeFiles/test.dir/main.cpp.obj
Elapsed time: 7 s. (time), 6.805 s. (clock)
[2/2] Linking CXX executable test.exe
Elapsed time: 16 s. (time), 15.244 s. (clock)

**Conclusion**
Linking the spdlog library in a barebones project still gives ~22 secs build time. By removing all spdlog traces, build is done in ~1sec.

Is there something different I need to do to reduce build time when using spdlog? Or is this the expected behaviour?


P.S. Total Build times of method 1 and method 2 are same. What good is pre-compiled headers if its gonna reduce compilation/creation of .obj file but increase link time => Total Build time similar.

**Comment by gabime** [comment]
Make sure the SPDLOG_COMPILED is defined before compiling and using

**Comment by GaganDhanoa** [comment]
Can you please elaborate. 
Where do I need to define SPDLOG_COMPILED and how is it defined?

I'm using Cmake to link to x64-mingw-static libspdlog.a created by vcpkg.

**Comment by gabime** [comment]
sorry it is SPDLOG_COMPILED_LIB that need to be defined.
 It just need to  be defined (eg gcc -DSPDLOG_COMPILED_LIB main.cc) before the include “spdlog.h” get processed, otherwise spdlog will use the header only version.

**Comment by GaganDhanoa** [comment]
Thanks gabime, you have created an awesome logging library. I was reading the issue thread of how you created the .lib version of your header only library and the effort was worth it. Build times using the .lib version are much faster than precompiling header only spdlog.

If you are interested I did some Build time analysis of spdlog. Build time of using spdlog as precompiled header only vs linking .lib version are compared.
https://stackoverflow.com/questions/72726977/does-pre-compiling-c-header-files-slows-down-linking-time/

**Comment by nurettin** [comment]
Compiling with 

```
#define SPDLOG_COMPILED_LIB
#include <spdlog/spdlog.h>
```
and `-l spdlog`

6 seconds

Compiling with 

```
#include <spdlog/spdlog.h>
```
without linking

9 seconds

I guess that's the best we can do.

**Comment by lgylylyct** [comment]
if you use QT, you can add `DEFINES += SPDLOG_COMPILED_LIB` in the xxx.pro.
