### ISSUE TITLE
LOG ERROR #0001

### ISSUE THREAD

**Issue by cangfeng110** [gabime/spdlog#1720]
* when i use spdlog, have times error like that, When this error occurs, it will happen times in a period time.  But this error is hard to happen. I tried to reproduce the problem, but I can’t reproduce it
```
[*** LOG ERROE #0001 *** ] [2020-09-30 10:19:28] [cooperative] {std::bad_alloc}
```
* the code like this
```
class Logger {
public:
    Logger(): hour_(0), minute_(0), truncate_(false), max_files_(15) {}

    void init(int max_files) {
        max_files_ = max_files;
        loggers_["cooperative"] = spdlog::daily_logger_mt<spdlog::async_factory>(
            "cooperative", "logs/log.txt", hour_, minute_,
            truncate_, max_files_);
        loggers_["mqtt"] = spdlog::daily_logger_mt<spdlog::async_factory>(
            "mqtt", "logs/mqtt.txt", hour_, minute_,
            truncate_, max_files_);
        loggers_["v2x"] = spdlog::daily_logger_mt<spdlog::async_factory>(
            "v2x", "logs/v2x.txt", hour_, minute_,
            truncate_, max_files_);
        spdlog::set_level(spdlog::level::debug);
        spdlog::set_pattern("{\"timestamp\":\"%H:%M:%S.%e\",\"info\":\"[%n][%l]\",%v}");
    }

    std::shared_ptr<spdlog::logger> get_logger(const std::string& log) {
        return loggers_[log];
    }

private:
    std::map<std::string, std::shared_ptr<spdlog::logger>> loggers_;
    int hour_;
    int minute_;
    bool truncate_;
    int max_files_;
};
```

**Comment by tt4g** [comment]
The error message is printed when `catch` an error in spdlog.

In most cases, `throw std::bad_alloc` when memory allocation failure.
Does your machine have enough memory?

**Comment by cangfeng110** [comment]
You mean there is not enough memory when writing log?

**Comment by tt4g** [comment]
Yes. If a non-null-terminated character is passed, it may try to allocate a very large amount of memory.

**Comment by cangfeng110** [comment]
Can you give an example to illustrate this situation

**Comment by tt4g** [comment]
Unfortunately, it's difficult to provide code that can reliably reproduce the defects related to memory allocation in C++.
This is because memory-related failures are highly dependent on the machine, the compiler, and the circumstances under which memory is allocated.

This is an example of outputting the following non-null-terminated `char *` to the log (https://github.com/tt4g/spdlog-issue-1720):

<details>
<summary>Example</summary>

```cpp
#include "spdlog/spdlog.h"
#include "spdlog/sinks/stdout_sinks.h"

#include <iostream>
#include <memory>

int main(int, char**) {

    spdlog::set_error_handler([](const std::string &msg) { std::cerr << "error handler: " << msg.c_str() << "\n"; });

    auto stdout_logger =
        std::make_shared<spdlog::logger>("stdout_logger", std::make_shared<spdlog::sinks::stdout_sink_mt>());
    spdlog::initialize_logger(stdout_logger);

    const char *terminated_chars = "Hello, World!";
    stdout_logger->info("terminated: {0}", terminated_chars);

    // Hello, World!
    const char non_terminated_chars[] =
        {'H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd', '!'};

    stdout_logger->info("no terminated: {0}", non_terminated_chars);

    return 0;
}

```
</details>

Perhaps a second `Hello, World' ends with an invalid character.
The output should be completed at the point where the null-terminated char happens to appear, but the
By the time a null-terminated char appears, it may cause a memory access violation or other problems.

**Comment by cangfeng110** [comment]
thank you very much
