### ISSUE TITLE
Level 4 warning when building x86 MSVC

### ISSUE THREAD

**Issue by WattsUp** [gabime/spdlog#1748]
Building spdlog v1.8.0 in x86 MSVC (19.28.29334.0) with `\Wx \W4` flags fails with:
**Warning C4702**
File: `details/os-inl.h` on [line 249](https://github.com/gabime/spdlog/blob/4a9ccf7e38e257feecce0c579a782741254eaeef/include/spdlog/details/os-inl.h#L249)
```C++
// Return file size according to open FILE* object
SPDLOG_INLINE size_t filesize(FILE *f)
{
    //...
    throw_spdlog_ex("Failed getting file size from fd", errno);
    return 0; // will not be reached.
}
```

**Comment by johannes-schmitt** [comment]
I had the same issue.
After setting /GL compiler flag, the warning disappeared.

To set the flag in Visual Studio, go to project properties > General and set "Whole Program Optimization" to "Use Link Time Code Generation".

This is not fixing the root cause, though. But it may provide a solution to others.
