### ISSUE TITLE
how to enable milliseconds resolution timestamps

### ISSUE THREAD

**Issue by muzammil360** [gabime/spdlog#1753]
I get following log lines. How can i enable milliseconds level accuracy? Also is the timestamp corresponding to the log line flush event or the instant when it was actually pushed to logger?

```
[2020-11-26 08:25:04 +00:00] [myclass] [info] [Process 17] [Thread 309] done 1
[2020-11-26 08:25:04 +00:00] [myclass] [info] [Process 17] [Thread 311] done 2
```

**Comment by tt4g** [comment]
Change logger format with `spdlog::set_pattern()` and see WIKI: https://github.com/gabime/spdlog/wiki/3.-Custom-formatting#pattern-flags

**Comment by tt4g** [comment]
> Also is the timestamp corresponding to the log line flush event or the instant when it was actually pushed to logger?

The log time is recorded as the time the logger received the message.

**Comment by johan-boule** [comment]
`void format(const details::log_msg &msg, const std::tm &, memory_buf_t &dest)`
In the formater functions, is it a leftover of a previous design to have the time available both as `msg.time` (std::chrono::system_clock's time_point) and as a `std::tm` struct (which is limited to seconds) ?
If not, what's the difference, appart from the resolution ?

**Comment by gabime** [comment]
The ```std::tm``` is a cached value for optimization purpose. It reduces the rate of calculating tm to once a second instead of recalculating it for each message, which can be expensive.
For higher resolutions (millis, micros, etc.) the formatter uses the msg.time value directly.

see https://github.com/gabime/spdlog/blob/4b3687f1a61912b778986cf5ac304e287aaebdd4/include/spdlog/pattern_formatter-inl.h#L1052-#L1062
