### ISSUE TITLE
Why thread id is equal to process id

### ISSUE THREAD

**Issue by Githubwyb** [gabime/spdlog#1761]
I use %P:%t format, but the log shows two same number which is actually process id, am I use the format right?

**Comment by tt4g** [comment]
In the Linux , the process ID and thread ID are the same when there is only a main thread (Look https://stackoverflow.com/questions/4517301/difference-between-pid-and-tid/8787888).

Start a new thread and make sure the thread ID is different.

**Comment by Githubwyb** [comment]
> In the Linux , the process ID and thread ID are the same when there is only a main thread (Look https://stackoverflow.com/questions/4517301/difference-between-pid-and-tid/8787888).
> 
> Start a new thread and make sure the thread ID is different.

Oh, I make a test of multithread. Spdlog thinks the main thread ID to be the process ID, and child thread will add 1 to main thread ID. It doesn't use the ID of function `pthread_self()`, but why? Is it because the ID is too long?

**Comment by tt4g** [comment]
As far as the implementation is seen, each OS defines its own way to get the thread ID, and the return value is converted to `size_t`.
`pthread_t()` can't be converted to `size_t` because it may return a `struct`.

https://github.com/gabime/spdlog/blob/de0dbfa3596a18cd70a4619b6a9766847a941276/include/spdlog/details/os-inl.h#L320

**Comment by Githubwyb** [comment]
Thanks for your reply!
Have to say, it's a good log lib, thanks for share.
