### ISSUE TITLE
Couldn't get filename function name and line number to custom sink

### ISSUE THREAD

**Issue by mango009** [gabime/spdlog#1767]
I wrote a sink and could not get spdlog to pass the filename and line number to the sink. 
```
template<typename Mutex>
class my_sink : public spdlog::sinks::base_sink<Mutex> {
protected:
  void sink_it_(const spdlog::details::log_msg& msg) override
  {
    spdlog::memory_buf_t formatted;
    spdlog::sinks::base_sink<Mutex>::formatter_->format(msg, formatted);
    std::cout <<  fmt::to_string(formatted);
  }
};

using my_sink_mt = my_sink<std::mutex>;
using my_sink_st = my_sink<spdlog::details::null_mutex>;
```

And I use it as:
```
 auto mysink = std::make_shared<my_sink_st>();
 auto my_logger = std::make_shared<spdlog::logger>("mlog", mysink);
 spdlog::set_default_logger(my_logger);
 spdlog::set_pattern("[%H:%M:%S %z] %L [%s:%#] %v");

```

But the `msg` struct passed `to sink_it_()` contains no filename, function name, and line# is always 0.

**Comment by tt4g** [comment]
In order to get line number, function name and filename, you have to use a logging macro such as `SPDLOG_TRACE`, `SPDLOG_INFO`, etc.

Look custom format wiki: https://github.com/gabime/spdlog/wiki/3.-Custom-formatting

and macro definetion:

https://github.com/gabime/spdlog/blob/de0dbfa3596a18cd70a4619b6a9766847a941276/include/spdlog/spdlog.h#L241-L249
