### ISSUE TITLE
Refresh a certain line

### ISSUE THREAD

**Issue by Luke-Filewalker** [gabime/spdlog#1803]
Hi, is it possible to refresh a already displayed line. For instance if I want to track a value and don't want to spam my complete output.

Instead of:
Value: x = 2
Value: x = 3
Value: x = 2
Value: x = 2

like:
Value: x = 2 <- only this changes

**Comment by tt4g** [comment]
This can be done by ANSI escape codes.
[ANSI escape code \- Wikipedia](https://en.wikipedia.org/wiki/ANSI_escape_code)

The feature to change colors by ANSI escape codes is available in spdlog, but there is no feature to replace part of the displayed content.
It is better to look for a library that controls the console output rather than a logger library.
