### ISSUE TITLE
Error while building from git repo using cmake

### ISSUE THREAD

**Issue by sayandip18** [gabime/spdlog#1881]
Sorry if this comes off as pretty basic.

 I am trying to clone `spdlog` using cmake in a project. My project consists of a folder called `project` which contains `main.cpp` hosting the main code, `CMakeLists.txt` and a `build` folder. I get the following error while building using `cmake ..` 
```
-- The CXX compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:18 (find_package):
  By not providing "Findspdlog.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "spdlog", but
  CMake did not find one.

  Could not find a package configuration file provided by "spdlog" with any
  of the following names:

    spdlogConfig.cmake
    spdlog-config.cmake

  Add the installation prefix of "spdlog" to CMAKE_PREFIX_PATH or set
  "spdlog_DIR" to a directory containing one of the above files.  If "spdlog"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/sayandip/project/build/CMakeFiles/CMakeOutput.log".
```

The CMakeLists.txt file looks like this
```
cmake_minimum_required(VERSION 3.1)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED True)

set(CMAKE_PREFIX_PATH "/home/sayandip")
include(ExternalProject)
set(SPDLOG_DIR "/home/sayandip")
list(APPEND CMAKE_MODULE_PATH "${SPDLOG_DIR}/cmake")
project(hello-world LANGUAGES CXX)

ExternalProject_Add(spdlog
  GIT_REPOSITORY    https://github.com/gabime/spdlog.git
  GIT_TAG           origin/master
  INSTALL_DIR "${home/sayandip/project}"
  CMAKE_ARGS ${CMAKE_COMMAND} make -j
)

find_package(spdlog)
add_executable(hello-world main.cpp)
include_directories(spdlog)
```

Where am I wrong?

**Comment by tt4g** [comment]
Since `ExternalProject_Add()` does not work the way you think, `FetchContent` is recommended.

Projects added with `ExternalProject_Add()` will be built by running each CMake command in a different process than your project.
Therefore, your project will not be able to get information about the external spdlog project (see this post for more details: https://crascit.com/2015/07/25/cmake-gtest/).
This confused many users, so `FetchContent()` was added.

The project fetched by `FetchContent_Populate()` will be recognized as a part of your project.

Look document `FetchContent`: https://cmake.org/cmake/help/latest/module/FetchContent.html

**Comment by sayandip18** [comment]
Thanks a lot! I managed to get it done finally!
