### ISSUE TITLE
Spdlog crashes on __declspec(naked) functions

### ISSUE THREAD

**Issue by MegaBor** [gabime/spdlog#1904]
Hi!
The following code crashes on msvc:
```cpp
void __declspec(naked) SpdlogBug()
{
    SPDLOG_TRACE("Why would it crash? I think it messed with the stack frame or something.");
}
```

If I use `printf` all working as normal.

**Comment by tt4g** [comment]
I'm not sure about `__declspec(naked)`, but from reading [c \- Could someone explain \_\_declspec\(naked\) please? \- Stack Overflow](https://stackoverflow.com/questions/3021513/could-someone-explain-declspecnaked-please), I think the cause is that the stack frame of the local variable is not set.

I think the reason `printf` doesn't crash is because it is a function that manipulates variable length arguments manually.

**Comment by MegaBor** [comment]
Are there any plans considering this is a bug or giving alternatives? for example maybe preprocessor to enable by the user that disables certain features of spdlog which will allow me to use in naked functions.

**Comment by gabime** [comment]
Not sure what it means to  support such spec. PR is welcome..
