### ISSUE TITLE
spdlog::basic_logger_mt  not output anything when using msvc debugger

### ISSUE THREAD

**Issue by zzwyrmslayer** [gabime/spdlog#1911]
when I using msvc 2017  IDE debugger to startup my program. The Basic file logger  will not generate log file，but I stat the program directly, all things works fine. Why? 

I want the logger working while I use the debugger to debug my program.

![image](https://user-images.githubusercontent.com/20119492/113979074-60f2ff00-9877-11eb-8d47-4c43018326a5.png)

**Comment by tt4g** [comment]
Where do you set "Working Directory" in your Debugging settings of Visual Studio IDE?
https://docs.microsoft.com/en-us/visualstudio/debugger/project-settings-for-a-cpp-debug-configuration?view=vs-2017#configuration-properties-folder-debugging-category

Since the log file path is a relative path, I guess it is output to the Working Directory.

**Comment by zzwyrmslayer** [comment]
you are right. They were in different folders.Now I use direct path instead of relative one.Solved
