### ISSUE TITLE
spdlog crash when use Instruments run profile on macOS Big Sur

### ISSUE THREAD

**Issue by keefo** [gabime/spdlog#1942]
I was able to reproduce the problem in this minimal demo.

[LogTest.zip](https://github.com/gabime/spdlog/files/6481472/LogTest.zip)

1. Run ./setup_conan.sh to setup conan.
2. Open LogTest.xcodeproj compile LogTest.app
3. Then click Xcode "Product" -> "Profile" menu, then start "leak" recording in the Instruments.  The app crash in 2s, and it produces this crash report.

[LogTest_2021-05-14-155417_iMac.crash.zip](https://github.com/gabime/spdlog/files/6481477/LogTest_2021-05-14-155417_iMac.crash.zip)

I am not sure if this is spdlog issue or the instruments issue.

**Comment by tt4g** [comment]
As far as I can see in the crash log, the access to the sink pointer is invalid.
I assume that `spdlog::sinks_init_list sink_list;` is the problem.

This is because, `spdlog::sinks_init_list` is `std::initializer_list` alias.

https://github.com/gabime/spdlog/blob/100f30043f33277122e0991c83845a2617172ffd/include/spdlog/common.h#L101

and `std::initializer_list` does not support copy constructor: https://en.cppreference.com/w/cpp/utility/initializer_list

`sink_list` variable is not guaranteed to copy the internal `std::shared_ptr` correctly, so `logger` may copy `std::shared_ptr` with an invalid pointer.

<details>
<summary>
Try replace `spdlog::sinks_init_list` with `std::vector<spdlog::sink_ptr>`:
</summary>

```diff
+ (void) setFilename:(NSString *)filename console:(BOOL)console level:(BCLoggerLevel) minimumLoglLevel
{
    try
    {
        log_path = filename;

        //spdlog::sinks_init_list sink_list;
        auto file_sink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>(filename.UTF8String, 1024*1024*10, 10);
        auto console_sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
        // name = [filename.lastPathComponent stringByDeletingPathExtension].UTF8String;

-        spdlog::sinks_init_list sink_list;
+        std::vector<spdlog::sink_ptr> sink_list;

        if (console) {
            sink_list = {console_sink, file_sink};
        } else {
            sink_list = {file_sink};
        }

```
</details>

**Comment by keefo** [comment]
Thank you @tt4g 

Indeed, this fixes the crash.

```cpp
std::vector<spdlog::sink_ptr> sink_list;
auto logger = std::make_shared<spdlog::logger>("", sink_list.begin(), sink_list.end());
```
