### ISSUE TITLE
Request of support/documentation: Proper usage with multithread

### ISSUE THREAD

**Issue by susundberg** [gabime/spdlog#1949]
Dear all,

i tried studying the documentation how to properly use the logger with multithreaded application and i was not sure from documentation how it should be properly done.

Below is example that i wrote, that i would, if you maintainers think its proper, like format as pr to be added to examples.

```

#include <cstdio>
#include <list>
#include <thread>

#include "spdlog/spdlog.h"
#include "spdlog/sinks/stdout_sinks.h" 
#include "spdlog/sinks/rotating_file_sink.h"

std::shared_ptr<spdlog::sinks::stdout_sink<spdlog::details::console_mutex> > GLOBAL_console_sink;
std::shared_ptr<spdlog::sinks::rotating_file_sink<std::mutex> > GLOBAL_file_sink;

void thread_function( const std::string& name)
{
    // Create new logger, as we want new combound name
    spdlog::logger logger( name , {GLOBAL_console_sink, GLOBAL_file_sink});

    logger.info("Log '{}' starting up", name );

    for (int loop = 0; loop < 100; loop ++ )
    {
        logger.info("Log {} ping {}", name, loop );
    }
    
    logger.info("Log {} EXIT", name );
}


int main(int, char *[])
{
    GLOBAL_console_sink = std::make_shared<spdlog::sinks::stdout_sink_mt>();
    GLOBAL_console_sink->set_level(spdlog::level::debug);

    GLOBAL_file_sink = std::make_shared<spdlog::sinks::rotating_file_sink_mt>("log.txt", 500, 9 );
    GLOBAL_file_sink->set_level(spdlog::level::debug);

    spdlog::logger logger("main", {GLOBAL_console_sink, GLOBAL_file_sink});
    logger.set_level(spdlog::level::debug);
    
    logger.info("OK - starting threads!");

    std::list<std::string> thread_names{"first","second","foo","bar","what","else"};
    std::list<std::thread> thread_objs;

    for ( const auto& name : thread_names )
    {
        logger.info("Creating '{}'", name );
        thread_objs.push_back( std::thread(&thread_function, name) );
    }

    logger.info("Threads created!");

    for ( auto& th : thread_objs )
    {
        th.join();
    }

    logger.info("Threads joined, bye!");

}



```

**Comment by tt4g** [comment]
IMO.
`std::shared_ptr` should not be a global variable. This is because we don't know when the pointer will be released.
In most cases, it is enough to prepare a factory class that creates `spdlog::logger` and manage sink.

**Comment by susundberg** [comment]
This is good point and shall fix. 

But the main question would be - do you think i should see the effort - i mean do you see the need for the example with threads?

**Comment by tt4g** [comment]
This is my opinion too.

I believe that there is no one best way to do this, as the requirements for multi-threading vary from application to application.

If an application uses only one logger, even if it is multi-threaded, just initialize `spdlog::default_logger()` first.

However, an application that repeatedly creates and deletes loggers is not simple.
Let's take an example of an HTTP server that requires a dedicated logger for each request.
When an HTTP request is received, a context and a logger are generated.
Since the request is operated in a multi-threaded fashion, the context and logger must be managed in the same lifecycle.
And don't forget to delete the logger when the response is completed.
The best way to manage this logger depends on the implementation of the application, because there is more than one way to exchange variables in a multi-threaded environment without causing data races.

It is also possible to register a logger with `spdlog::register_logger` and get the logger in each thread with `spdlog::get`.
But think about it, if we can transfer the name of the logger for each request to each thread, then we should be able to transfer the logger directly to the thread.

The data (variable) exchange design of multithreaded applications should be the way to exchange `spdlog::logger` in multithreading as it is.

**Comment by susundberg** [comment]
Thanks for the comments and your your time.

In my case i ended up following construct:
 - Wrapped the spdlog inside "Log" class that is initialed with `std::string module_log_name` - bit similar to python3 getLogger(<name>)
 - Then threads do logging via this file specific `static Log LOG("my_module1)` - object that maintains the actual `spdlog::logger* handle` (usage then in that file goes `LOG.info("hello there!")` - and log gets entry ` [my_module1] [info] hello there`
 - Before starting the threads/logging there is initialization that creates sinks (rotate file + stdout) - based on some configuration how user wants logs to be created.
