### ISSUE TITLE
Error on g++ with c++17

### ISSUE THREAD

**Issue by elwolf6** [gabime/spdlog#1952]
`g++ -Wall -Wfatal-errors -std=c++17 -I"./libs/" ./src/*.cpp ./src/Game/*.cpp ./src/ECS/*.cpp -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer -llua5.3 -lspdlog -o elwolfengine
In file included from /usr/include/spdlog/common.h:36,
                 from /usr/include/spdlog/spdlog.h:12,
                 from ./src/Game/Game.cpp:2:
/usr/include/spdlog/fmt/fmt.h:22:10: fatal error: spdlog/fmt/bundled/core.h: No such file or directory
   22 | #include <spdlog/fmt/bundled/core.h>
      |          ^~~~~`

That is the output from my makefile while using spdlog i'm on arch it installed correctly 

here's my makefile https://en0.sh/86f9a29728be99b8.makefile

**Comment by tt4g** [comment]
It looks like the header directory of spdlog is not added correctly to the header search path, since it is reported that the header file is not found.

Also, if using the pre-built spdlog (not the header library), then the `SPDLOG_COMPILED_LIB` macro must also be defined in g++ optioins (`-DSPDLOG_COMPILED_LIB`).

**Comment by elwolf6** [comment]
i just installed spdlog from the AUR if I try adding `-DSPDLOG_COMPILED_LIB` to my g++ flags i get the same output

**Comment by tt4g** [comment]
Does `spdlog/fmt/bundled/core.h` exist? Please add the `-I` option if you have not added a setting that allows the relevant file to be included from the header include path.

**Comment by elwolf6** [comment]
usr/includespdlog/fmt/bundled doesn't exist

**Comment by tt4g** [comment]
I don't know how you installed spdlog, but if you defined the CMake variable `SPDLOG_FMT_EXTERNAL=ON` at build time, the fmt bundled with spdlog will not be installed.
At this time, spdlog is built using an external fmt, so the `SPDLOG_FMT_EXTERNAL` macro must be defined in order to use spdlog.
If this macro is not defined, spdlog will try to include the bundled fmt.

**Comment by elwolf6** [comment]
is this an issue with the AUR package then bc I didn't build spdlog myself i installed from the AUR

**Comment by tt4g** [comment]
Unfortunately, the AUR package is not maintained in this repository.
It is recommended that you ask the AUR package provider.

**Comment by elwolf6** [comment]
yep built spdlog myself and had no issue
