### ISSUE TITLE
Why not use lock free mpsc queue for the case when async log use single thread?

### ISSUE THREAD

**Issue by MBkkt** [gabime/spdlog#1973]
https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/details/thread_pool.h#L86
Why not use lock free mpsc queue for the case when thread 1?
This seems to have an impact on performance. At the same time, it doesn't require some kind of great complication.
Again, as I understand it, 1 thread is the default option. That is, such an improvement (if it improves of course) will have an impact on many users.

**Comment by gabime** [comment]
spdlog used in the past lockfree mpmc queue. It was replaced because I couldnt find a satisfactory way to avoid spinning when the is empty/full. If there is some solution for this I would be happy to use it. see also https://github.com/gabime/spdlog/issues/325 and https://github.com/gabime/spdlog/issues/325

**Comment by MBkkt** [comment]
Thanks for the answer. Are the links correct? You are referencing 325 twice

**Comment by MBkkt** [comment]
@gabime About problem with wait, are you trying semaphore (signal after add, wait before pop)?
This option will not be able to futex_wait for producer, if the queue is full. But is it really necessary?

**Comment by gabime** [comment]
Tried it once. ,Couldn't make it work correctly under high load.

**Comment by shuhaowu** [comment]
Is it possible to make it so that the queue can be chosen via template parameters? This would even potentially allow user-implemented queue. The reason to use a lockless queue could be in some situations where locks cannot be used. For example, in real-time/high-performance context where maximum latency _must_ be below a certain amount, and mutexes can cause [priority inversion problems](https://en.wikipedia.org/wiki/Priority_inversion) which can result in unbounded latency. This means a lockless queue must be used despite higher CPU usage. Usually in these contexts the queue will be a non-blocking one where when the queue is full, the older messages are dropped.
