### ISSUE TITLE
spdlog lost some log, it's weird...

### ISSUE THREAD

**Issue by zxdposter** [gabime/spdlog#2074]
```c
spdlog::logger init_log() {
    std::vector<spdlog::sink_ptr> sinks;
    sinks.push_back(std::make_shared<spdlog::sinks::ansicolor_stdout_sink_mt>());
    sinks.push_back(
            std::make_shared<spdlog::sinks::rotating_file_sink_mt>(LOGGER_FILE, LOGGER_MAX_SIZE, LOGGER_MAX_FILES));



    static spdlog::logger logger = spdlog::logger("301", std::begin(sinks), std::end(sinks));

    logger.set_level(static_cast<level::level_enum>(LOGGER_LEVEL));

    logger.info("set log info, max size {}, max files {}, level {}, file path {}", LOGGER_MAX_SIZE,
                LOGGER_MAX_FILES, LOGGER_LEVEL, LOGGER_FILE);

    return logger;
}
```

this is my log file:
![image](https://user-images.githubusercontent.com/13846260/131061761-ef59d35e-ccf5-45b3-a54d-d2d4b98176cb.png)

this is my console output:
![image](https://user-images.githubusercontent.com/13846260/131061797-f73ad311-dac1-4d59-b915-af49a4f4b498.png)

always lost log in red frame, but normal for the subsequent log.

I also have try start two thread log increase int on every 10ms, not lost.

Why I have this situation?

**Comment by zxdposter** [comment]
@tt4g seem flush is working, why not flush immediately in every log?

**Comment by zxdposter** [comment]
@tt4g I used `flush_on(level::debug);` is working now..

**Comment by tt4g** [comment]
spdlog calls `std::fwrite()` when it writes a file.
`std::fwrite()` writes the buffer to the stream, but there is no guarantee that the data in the buffer will be written to disk unless `std::fflush()` is called.

**Comment by zxdposter** [comment]
header only way, whether to support asynchronous writes?

**Comment by tt4g** [comment]
Do you mean Asynchronous I/O? Asynchronous I/O is not supported.

`spdlog::flush_every();` is provided as a way to perform periodic flush operations in a dedicated thread.
Wiki: https://github.com/gabime/spdlog/wiki/7.-Flush-policy

However, periodic flushes will only flush loggers that are registered in the spdlog global registry.
The snippet will not work because the logger is not registered in the global registry.
To register a logger in the global registry, call `spdlog::register_logger()`.

**Comment by zxdposter** [comment]
ok thanks a lot!
