### ISSUE TITLE
windows7, vs2013: ~async_log_helper() hang when exit application

### ISSUE THREAD

**Issue by alek314** [gabime/spdlog#213]
`~async_log_helper()
{
    _worker_thread.join(); //hang here
}`

looks like it's a windows issue. 
call spdlog::drop_all() before main() exit to ensure all worker thread is killed and every thing is OK.
[http://stackoverflow.com/questions/10915233/stdthreadjoin-hangs-if-called-after-main-exits-when-using-vs2012-rc](url)

**Comment by DevCybran** [comment]
Having the same issue on the same platform.

This is caused by a bug in VS2012/2013, where thread joining causes a deadlock when executed after the main() function exits (http://stackoverflow.com/questions/10915233/stdthreadjoin-hangs-if-called-after-main-exits-when-using-vs2012-rc - hope my link works ;) )

There is not much spdlog can do to avoid this. Calling spdlog::drop_all() only works if your loggers are part of the registry. If the loggers are (as in my case) created by a static initializer, you have to find another workaround.

**Comment by alek314** [comment]
windows issues and workaround is added to the wiki

**Comment by sbwtw** [comment]
@alek314 hello, can't find workaround solution on wiki, can you give some tips here?
