### ISSUE TITLE
how to log before coredump

### ISSUE THREAD

**Issue by f1msch** [gabime/spdlog#2166]
Is there any method to flush every log before my programe coredump? I use flush_every(seconds(1)) now but the time granularity seems too large that it cannot provider enough logs to me.
Even more could it log any more backtrace at coredump time, it seems more useful than only use "gdb coredump"

**Comment by tt4g** [comment]
It will not be possible to flush the logs before the core dump.
Because core dump is caused by an abnormal termination of the program.

Consider that it is impossible to rescue the log from a process with abnormal behavior.

It is always better to flush the log with a process that is running normally.
If you want to always flush the log, call `spdlog::flush_on(spdlog::level::trace)` or `spdlog::logger::flush_on(spdlog::level::trace)`.

**Comment by f1msch** [comment]
It will be nice,I will try it
