### ISSUE TITLE
Another wstring wchar_t issue

### ISSUE THREAD

**Issue by erichlf** [gabime/spdlog#2243]
I am getting the following error:
```
/home/seegrid.local/efoster/workspace/hemiola/build/external/spdlog/include/spdlog/spdlog.h:149:13: note: candidate: ‘void spdlog::debug(fmt::v8::format_string<T ...>, Args&& ...) [with Args = {std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&}; fmt::v8::format_string<T ...> = fmt::v8::basic_format_string<char, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&>]’
  149 | inline void debug(fmt::format_string<Args...> fmt, Args &&... args)
      |             ^~~~~
/home/seegrid.local/efoster/workspace/hemiola/build/external/spdlog/include/spdlog/spdlog.h:149:47: note:   no known conversion for argument 1 from ‘const wchar_t [36]’ to ‘fmt::v8::format_string<std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&>’ {aka ‘fmt::v8::basic_format_string<char, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&>’}
  149 | inline void debug(fmt::format_string<Args...> fmt, Args &&... args)
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
/home/seegrid.local/efoster/workspace/hemiola/build/external/spdlog/include/spdlog/spdlog.h:247:13: note: candidate: ‘template<class T> void spdlog::debug(const T&)’
  247 | inline void debug(const T &msg)
```
The code is pretty simple:
```c++
// these includes are for a ftm::join
#include <fmt/ranges.h>
#include <fmt/xchar.h>
...
void lookup ( std::wstring letters ) {
    spdlog::debug (
              L"Found the following anagrams for {}",
              letters );
}
```

I have read that there was a flag, but:
```
/home/seegrid.local/efoster/workspace/hemiola/build/external/spdlog/include/spdlog/common.h:132:10: error: #error SPDLOG_WCHAR_TO_UTF8_SUPPORT only supported on windows
  132 | #        error SPDLOG_WCHAR_TO_UTF8_SUPPORT only supported on windows
```

I saw someone else post pretty much the exact same thing, but they closed their ticket without a resolution: https://github.com/gabime/spdlog/issues/1870

**Comment by erichlf** [comment]
I have also tried `SPDLOG_WCHAR_FILENAMES`

**Comment by erichlf** [comment]
I do have `#define SPDLOG_FMT_EXTERNAL`.

**Comment by tt4g** [comment]
As the error message says, spdlog does not provide `wchar_t` support for non-Windows platforms.

https://github.com/gabime/spdlog/blob/eb3220622e73a4889eee355ffa37972b3cac3df5/include/spdlog/logger.h#L21-L26

**Comment by erichlf** [comment]
The question is why? And how much work would it be to make it work? Cause I might be willing to do the work.

**Comment by tt4g** [comment]
Since spdlog handles characters as `char` internally, so it is necessary to convert `wchar_t` to `char`.
However, the C/C++ language specification does not specify the character encoding for `wchar_t` (it is platform-dependent).

The Win API expects `wchar_t` to be UTF-16 encoding, which is the de facto standard.
And it is supported by spdlog because it provides a Win API for interconversion between UTF-16 (`wchar_t`) and UTF-8 (`char`).

The character encoding expected for `wchar_t` is unknown on platforms other than Windows.
These platforms cannot support `wchar_t` because they don't know what character encoding it expects.

**Comment by erichlf** [comment]
So if I used a `std::u32string` I would be good?

**Comment by tt4g** [comment]
spdlog does not support neither `char16_t` nor `char32_t`. It is the user's responsibility to convert them to `char`.
Because, as far as the C++ standard specification is concerned, `char16_t` is a type whose size is large enough to store UTF-16, and `char32_t` is a type whose size is large enough to store UTF-32.
In other words, it can store data that is not UTF-16 or UTF-32.

See: https://en.cppreference.com/w/cpp/language/types#char32_t

Since there is no guarantee for the character data stored in the type, spdlog will not automatically convert it.
Developers should convert the character data to `char` at their own risk before passing the character data to spdlog.
Only `wchar_t` on Windows platforms is exceptionally supported since it has a de facto standard.
