### ISSUE TITLE
fmtlib function already defined

### ISSUE THREAD

**Issue by EliSauder** [gabime/spdlog#2250]
I am using cmake as a my build system and making sure to `add_definitions(-DSPDLOG_FMT_EXTERNAL)` (I have also tried with =ON) to the CMakeLists.txt to use the external fmtlib, however I am receiving the below error when trying to use the fmt::vformat function.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2005	"void __cdecl fmt::v8::detail::throw_format_error(char const *)" (?throw_format_error@detail@v8@fmt@@YAXPEBD@Z) already defined in fmtd.lib(format.cc.obj)	C:\Users\elija\source\repos\Mythos\out\build\x64-Debug\Mythos	C:\Users\elija\source\repos\Mythos\out\build\x64-Debug\Mythos\spdlogd.lib(spdlog.cpp.obj)	1	
```

**Comment by tt4g** [comment]
The cause is not clear from the information provided.
However, I can see that there is some problem with your CMake project.

First, `add_definitions()` (depracted) will only add macro definitions to CMake targets that are added in the CMake current directory.

See: https://cmake.org/cmake/help/v3.22/command/add_definitions.html

> Adds definitions to the compiler command line for targets in the current directory, whether added before or after this command is invoked, and for the ones in sub-directories added after. This command can be used to add any flags, but it is intended to add preprocessor definitions.

That is, it will not work if you have installed spdlog or added a subdirectory spdlog to your project with `add_subdirectory()`.

If you have `spdlog` installed, use `find_pacakge(spdlog REQUIRED) ` to find the CMake target `spdlog::spdlog` (or `spdlog::spdlog_header_only` if you use header-only library) and then use `target_link_libraries(${YOUR_TARGET} PUBLIC spdlog ::spdlog)`, you need to tell CMake that your library (or application) uses spdlog.

<details>
<summary>installed spdlog example</summary>

```cpp
cmake_minimum_required(VERSION 3.12.0)
project(example VERSION 0.1.0)

find_package(spdlog REQUIRED)

add_executable(my_app main.cpp)
target_link_libraries(my_app PUBLIC spdlog::spdlog)
```
</details>

If you are using `add_subdirectory` to get spdlog into your project, just set the CMake variable `SPDLOG_FMT_EXTERNAL` (or `SPDLOG_FMT_EXTERNAL_HO` if you are using header-only) to `ON`.

<details>
<summary>add_subdirectory example</summary>

```cpp
cmake_minimum_required(VERSION 3.12.0)
project(example VERSION 0.1.0)

set(SPDLOG_FMT_EXTERNAL ON)
set(SPDLOG_FMT_EXTERNAL_HO ON)

add_subdirectory(thirdparty/spdlog)

add_executable(my_app main.cpp)
target_link_libraries(my_app PUBLIC spdlog::spdlog)
```
</details>

**Comment by EliSauder** [comment]
Hello, I'm more than happen to provide information, though I'm not sure what all you would need.

I use add sub directory in the root of my project and I updated my cmake, adding the libraries looks like this now:

```cmake
target_link_libraries(Mythos PUBLIC fmt::fmt)
target_include_directories(Mythos PUBLIC ${PROJECT_SOURCE_DIR}/Mythos/external/fmt/include)

set(SPDLOG_FMT_EXTERNAL ON)

target_link_libraries(Mythos PRIVATE spdlog::spdlog)
target_include_directories(Mythos PRIVATE ${PROJECT_SOURCE_DIR}/Mythos/external/spdlog/include)

```

**Comment by tt4g** [comment]
You need to define `SPDLOG_FMT_EXTERNAL=ON` before `add_subdirectory(/path/to/spdlog)`.

**Comment by EliSauder** [comment]
Gotcha, that did resolve the issue. It was just due to my unfamiliarity with cmake. Thank you.
