### ISSUE TITLE
Issue when using spdlog in any configuration with VS2022

### ISSUE THREAD

**Issue by skuyuy** [gabime/spdlog#2283]
I am trying to incorporate spdlog (v1.x) in some software i am writing. For that, i am using the header-only version since i wanted to try to avoid building all my dependencies manually, and it used to work with C++20 on VS2022, but ever since i did some restructuring to my code (mainly namespaces and filenames) i am running into a very weird error with the system <thread> header in every file spdlog is included in. 
Maybe worth knowing: im using premake to build my solution and added spdlog/include as an additional include directory there, but again, until recently this did not cause any issues...

I already tried linking to the static library version as well, without success. if you need any more info i would be happy to provide :) thanks in advance

```
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\thread(76,43): error C2039: '_beginthreadex': is not a member of '`global namespace''
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\thread(89): message : see reference to function template instantiation 'void std::thread::_Start<_Ty,>(_Fn &&)' being compiled
1>        with
1>        [
1>            _Ty=spdlog::details::periodic_worker::{ctor}::<lambda_1>,
1>            _Fn=spdlog::details::periodic_worker::{ctor}::<lambda_1>
1>        ]
1>B:\Files\Dev\Git\clap-query\spdlog\include\spdlog\details\periodic_worker-inl.h(30): message : see reference to function template instantiation 'std::thread::thread<spdlog::details::periodic_worker::{ctor}::<lambda_1>,,0>(_Fn &&)' being compiled
1>        with
1>        [
1>            _Fn=spdlog::details::periodic_worker::{ctor}::<lambda_1>
1>        ]
1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\thread(66,5): error C3861: '_beginthreadex': identifier not found
```

**Comment by tt4g** [comment]
Probably the same problem as the following link:

* [Solution for C\+\+ error c2039 is not a member of global namespace \- CodeProject](https://www.codeproject.com/Questions/1178046/Solution-for-Cplusplus-error-c-is-not-a-member-of)
* [c\+\+ \- error C3861: '\_beginthreadex': identifier not found \- Stack Overflow](https://stackoverflow.com/questions/27230258/error-c3861-beginthreadex-identifier-not-found)

Perhaps there is a header file with the same name as the system header in which `_beginthreadex` is defined.
Configure your project so that system headers are searched first.

**Comment by skuyuy** [comment]
will try that, ill give you an update if it worked

**Comment by skuyuy** [comment]
Update: caused by a "process.h" header file in another dependency, which i naively included without preceding directory. Thanks! :)
