### ISSUE TITLE
Forked Process - Child can't log

### ISSUE THREAD

**Issue by twarg1** [gabime/spdlog#2309]
Child process can't log after process fork.

Example C++ Code:

#include < spdlog/async.h >
#include < spdlog/spdlog.h >
#include < spdlog/sinks/stdout_color_sinks.h >
#include < spdlog/details/thread_pool.h >
#include < iostream >  // include iostream
#include < unistd.h >   // for fork
#include < sys/wait.h > // for wait

void forkTest ()
{
  try {
      pid_t pid = fork();
      if (pid == -1) {
        perror("Problem forking");
      }
      else if (pid > 0) {
       // PARENT PROCESS
        std::cout << "PARENT HERE!" << std::endl << std::flush;
        auto logger = spdlog::get("system");
        logger->info ( "SPDLOG is still here in the Parent" );
        logger->flush();
        std::cout << "PARENT LOGGED" << std::endl << std::flush;
        int status;
        waitpid (pid, &status, 0);
        std::cout << "PARENT got Child Termination Status (" << status << ")" << std::endl << std::flush;
      }
      else {
       // CHILD PROCESS
        std::cout << "CHILD HERE!" << std::endl << std::flush;
        auto logger = spdlog::get("system");
        for (int i=0; i<200; i++)
        {
            **_logger->info ( "SPDLOG is still here in the Child" );_**
            logger->flush();
        }
        spdlog::details::registry::instance().flush_all();
        std::cout << "CHILD LOGGED" << std::endl << std::flush;
        std::fflush( nullptr );
        exit(0);
      }
  }
  catch ( spdlog::spdlog_ex& spde ) {
      std::cout << "SPDLOG EXCEPTION:  (" << spde.what() << ")" << std::endl << std::flush;
  }
  catch ( const std::exception& e ) {
      std::cout << "STD EXCEPTION:  (" << e.what() << ")" << std::endl << std::flush;
  }
  catch (...) {
      std::cout << "UNKNOWN EXCEPTION" << std::endl << std::flush;
  }
}

int main( int argc, char** argv )
{
    auto sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
    sink->set_level( spdlog::level::trace );
    auto tp = std::make_shared<spdlog::details::thread_pool>( 512, 2 );
    auto logger = std::make_shared<spdlog::async_logger>( "system", sink, tp, spdlog::async_overflow_policy::block );
    logger->set_level( spdlog::level::trace );
    spdlog::register_logger( logger );
    spdlog::set_default_logger( logger );

    std::cout << "start fork test..." << std::endl << std::flush;
    forkTest();
    std::cout << "fork test back" << std::endl << std::flush;
    spdlog::details::registry::instance().flush_all();
    std::fflush( nullptr );
    spdlog::shutdown();
}

PROBLEM/ISSUE: After the process has been forked, the parent can log using the logger constructed in main(), but the child can not.
Is Spdlog supposed to be fork-safe?

IMPORTANT NOTE: if a **synchronous** logger is created instead ... program runs fine!

**Comment by twarg1** [comment]
Additional Information ...   if you add a loop in the child code section to log say 200 messages instead of one.  Add decrease the size of the thread pool from 512 to 128 ... you can hang the child process.   Appears some issue with flushing the sink?

**Comment by tt4g** [comment]
After `fork()`, the child process does not share STDOUT and STDERR with the parent process.
If you want to log to STDOUT of the parent process, connect (pipe) STDOUT of the child process to STDOUT of the parent process.

**Comment by twarg1** [comment]
Thanks for the quick reply!   All the std::cout lines print without issue.   The only line that does not output is the logger->info line in the child process.   Perhaps I'm misunderstanding your point ... how should I update the code above?

**Comment by tt4g** [comment]
I apologize I did not understand your code correctly.
Please disregard my previous comment as it is erroneous.

And when providing code, it is recommended that Markdown code formatting be enabled to ensure that the code is not broken.

Example:

`````
```cpp

#include <spdlog/async.h>
#include <spdlog/spdlog.h>
#include <spdlog/sinks/stdout_color_sinks.h>
#include <spdlog/details/thread_pool.h>
#include // include iostream
#include <unistd.h> // for fork
#include <sys/wait.h> // for wait

void forkTest ()
{
    ....
}

int main( int argc, char** argv )
{
    ...
}
```
```

**Comment by tt4g** [comment]
About the issue of child processes not being logged, it is probably due to the fact that the custom `spdlog::details::thread_pool` and `logger` are created in the same scope.

Async logger uses `spdlog::details::thread_pool` created inside spdlog if you do not use your own `spdlog::details::thread_pool`.

https://github.com/gabime/spdlog/blob/eb3220622e73a4889eee355ffa37972b3cac3df5/include/spdlog/details/registry-inl.h#L236-L257

The async logger is designed to write all logs through the thread_pool by calling `std::weak_ptr<spdlog::details::thread_pool>::lock()` in the destructor.

https://github.com/gabime/spdlog/blob/eb3220622e73a4889eee355ffa37972b3cac3df5/include/spdlog/async_logger-inl.h#L27-L37

On the other hand, since you have created the thread_pool and logger within `main()`, the deleting is done in the order of thread_pool, logger.
Therefore, `std::weak_ptr<spdlog::details::thread_pool>::lock()` is expected to fail in the destructor of logger

Try calling `logger.reset()` before `spdlog::shutdown();`.

```diff
 int main( int argc, char** argv )
 {
     auto sink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
     sink->set_level( spdlog::level::trace );
     auto tp = std::make_shared<spdlog::details::thread_pool>( 512, 2 );
     auto logger = std::make_shared<spdlog::async_logger>( "system", sink, tp, spdlog::async_overflow_policy::block );
     logger->set_level( spdlog::level::trace );
     spdlog::register_logger( logger );
     spdlog::set_default_logger( logger );

     std::cout << "start fork test..." << std::endl << std::flush;
     forkTest();
     std::cout << "fork test back" << std::endl << std::flush;
     spdlog::details::registry::instance().flush_all();
     std::fflush( nullptr );
+    logger.reset();
     spdlog::shutdown();
 }
```

**Comment by twarg1** [comment]
Thank you!    Added the "logger.reset() line as instructed.  Does not appear to impact the result.   Sorry about the formatting ... what I paste in is not being preserved on saving the comment.  Example:   can't add the line to include the C++ header iostream.
#include <iostream>

**Comment by tt4g** [comment]
I have tried running your source code but could not determine the cause.
I am not familiar with `fork()` so I am sure I am missing something.
If I have time, I will continue to investigate, but I don't know when that will be.

If you don't mind, use a sync logger. It is faster than async logger (#1391, #2282).

**Comment by tt4g** [comment]
I browsed the following URL to find out about `fork()`.

- https://man7.org/linux/man-pages/man2/fork.2.html
- https://thorstenball.com/blog/2014/10/13/why-threads-cant-fork/
- https://www.evanjones.ca/fork-is-dangerous.html
- https://stackoverflow.com/questions/6078712/is-it-safe-to-fork-from-within-a-thread/6079669
- https://stackoverflow.com/questions/39890363/what-happens-when-a-thread-forks
- https://unix.stackexchange.com/questions/155017/does-fork-immediately-copy-the-entire-process-heap-in-linux

From the above URL link I deduced the cause of this issue (my knowledge of `fork()` and threads is based on the URL link. It may contain incorrect information as I have not actually investigated on my machine).

First, after `fork()`, the child process copies the memory of the parent process, which also copies the file descriptors and mutex state (memory copying is done with a copy-on-write strategy). but  threads are not copied. The running process in the parent process is copied to the child process, but is stopped.
Thus, only threads in the thread pool are available for the parent process.

And thread pool then manages log messages with queue. Since queue is implemented in `std::vector`, when a log message is added, the child process is copied memory due to the limitation of `fork()`, and the queues of the parent and child process are completely separated.

The log messages of the child process are added to queue, but all the threads in the thread pool that pull log messages from queue are stopped.

(If I am not mistaken so far) this explains why log messages of child processes are not printed by the async logger.
Since spdlog uses threads (such as `spdlog::details::thread_pool` and `spdlog::details::periodic_worker`), it is not considered fork-safe if used before `fork()`.

The workaround is to set up spdlog in both the parent and child process after `fork()`.

**Comment by twarg1** [comment]
understood.   thank you for looking into this one.

**Comment by voidvelocity** [comment]
Is spdlog support multiprocessing now? It's seems doesn't work now. My code:

```
#include <iostream>
#include <spdlog/spdlog.h>
#include <spdlog/async.h>
#include <spdlog/sinks/basic_file_sink.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>

void init_logger(const std::string& log_file) {
    auto async_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>(log_file, true);

    auto logger = std::make_shared<spdlog::async_logger>(
        "logger", async_sink, spdlog::thread_pool(), spdlog::async_overflow_policy::block);
    
    spdlog::set_pattern("[%Y-%m-%d %H:%M:%S.%e] [%t] [%l] %v");
    spdlog::set_default_logger(logger);
    spdlog::info("Logger initialized in process {}", getpid());
}

int main() {
    spdlog::init_thread_pool(8192, 1);
    init_logger("log_main.txt");

    spdlog::info("Main process started, PID={}", getpid());

    for (int i = 0; i < 2; ++i) {
        pid_t pid = fork();
        if (pid == 0) { 
            spdlog::shutdown(); 

            spdlog::init_thread_pool(8192, 1);
            init_logger("log_child_" + std::to_string(getpid()) + ".txt");

            spdlog::info("Child process started, PID={}", getpid());
            for (int j = 0; j < 5; ++j) {
                spdlog::info("Child process PID={} logging iteration {}", getpid(), j);
            }

            _exit(0);
        } else if (pid < 0) {
            spdlog::error("Fork failed");
            return 1;
        }
    }

    while (wait(nullptr) > 0); 
    spdlog::info("Main process finished");

    return 0;
}
```

my compile command:

```
g++ main.cpp -std=c++17 -I /<spdlog>/include
```

**Comment by tt4g** [comment]
@ligengli It does not work because spdlog is used before `fork()`.

See: https://github.com/gabime/spdlog/issues/3337#issuecomment-2641040489

> Do not set up spdlog in the parent process before `fork()`. After `fork()`, resources created with C++ `std::thread` and `std::mutex` will not work properly.
> 
> See:
> 
> * https://stackoverflow.com/questions/39890363/what-happens-when-a-thread-forks
> * https://stackoverflow.com/questions/6078712/is-it-safe-to-fork-from-within-a-thread/6079669#6079669

See also: https://github.com/gabime/spdlog/issues/2309#issuecomment-1068708569
