### ISSUE TITLE
Compiling spdlog with /clr , Common Language Runtime ( C++ CLI )

### ISSUE THREAD

**Issue by beemibrahim** [gabime/spdlog#2368]
I can't find a logging library for C++ /CLI , spdlog works very well with C++ , How to integrate it with C++ CLI

**Comment by tt4g** [comment]
spdlog requires c++11 features.
`std::mutex` is required because it is heavily used internally.

**Comment by beemibrahim** [comment]
Thats not the answer I'm looking for

**Comment by USAFrenzy** [comment]
To be fair, tt4g did give some insight on what you can do here; the functionality you're requesting is out of spdlog's scope of being a C++11 library, so rolling your own mutex alternative and replacing spdlog's usage of mutex for that alternative should allow you to have a compatible cli version of spdlog. One option might be using System::Threading::Monitor or to go along with the manual route, you could check out the answer to  [this](https://stackoverflow.com/questions/45224526/what-is-the-alternative-to-futures-and-promises-in-managed-c/49845900#49845900) stack overflow answer. Either way, best of luck in your endeavor and I hope this was able to help!

**Comment by tt4g** [comment]
Another workaround seems to be to use forward declaration techniques to hide features that C++/CLI cannot use.
Stack Overflow: https://stackoverflow.com/questions/15188937/using-clr-and-stdthread?noredirect=1&lq=1

Create a wrapper library for spdlog so that features that C++/CLI cannot use do not appear in the header.
And use spdlog through the wrapper library.

**Comment by beemibrahim** [comment]
Fine
