### ISSUE TITLE
undefined reference to spdlog::cfg::helpers::load_levels

### ISSUE THREAD

**Issue by gianmarcoodorizzi** [gabime/spdlog#2401]
Hello,
if I try to compile the example **Load log levels from env variable or from argv** I get:

`build/src/main.o: In function spdlog::cfg::load_env_levels()':
main.cpp:(.text._ZN6spdlog3cfg15load_env_levelsEv[_ZN6spdlog3cfg15load_env_levelsEv]+0x2e): undefined reference to spdlog::cfg::helpers::load_levels(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status`

Is there something I am doing wrong? Thank you!

**Comment by tt4g** [comment]
I don't know exactly what the cause is since no compiler information is provided, but from my experience it appears to be a standard library compatibility issue with the GCC compiler (I expect that you are linking the built spdlog library since it is reporting the link error).
If so, please check the gcc (`g++`) library for compatibility.

See also:
- https://github.com/gabime/spdlog/wiki/0.-FAQ#gcc-standard-library-compatibility-problem
- https://stackoverflow.com/questions/71273433/producing-a-library-with-a-recent-gcc-and-consuming-it-with-an-older-gcc-why-a
- https://stackoverflow.com/questions/49242829/gcc-not-linking-against-libstdc

**Comment by gianmarcoodorizzi** [comment]
Thank you for your prompt response.
This is the build/link command:

`Building file: src/main.cpp
arm-fslc-linux-gnueabi-g++  -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard --sysroot=/opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi  -DSPDLOG_COMPILED_LIB       -Wall -Wextra -pedantic-errors -Wno-psabi -std=c++17 -Isrc -I../common -I../common/include  -O2 -pipe -g -feliminate-unused-debug-types      -c "src/main.cpp" -MMD -MP -MF"build/src/main.d" -MT"build/src/main.o" -o "build/src/main.o"
src/main.cpp: In function ‘int main(int, char**)’:
src/main.cpp:2:15: warning: unused parameter ‘argc’ [-Wunused-parameter]
 int main (int argc, char *argv[])
               ^~~~
src/main.cpp:2:32: warning: unused parameter ‘argv’ [-Wunused-parameter]
 int main (int argc, char *argv[])
                                ^
Building target: project
arm-fslc-linux-gnueabi-g++  -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard --sysroot=/opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi   -O2 -pipe -g -feliminate-unused-debug-types        -Wl,--build-id=none -Lsrc/modbus/lib   -o "project" build/src/main.o [...] -lpthread -lm -lzmq -lmodbus
build/src/main.o: In function spdlog::cfg::load_env_levels()':
/home/user/git/cs/project/src/spdlog/cfg/env.h:33: undefined reference to spdlog::cfg::helpers::load_levels(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
make: *** [Makefile:112: project] Error 1`

gcc version 7.2.0.

I am not sure how to go about this from here.

P.S.: I am building spdlog from source.

**Comment by tt4g** [comment]
Are you saying that you have already built spdlog? If so, `spdlog.so` is not linked. A link option `-lspdlog` must be added.

If the spdlog library is not in the standard library path, you must also add a path for the linker to find the library with the `-L` option. If the spdlog library is in `/path/to/spdlog/library` directory, add the `-L/path/to/spdlog/library` option.

**Comment by gianmarcoodorizzi** [comment]
No, what I am saying is that I am building spdlog from source (it is part of my codebase) and I am not building a static nor dynamic library. I am able to use your library, I am not able to build the simple example you provided in the README: _Load log levels from env variable or from argv
_

**Comment by tt4g** [comment]
Linking errors occur when there is no corresponding function or when application binary compatibility has been broken. However, a stand-alone project would not normally encounter this error.

This is the case, I cannot offer any more hints that would solve the issue.
It may be due to the fact that spdlog has been imported into your project, but I do not have any information about that project. Therefore, I cannot provide any further hints on how to solve the issue.

The only possibilities are that the spdlog source code is missing or that the spdlog source has not been added to the include path.

EDIT: There is another possibility. You may have an older version of spdlog installed on your machine that is loading its header files.

**Comment by gianmarcoodorizzi** [comment]
Thank you for this, I will update this if I figure out what is wrong.

**Comment by PetropoulakisPanagiotis** [comment]
```
# Download fmt v9.1.0
cd /tmp
git clone https://github.com/fmtlib/fmt.git
cd fmt
git checkout 9.1.0

# Build and install
mkdir build && cd build
cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON ..
make -j$(nproc)
sudo make install

# Update the library cache
sudo ldconfig
```
```

# Install spdlog from source with fmt v9
git clone https://github.com/gabime/spdlog.git
cd spdlog
git checkout v1.12.0  # or latest stable

mkdir build && cd build
cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
      -DSPDLOG_FMT_EXTERNAL=ON \
      -DCMAKE_BUILD_TYPE=Release \
      ..
make -j$(nproc)
sudo make install
sudo ldconfig

```

ldconfig -p | grep fmt

This might help
