### ISSUE TITLE
test_stopwatch2 fails on UCRT64 (MSYS2)

### ISSUE THREAD

**Issue by neheb** [gabime/spdlog#2404]
```
  REQUIRE( val >= wait_duration.count() )^M
with expansion:^M
  0.2496895 >= 0.25^M
```

**Comment by neheb** [comment]
Actually 1 fails too:

```
  REQUIRE( sw.elapsed() >= wait_ms )^M
with expansion:^M
  {?} >= {?}^M
^M

```

**Comment by neheb** [comment]
Sounds like a GCC bug...

https://news.ycombinator.com/item?id=7923817

**Comment by tt4g** [comment]
I suspect it is due to the accuracy of the Windows timer, which is accurate to about 16ms, so the `sleep()` wakeups are getting faster (https://randomascii.wordpress.com/2020/10/04/windows-timer-resolution-the-great-rule-change/).

Does the code in [this comment](https://stackoverflow.com/a/41862592) not solve the issue?

> Another Quick Solution
>
> As you might have noticed, above code is no longer very light-weight. It needs to include Windows header among others things which might not be very desirable if you are developing header-only libraries. If you need sleep less than 2ms and you are not very keen on using OS code then you can just use following simple solution which is cross platform and works very well on my tests. Just remember that you are now not using heavily optimized OS code which might be much better at saving power and managing CPU resources.
>
> ```cpp
> typedef std::chrono::high_resolution_clock clock;
> template <typename T>
> using duration = std::chrono::duration<T>;
>
> static void sleep_for(double dt)
> {
>     static constexpr duration<double> MinSleepDuration(0);
>     clock::time_point start = clock::now();
>     while (duration<double>(clock::now() - start).count() < dt) {
>         std::this_thread::sleep_for(MinSleepDuration);
>     }
> }
> ```

**Comment by neheb** [comment]
Quite a hack. Wouldn’t a call to https://docs.microsoft.com/en-us/windows/win32/api/timeapi/nf-timeapi-timebeginperiod be sufficient?

**Comment by tt4g** [comment]
`timeBeginPeriod()` changes the global timer interrupt frequency, so it also affects processes other than testing.
I think some people would disagree with calling such an API to make the test pass.
Also, as mentioned in the blog post, it should be noted that the timer frequency may not improve as much as expected after calling `timeBeginPeriod()`.
It is expected that some machines will not pass the test even if they try to call this API.

I think it would be better to modify the test case to take into account the error of the Windows timer. It would be better to change the sleep interval of the test to 500 milliseconds and allow for an error of plus or minus 15 ms, so that the scope of impact of the fix is smaller.

**Comment by neheb** [comment]
I’m curious why LLVM’s libc++ has no such issue.

**Comment by tt4g** [comment]
I don't know. My guess is that MinGW is a project intended for a GNU port, and the timer interrupt frequency may have been changed internally for GNU compliance.

**Comment by neheb** [comment]
Maybe libc++ has a fix for this quirk with Windows. Maybe @mstorsjo knows.

**Comment by neheb** [comment]
Ah found out why: https://github.com/llvm/llvm-project/blob/main/libcxx/src/support/win32/thread_win32.cpp#L245

It ceils the value.

**Comment by tt4g** [comment]
I looked at the `spdlog::stopwatch` header file and noticed that the role of this class is to display the elapsed time since being constructed.

https://github.com/gabime/spdlog/blob/a26e174b367a60a51f0be83a81d6d066330cdd8f/include/spdlog/stopwatch.h#L8-L9

So, the test should confirm that this role is being fulfilled.
In that light, the frequency of system timer interruptions has nothing to do with the nature of the test. It should be possible to rewrite the test case to focus only on the fact that the elapsed time is measured.

@gabime What do you think about rewriting the following source to measure `diff_duration` in the test case?
This rewrite should prevent the test case from failing due to the accuracy of the system timer.
This test method may seem redundant, but it is the same as the previous test in that it checks that `spdlog::stopwatch` is doing its role of measuring time.

`tests/test_stopwatch.cpp`:

```cpp
#include "includes.h"
#include "test_sink.h"
#include "spdlog/stopwatch.h"

TEST_CASE("stopwatch1", "[stopwatch]")
{
    using std::chrono::milliseconds;
    using clock = std::chrono::steady_clock;
    milliseconds wait_ms(250);
    milliseconds tolerance_ms(250);

    spdlog::stopwatch sw;
    milliseconds start_ms = clock::now();
    std::this_thread::sleep_for(wait_ms);
    milliseconds stop_ms = clock::now();
    milliseconds diff_ms = stop_ms - start_ms;
    REQUIRE(sw.elapsed() >= diff_ms);
    REQUIRE(sw.elapsed() <= diff_ms + tolerance_ms);
}

TEST_CASE("stopwatch2", "[stopwatch]")
{
    using std::chrono::milliseconds;
    using std::chrono::duration_cast;
    using clock = std::chrono::steady_clock;
    using duration = clock::duration;

    duration wait_duration(milliseconds(250));
    duration tolerance_duration(milliseconds(250));

    auto test_sink = std::make_shared<test_sink_st>();
    spdlog::logger logger("test-stopwatch", test_sink);
    logger.set_pattern("%v");

    spdlog::stopwatch sw;
    duration start_duration = clock::now().time_since_epoch();
    std::this_thread::sleep_for(wait_duration);
    duration stop_duration = clock::now().time_since_epoch();
    logger.info("{}", sw);
    auto val = std::stod(test_sink->lines()[0]);

    duration diff_duration = stop_duration - start_duration;
    REQUIRE(val >= diff_duration.count());
    REQUIRE(val <= (diff_duration + tolerance_duration).count());
}

```

<details>
<summary>Diff</summary>

```diff
 #include "includes.h"
 #include "test_sink.h"
 #include "spdlog/stopwatch.h"
 
 TEST_CASE("stopwatch1", "[stopwatch]")
 {
     using std::chrono::milliseconds;
+    using clock = std::chrono::steady_clock;
     milliseconds wait_ms(250);
     milliseconds tolerance_ms(250);
 
     spdlog::stopwatch sw;
+    milliseconds start_ms = clock::now();
     std::this_thread::sleep_for(wait_ms);
+    milliseconds stop_ms = clock::now();
+    milliseconds diff_ms = stop_ms - start_ms;
-    REQUIRE(sw.elapsed() >= wait_ms);
-    REQUIRE(sw.elapsed() <= wait_ms + tolerance_ms);
+    REQUIRE(sw.elapsed() >= diff_ms);
+    REQUIRE(sw.elapsed() <= diff_ms + tolerance_ms);
 }
 
 TEST_CASE("stopwatch2", "[stopwatch]")
 {
     using spdlog::sinks::test_sink_st;
+    using std::chrono::milliseconds;
+    using std::chrono::duration_cast;
+    using clock = std::chrono::steady_clock;
+    using duration = clock::duration;
 
-     std::chrono::duration<double> wait_duration(0.250);
-     std::chrono::duration<double> tolerance_duration(0.250);
+     duration wait_duration(milliseconds(250));
+     duration tolerance_duration(milliseconds(250));
 
     auto test_sink = std::make_shared<test_sink_st>();
+    spdlog::logger logger("test-stopwatch", test_sink);
+    logger.set_pattern("%v");
 
     spdlog::stopwatch sw;
+    duration start_duration = clock::now().time_since_epoch();
-    spdlog::logger logger("test-stopwatch", test_sink);
-    logger.set_pattern("%v");
     std::this_thread::sleep_for(wait_duration);
+    duration stop_duration = clock::now().time_since_epoch();
     logger.info("{}", sw);
     auto val = std::stod(test_sink->lines()[0]);
 
+    duration diff_duration = stop_duration - start_duration;
-    REQUIRE(val >= wait_duration.count());
-    REQUIRE(val <= (wait_duration + tolerance_duration).count());
+    REQUIRE(val >= diff_duration.count());
+    REQUIRE(val <= (diff_duration + tolerance_duration).count());
 }

```
</details>

**Comment by gabime** [comment]
@tt4g Seema like a good idea. Especially in cases where the `sleep_for()` takes  longer than expected (that's why I added the tolerance of 250ms).
Why the the use of the `time_since_epoch()`  instead of just `now()` ? 
Also, I think the ```milliseconds start_ms = clock::now();``` should be called before the sw is created.

**Comment by tt4g** [comment]
@gabime Thank you for your review. The source code with the corrections you have pointed out is as follows.

```cpp
#include "includes.h"
#include "test_sink.h"
#include "spdlog/stopwatch.h"

TEST_CASE("stopwatch1", "[stopwatch]")
{
    using std::chrono::milliseconds;
    using clock = std::chrono::steady_clock;
    milliseconds wait_ms(250);
    milliseconds tolerance_ms(250);

    milliseconds start_ms = clock::now();
    spdlog::stopwatch sw;
    std::this_thread::sleep_for(wait_ms);
    milliseconds stop_ms = clock::now();
    milliseconds diff_ms = stop_ms - start_ms;
    REQUIRE(sw.elapsed() >= diff_ms);
    REQUIRE(sw.elapsed() <= diff_ms + tolerance_ms);
}

TEST_CASE("stopwatch2", "[stopwatch]")
{
    using std::chrono::milliseconds;
    using std::chrono::duration_cast;
    using clock = std::chrono::steady_clock;
    using duration = clock::duration;

    duration wait_duration(milliseconds(250));
    duration tolerance_duration(milliseconds(250));

    auto test_sink = std::make_shared<test_sink_st>();
    spdlog::logger logger("test-stopwatch", test_sink);
    logger.set_pattern("%v");

    spdlog::stopwatch sw;
    duration start_duration = clock::now();
    std::this_thread::sleep_for(wait_duration);
    duration stop_duration = clock::now();
    logger.info("{}", sw);
    auto val = std::stod(test_sink->lines()[0]);

    duration diff_duration = stop_duration - start_duration;
    REQUIRE(val >= diff_duration.count());
    REQUIRE(val <= (diff_duration + tolerance_duration).count());
}

```

@neheb Can you rewrite the test code and see if the test passes? If the test passes, please open a pull request.

**Comment by neheb** [comment]
that doesn't compile. now() returns a time_point, not a duration.

edit: yeah

```
with expansion:
  0.250343796 >= 250
```

edit2: seems test_mpmc_q.cpp fails now...

**Comment by neheb** [comment]
After fixing that code the test succeeds.
