### ISSUE TITLE
centos7 build error for pattern_formatter-inl.h:1056:12:,

### ISSUE THREAD

**Issue by kanli201904** [gabime/spdlog#2427]
Hello:
I met one error on centos7: Can you have some suggestions?
spdlog**/pattern_formatter-inl.h:1056:12: error: cannot bind**
‘std::unique_ptr<spdlog::pattern_formatter, std::default_deletespdlog::pattern_formatter >’
lvalue to
‘std::unique_ptr<spdlog::pattern_formatter, std::default_deletespdlog::pattern_formatter >&&’
return cloned;
....
/usr/include/c++/4.8.2/bits/unique_ptr.h:169:2: error: initializing argument 1 of
‘std::unique_ptr<_Tp, _Dp>::unique_ptr(std::unique_ptr<_Up, _Ep>&&)
[with _Up = spdlog::pattern_formatter; _Ep = std::default_deletespdlog::pattern_formatter; = void;
_Tp = spdlog::formatter; _Dp = std::default_deletespdlog::formatter]’
unique_ptr(unique_ptr<_Up, _Ep>&& __u) noexcept

**Comment by tt4g** [comment]
That is due to the changes made in this PR #2396.
This is a change to activate NRVO (named return value optimization"), but it may fail to compile if this feature is not provided.

cppreference: https://en.cppreference.com/w/cpp/language/copy_elision

I cannot determine this is a compiler bug. 
Anyway, if revert 298a200f69d66114adde2d5d8ad34f2cce5a5b69, you can compile it. Instead, the opportunity for NRVO is lost.

**Comment by kanli201904** [comment]
@tt4g ： Thanks,i got it.
