### ISSUE TITLE
Is it possible to zero-fill line numbers?

### ISSUE THREAD

**Issue by mcondarelli** [gabime/spdlog#2511]
I tried something like:
```
    spdlog::set_pattern("[%3!l][%15s::%-04#] %v");
```
but it doesn't seem to work.

**Comment by tt4g** [comment]
Zero-fill alignment format flags are not supported.

Presumably, zero fill is not supported because line numbers are converted to strings before the alignment process.

EDIT: This is not to say that it is technically impossible, but rather that we did not anticipate that there would be a requirement to zero-fill strings.
