### ISSUE TITLE
Error when use with Android

### ISSUE THREAD

**Issue by paulocoutinhox** [gabime/spdlog#2520]
Hi,

I have a problem when use with Android:

```
#if defined(__ANDROID__)
#include "spdlog/spdlog.h"
#include "spdlog/sinks/android_sink.h"
auto logger = spdlog::android_logger_mt("android", "XPLPC");
spdlog::set_default_logger(logger);
#endif
```

Error:

```
In file included from /Users/paulo/Developer/workspaces/cpp/xplpc/jni/lib/src/xplpc/jni/PlatformProxy.cpp:8:
In file included from /Users/paulo/Developer/workspaces/cpp/xplpc/cxx/custom/include/xplpc/custom/Mapping.hpp:2:
/Users/paulo/Developer/workspaces/cpp/xplpc/cxx/lib/include/xplpc/xplpc.hpp:7:9: error: no type named 'set_default_logger' in namespace 'spdlog'
spdlog::set_default_logger(logger);
~~~~~~~~^
```

Can anyone help me?

**Comment by tt4g** [comment]
I suspect that the spdlog source code is not correctly included by `#include "spdlog/spdlog.h"` due to the existence of a file named `spdlog.h` in your project.

The C/C++ compiler includes the first file in the include path whose path matches. If the library and include file paths conflict, the library header will not be included (your header file will be included instead).
In this case you should rename the file in your project.
