### ISSUE TITLE
multi-thread print order

### ISSUE THREAD

**Issue by bayec** [gabime/spdlog#2569]
Hi,

I created a logger, use it in multi-thread, then timestamp is disorder.

Test code:
```c++
#include "spdlog/spdlog.h"
#include "spdlog/sinks/stdout_color_sinks.h"

void thread_proc(const std::shared_ptr<spdlog::logger>& logger, const std::string& name)
{
    for (;;)
    {
        logger->info("{}", name);
    }
}

int main()
{
    std::shared_ptr<spdlog::logger> console = spdlog::stdout_color_mt("console");
    console->set_pattern("[%Y-%m-%d %H:%M:%S.%f][%l][%n][%t]: %v");

    std::vector<std::thread> threads;
    for (int i = 0; i < 3; ++i)
    {
        threads.emplace_back(thread_proc, console, "t" + std::to_string(i));
    }

    for (auto &t : threads)
    {
        t.join();
    }
}
``` 

Output of part:
![image](https://user-images.githubusercontent.com/16732948/205685579-8778cff6-4b31-4ffe-9c2c-0c37b1078b8e.png)

Please help me, thanks.

**Comment by tt4g** [comment]
Duplicate #376, #1558

**Comment by tt4g** [comment]
Supplemental information.

If you do not pass the log time in the logging method argument, the log time is generated by `spdlog::details::os::now()` in the logging method.

https://github.com/gabime/spdlog/blob/f0cd9d15308007aa84068d0373b52bcaa67e3823/include/spdlog/logger.h#L207-L231

https://github.com/gabime/spdlog/blob/f0cd9d15308007aa84068d0373b52bcaa67e3823/include/spdlog/details/log_msg-inl.h#L27-L34

Since this operation is performed without a critical section by `std::mutex` or other means, the order of execution may be swapped in a multi-threaded environment between the creation of the log time and when the log is passed to sink.

**Comment by bayec** [comment]
@tt4g OK, I really appreciate your help.
