### ISSUE TITLE
tsan false warnings for mpmc_blocking_queue::dequeue_for

### ISSUE THREAD

**Issue by alokpr** [gabime/spdlog#2587]
gcc 11.3.0 on Ubuntu 22.04 reports "data race" and "double lock of a mutex" for `mpmc_blocking_queue::dequeue_for`

This is most probably due to this gcc bug - https://gcc.gnu.org/bugzilla//show_bug.cgi?id=101978

Replacing timed [wait_for](https://github.com/gabime/spdlog/blob/edc51df1bdad8667b628999394a1e7c4dc6f3658/include/spdlog/details/mpmc_blocking_q.h#L58) with `std::condition_variable::wait` avoids the tsan warnings.

This of course should be fixed in gcc, but I am curious what is the reason for wait_for in the first place? Do you see any issues with replacing `wait_for` with `wait`?

**Comment by tt4g** [comment]
This is because `mpmc_blocking_queue` is designed as a queue for the Producer-Consumer pattern (as described at the top of the header file).

https://github.com/gabime/spdlog/blob/edc51df1bdad8667b628999394a1e7c4dc6f3658/include/spdlog/details/mpmc_blocking_q.h#L6-L11

Many developers may want to allow the Consumer thread to perform other tasks while there are no messages in the queue.
It is a commonplace idea to implement a dequeue (pop) API with a timeout on the queue for this purpose.

**Comment by alokpr** [comment]
The `mpmc_blocking_queue` is only used in `thread_pool` though, where the consumer thread does not perform any idle task. It unnecessarily wakes up the thread every 10s only to go back to waiting for the next message - https://github.com/gabime/spdlog/blob/edc51df1bdad8667b628999394a1e7c4dc6f3658/include/spdlog/details/thread_pool-inl.h#L114

If there is a desire for `mpmc_blocking_queue` to be a generic producer-consumer queue, may be we could add another blocking non-timed `dequeue` and use that in `thread_pool`? Unless I am missing some other reason for the timeout?

**Comment by tt4g** [comment]
I did not develop `thread_pool` so I don't know why it uses `dequeue_for()`.

If you think wakeup every 10 seconds is useless, you can create a PR, but I personally don't see the need to change the current implementation for the purpose of avoiding the compiler sanitizer bug.

**Comment by alokpr** [comment]
Agreed that just avoiding the sanitizer bug is not a good justification for a change. Created PR #2588 to avoid unnecessary wakeups.
