### ISSUE TITLE
a global logger sink a log erro when  exit the program ? how can i fix it?

### ISSUE THREAD

**Issue by jiudianren** [gabime/spdlog#2594]

**Comment by tt4g** [comment]
We don't know anything because no source code has been provided to reproduce the problem.

EDIT: From the uploaded image, I can see that the logger is being called after the application has exited because `__GI_exit()` is printed on the backtrace.
This is an undefined behavior of spdlog because the destructor of the logger may have been called when the application exits. The behavior is not guaranteed.
