### ISSUE TITLE
Stopwatch without fmt.h?

### ISSUE THREAD

**Issue by eddelbuettel** [gabime/spdlog#2611]
On a project where we use spdlog in an application layer (from R) but also bring in `libspdlog.a` for another library, I was getting linking errors on Windows when also using the `stopwatch` object via its header.   I can avoid these when I use a local header that defines the object but does not bring in `fmt.h`.   

Would a narrower `stopwatch` object header that made `fmt` optional be of more general interest?

**Comment by tt4g** [comment]
spdlog uses the [fmt library](https://github.com/fmtlib/fmt) for formatting log messages. spdlog's base API depends on the fmt library, so the dependency cannot be excluded.

The option to use c++20 `std::format` instead of the fmt library is provided.
Define `SPDLOG_USE_STD_FORMAT` macro or define CMake variable `SPDLOG_USE_STD_FORMAT` to enable this option.

https://github.com/gabime/spdlog/blob/654dbc5c3291a0981e6c473fac199409d41fcde8/include/spdlog/fmt/fmt.h#L13-L15

https://github.com/gabime/spdlog/blob/654dbc5c3291a0981e6c473fac199409d41fcde8/CMakeLists.txt#L87

There is also an option to make the fmt library externally.
Define `SPDLOG_FMT_EXTERNAL` macro or define CMake variable `SPDLOG_FMT_EXTERNAL` (`SPDLOG_FMT_EXTERNAL_HQ` macro is only for use in header-only) to enable this option.
However, this probably cannot be used as a solution to the problem because it requires the fmt library as a dependency of the C++ library.

https://github.com/gabime/spdlog/blob/654dbc5c3291a0981e6c473fac199409d41fcde8/include/spdlog/fmt/fmt.h#L30-L33

https://github.com/gabime/spdlog/blob/654dbc5c3291a0981e6c473fac199409d41fcde8/CMakeLists.txt#L88-L89

**Comment by tt4g** [comment]
The only part of the `stopwatch.h` file that depends on the formatter is the following:

https://github.com/gabime/spdlog/blob/654dbc5c3291a0981e6c473fac199409d41fcde8/include/spdlog/stopwatch.h#L51-L69

If the problem can be avoided by using the C++20 formatter API, then define an `SPDLOG_USE_STD_FORMAT` macro.

**Comment by eddelbuettel** [comment]
@tt4g I am aware of all that but that didn't help me one bit.  

> so the dependency cannot be excluded

It can be, and I am doing it.  It's a bit convoluted but in [RcppSpdlog](https://github.com/eddelbuettel/rcppspdlog) I provide the base layer and include `spdlog`.  I wrap another simpler API around in [spdl](https://github.com/eddelbuettel/spdl) which allows me access the same API from R and C++ (using a subset of `spdlog` I export via R's mechanism as plain C and not C++).  Now in a branch I currently have [exactly what this issue is about: stopwatch, but no `fmt`](https://github.com/TileDB-Inc/TileDB-R/blob/de/sc-24621/use_tiledb_2.14.0/inst/include/tinyspdl/stopwatch.h) because we can extract time elapsed as a numeric variable (`double`, say) which `std::to_string` can deal with just fine without needing `fmt`.  

Hence my question. Here is a working 'proof' of `spdlog::stopwatch` without `fmt`.  This may have more general interest because I am working with a project bringing in `libspdlog.a` (in Windows, I know ...) and it would be sweet to not clash over `fmt`.

**Comment by eddelbuettel** [comment]
I am (for now) bound to C++17 and yes I am aware that C++20 offers `std::format` which I plan to switch to . I also know that many users of these packages will be stuck with C++11, C++14, ... for years to come so addressing this could help some.

**Comment by tt4g** [comment]
I am not the maintainer of this repository, so I don't know if there will be major changes such as removing the dependency on the fmt library (moving completely to the `std::format` API).
In my opinion, since C++20 is a new standard specification, many platforms are not supported. spdlog will not become a C++20 library until much later.

**Comment by eddelbuettel** [comment]
I am getting by with a modified header file with fmt, which on one platform clashes when used win another library. It's not the end of the world, but it may be something worth considering.  `spdlog` is otherwise amazing and quite a joy to use.  And C++20 and `std:;format` should make this issue go away for me,

**Comment by gabime** [comment]
> spdlog is otherwise amazing and quite a joy to use. 

Thanks :)

> It's not the end of the world, but it may be something worth considering

The main reason for the stopwatch class is to be able to use it as a format arg. Otherwise it is just a basic stopwatch utility with no relation to logging.

**Comment by eddelbuettel** [comment]
Yes, that is also how I used it.  But I have one more complex deployment where spdlog + fmt come in also via a different library, and that ended up in tears on Windows.  I juggle a few things differently there by having the spdlog logic in an R package, and 'exporting' functionality across R packages via a plain C interface for FFI.  That all works ... and I get to 'hide' fmt, but stopwatch.h currently breaks it.   That is not lethal, and we plan to move to C++20 for that project anyway so using `std` may alleviate it.  

So please feel free to close this if there is no redeeming aspect for spdlog 'at large'.  I just felt I should mention the potential issue (in a corner case) and my workaround.
