### ISSUE TITLE
[help wanted]how to add sink with lz4 compress

### ISSUE THREAD

**Issue by nzcv** [gabime/spdlog#2645]
here is the example, https://github.com/lz4/lz4/blob/dev/examples/fileCompress.c

i set spdlog::flush_every(std::chrono::seconds(3));

my question is:

because flush_ is call 3seconds intervally, call LZ4F_writeClose at where? 

or is there another way to compress log?

**Comment by tt4g** [comment]
I don't see what `compress' has to do with `flush()`.

Some sinks accept `file_event_handlers` so that `after_close()` callback can compress the log file.

https://github.com/gabime/spdlog/blob/4f800773393d3ebac13c1fcd946a315d4d72bcd9/include/spdlog/common.h#L322-L335

https://github.com/gabime/spdlog/blob/da14258533cb951ce85087ceb45556e0b8253660/include/spdlog/sinks/basic_file_sink.h#L23

https://github.com/gabime/spdlog/blob/f29f369a12c701db27e816c6762e914863e8e951/include/spdlog/details/file_helper-inl.h#L101-L118

Other way, create a custom sink: https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink

**Comment by nzcv** [comment]
sloved it.
