### ISSUE TITLE
How to avoid to create empty log file？

### ISSUE THREAD

**Issue by CheneyDu0129** [gabime/spdlog#2695]
When i use file as logger output，Even if there is no log to print, an empty log file is still created. How can i avoid this?<br>
![image](https://user-images.githubusercontent.com/72074750/229361698-0164a052-58c2-4eff-a503-ac873820ce44.png)

**Comment by tt4g** [comment]
Since the file is opened in the constructor of file sink, there is no way to avoid file creation.
It is possible to delete an empty file by passing the `file_event_handlers.after_close()` event handler.

https://github.com/gabime/spdlog/blob/0ca574ae168820da0268b3ec7607ca7b33024d05/include/spdlog/sinks/basic_file_sink.h#L23

https://github.com/gabime/spdlog/blob/0ca574ae168820da0268b3ec7607ca7b33024d05/include/spdlog/common.h#L329-L342

If you really want to avoid creating empty files, create your own sink.
This sink can avoid the creation of empty files by creating file sink at the first logging.
Implementing your own sink: https://github.com/gabime/spdlog/wiki/4.-Sinks#implementing-your-own-sink

**Comment by CheneyDu0129** [comment]
Thanks. Your answer can reslove my question.
