### ISSUE TITLE
error	C2338	static_assert failed: 'Cannot format an argument. To make type T formattable provide a formatter<T> specialization

### ISSUE THREAD

**Issue by RIKDXHQ11** [gabime/spdlog#2714]
\spdlog\include\spdlog\fmt\bundled\core.h	418	
error	C2338	static_assert failed: 'Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt'

Log::GetXXXLogger()->trace(__VA_ARGS__)

I downloaded the latest version 1.11.0
But this problem is still unresolved.

**Comment by tt4g** [comment]
Duplicate #2593, #2345, #2021

As the error message helpfully explains, go to the link https://fmt.dev/latest/api.html#udt and define `fmt::formatter<T>` for `T`

**Comment by RIKDXHQ11** [comment]
> Duplicate #2593, #2345, #2021
> 
> As the error message helpfully explains, go to the link https://fmt.dev/latest/api.html#udt and define `fmt::formatter<T>` for `T`

Hello, I can't understand that.
Please tell me what file to modify and where it is located. thank you!

**Comment by tt4g** [comment]
You have to define `fmt::format` in your project because the fmt library does not know how to format the `T` type.

The `T` type is something passed in `__VA_ARGS__`. The error message is incomplete so I don't know what it is.

If you don't know what you are doing by visiting https://fmt.dev/latest/api.html#udt, then learn about the C++ template.
