### ISSUE TITLE
Formatting fails with `const unsigned char *`

### ISSUE THREAD

**Issue by NOOBDY** [gabime/spdlog#2719]
On spdlog 1.11.0 formatting `const unsigned char *` causes compile errors
E.g.
```cpp
// `glGetString()` returns `const unsigned char *`
spdlog::info("{}", glGetString(GL_VERSION));
```
Using
```cpp
spdlog::info("{}", reinterpret_cast<const char *>(glGetString(GL_VERSION)));
```
fixes it temporarily

This issue doesn't exist on 1.10.0

Here is the complete compile error [log](https://pastebin.com/0C672d9Z)

**Comment by tt4g** [comment]
Impact of changes in the fmt library: fmtlib/fmt#3307

As explained in the fmt issue, `char`, `signed char`, and `unsigned char` are all treated as different types by the C++ specification (https://en.cppreference.com/w/cpp/language/types).
The current behavior is considered correct by the C++ specification, since implicit conversion can cause problems on some platforms.

**Comment by NOOBDY** [comment]
I see, thanks for the explanation
