### ISSUE TITLE
is async logger real async?

### ISSUE THREAD

**Issue by bethebest0622** [gabime/spdlog#2771]
here is the code:

```
#include "spdlog/async.h"
#include "spdlog/async_logger.h"
#include "spdlog/cfg/env.h"
#include "spdlog/fmt/ostr.h"
#include "spdlog/sinks/basic_file_sink.h"
#include "spdlog/sinks/callback_sink.h"
#include "spdlog/sinks/daily_file_sink.h"
#include "spdlog/sinks/sink.h"
#include "spdlog/spdlog.h"

int main() {
  auto async_file = spdlog::basic_logger_mt<spdlog::async_factory>("async_file_logger", "logs/async_log.txt");

  for (int i = 1; i < 10000000; ++i) {
    async_file->info("Async message #{}", i); 
  }
  printf("here reached\n");
}
```

i found the `here reached` info will release after the file writing finished. which in my understanding, it's sync.

async should be: the info will return at once, then the `here reached` comes out, and the async thread will handle the writing part.

is there anything i misunderstand?

**Comment by tt4g** [comment]
I'm not sure at what point you expected the code to run asynchronously, but the async logger logging method runs synchronously.
What is asynchronous is the operation in which sink writes log messages to a file.

Also, the output of `here reached` may be delayed by buffering because `fflush(stdout)` is not called after `printf`.
