### ISSUE TITLE
not able to see logs when same process has 2 loggers with different logger name

### ISSUE THREAD

**Issue by nitingaikwad-28** [gabime/spdlog#2864]
I am facing below issue with spdlogger.
In one process , I create spd logger with some file name using Sink vector. But when I try to create spd logger second time in same process with different file name, not able to see the logs into file when below line is called second time with different - logger name.
std::make_sharedspdlog::logger(spdlog::logger("loggername2", sink.begin(),sink.end())
First log file in process has log in it but second log file with another name is 0 byte size file

Thanks in advance for help !!

**Comment by gabime** [comment]
Please provide sample code to reproduce

**Comment by nitingaikwad-28** [comment]
After debugging it is observed that - 
1. log file with zero size[empty file] gets created immediately once process is started 
2. log file becomes non zero and able to see the logs when process is closed, my assumption is that log file is not getting flushed when process is on.

Below is code
vector<sint_ptr> sinks;
filesink = std::make_shared<spdlog::sinks::basic_file_sink_mt>  ( "File1",  true);
sinks.push_back(filesink)
 std::make_sharedspdlog::logger(spdlog::logger("loggername1", sinks.begin(),sinks.end())
 
 then in same process other function
vector<sint_ptr> sinks2;
filesink2 = std::make_shared<spdlog::sinks::basic_file_sink_mt>  ( "File2",  true);
sinks2.push_back(filesink2)
 std::make_sharedspdlog::logger(spdlog::logger("loggername2", sinks2.begin(),sinks2.end())
 
 Also suggest if is there any other way to cleanup/destroy logget than just adding below line to destructo:
spdlog::shutdown();

**Comment by tt4g** [comment]
If it is a Windows OS, the OS may not output log messages from the buffer to a file at process exit if `spdlog::shutdown()` is not called.

**Comment by nitingaikwad-28** [comment]
Thanks, I m using Linux-ubuntu. So any hints behind empty log file for second logger different filename

**Comment by tt4g** [comment]
Maybe the logs are not being output because they were filtered at the log level?

**Comment by nitingaikwad-28** [comment]
no actually that is not the case, I confirmed the logging level. Even after making it trace , it does repeat the issue. 
is there anything like flush every time ot is it resource intensive

**Comment by tt4g** [comment]
`logger->flush_on(spdlog::level::trace)`

https://github.com/gabime/spdlog/wiki/7.-Flush-policy

**Comment by nitingaikwad-28** [comment]
But is there any negative impact on system if we call logger->flush() in Process constructor.
My knowledge is that if we use explicit "flush_on" , process will be little slower as flush will go on every time it receives that severity. Could you please guide on this

**Comment by tt4g** [comment]
What is a process constructor?
In any case, the purpose of calling `logger->flush_on(spdlog::level::trace)` now is to determine the cause of the problem, and once the cause is found it should be removed.

EDIT: Are you using loggers before or after the `main()` function? It is not guaranteed to work due to C/C++ specifications.

**Comment by nitingaikwad-28** [comment]
you mean - below line must not be used in production code? 
 logger->flush_on(spdlog::level::trace)  
when I added above line in main function while creating class object, it is observed that logs are written immediately to log file , so seems my problem is solved after using above line 
 But is above line supposed to be used in production code ? if not what is reason behind it.
 Thank you very much for all your responses !!!

**Comment by tt4g** [comment]
It does not mean that `logger->flush_on(spdlog::level::trace)` should not be used in a production.
However, performance is poor because a flush operation is performed each time the logging function is called.

And the fact that logs are now written to a file after adding `logger->flush_on(spdlog::level::trace)` means that the logger you created will not be properly released before the application exits.
This is because sink performs the flush operation in the destructor when it is released.
Your application does not release the logger in the `main()` function because sink is not released unless the logger is released.
