### ISSUE TITLE
example_header_only PRIVATE spdlog::spdlog_header_only

### ISSUE THREAD

**Issue by foxnight2** [gabime/spdlog#2891]
https://github.com/gabime/spdlog/blob/91807c2e718890ca2c0c88620326c6919ce041f4/example/CMakeLists.txt#L15
https://github.com/gabime/spdlog/blob/91807c2e718890ca2c0c88620326c6919ce041f4/example/CMakeLists.txt#L22

```
target_link_libraries(example PRIVATE spdlog::spdlog $<$<BOOL:${MINGW}>:ws2_32>)
    target_link_libraries(example_header_only PRIVATE spdlog::spdlog_header_only)

```
There are at the example/,  but I try to build it with example, it is depend on the root CmakeList.txt

**Comment by tt4g** [comment]
I do not know what you are asking.

`example/CMakeLists.txt` file is imported by `CMakeLists.txt` in the project root.
This is because CMake can have `CmakeList.txt` placed in a subdirectory in order to split the project.
This makes building `example` and `example_header_only` optional.

https://github.com/gabime/spdlog/blob/91807c2e718890ca2c0c88620326c6919ce041f4/CMakeLists.txt#L274-L281

**Comment by foxnight2** [comment]
Thanks a lot.
What does it mean? I can't understand it.

```
spdlog::spdlog $<$<BOOL:${MINGW}>:ws2_32>
```

**Comment by tt4g** [comment]
`$<...>` is CMake generator expressions.
See: https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html

`target_link_libraries(example PRIVATE spdlog::spdlog $<$<BOOL:${MINGW}>:ws2_32>)` means that `ws2_32` is added to the link target only MinGW environment.

```
# Evaluate on MinGW
target_link_libraries(example PRIVATE spdlog::spdlog ws2_32)

# Evaluate on not MinGW
target_link_libraries(example PRIVATE spdlog::spdlog)
```
