### ISSUE TITLE
Error when empty string is passed as a logger name

### ISSUE THREAD

**Issue by vit0l** [gabime/spdlog#2933]
**spdlog v1.12.0**

Passing empty string as a logger-name to basic_logger_mt() like this:
```c++
auto m_logFile = "/path/to/file.log";
    try {
        m_logger = spdlog::basic_logger_mt("", m_logFile);
    } catch (const spdlog::spdlog_ex &ex) {
        m_logger->error("Can't start logging to file: {}", m_logFile);
        return false;
    }
```
 triggers the following error:

`Exception 0xc0000005 encountered at address 0x7ff6cc602e55: Access violation reading location 0x00000050`

**Comment by tt4g** [comment]
This is because the default logger name is an empty string.
Loggers with the same name cannot be registered.

https://github.com/gabime/spdlog/blob/ac55e60488032b9acde8940a5de099541c4515da/include/spdlog/details/registry-inl.h#L35-L48

Access violations are caused by your source code.
You are trying to log by `m_logger` what `m_logger` could not create.
That is inconsistent.

**Comment by vit0l** [comment]
Ok, thank you for shedding light on this!
I guess it would be a good idea to check against this by library code or trigger an exception.

Actually, I was blindly searching for a way to create a file logger with an "empty" name, which is, as you explained, a default name. How to achieve this with `basic_logger_mt()`?

**Comment by gabime** [comment]
You can replace the default logger with a logger with non empty string

**Comment by vit0l** [comment]
> You can replace the default logger with a logger with non empty string

Great, thanks for help!

Please, consider to close this issue if all is fine.
