### ISSUE TITLE
SpdLog crashes when registered as async_logger, compiled in c++20 and with O3 optimizations

### ISSUE THREAD

**Issue by develHector** [gabime/spdlog#2937]
When declaring spdlog as async_logger, c++20 and O3 optimizations, it crashes producing no log and alerting this way:
  [*** LOG ERROR #0001 ***] [2023-11-09 12:08:56] [TEST] async log: thread pool doesn't exist anymore
  [*** LOG ERROR #0005 ***] [2023-11-09 12:08:58] [TEST] async flush: thread pool doesn't exist anymore
  [*** LOG ERROR #0006 ***] [2023-11-09 12:08:59] [TEST] async flush: thread pool doesn't exist anymore
PS: That happens even with 1.12 or newer versions even the trunk/master one.
PS: The very same code does well without optimizations or going back to c++17.
PS: gdb shows the problem with regards to chrono duration at the internals of the asycronicity.
PS: Also appears to be when running multiple loggers.

**Comment by tt4g** [comment]
It is caused by the logger being used after `spdlog::shutdown()`.

**Comment by develHector** [comment]
> It is caused by the logger being used after `spdlog::shutdown()`.

Well, as if it were, but actually not. As commented, the very same code runs perfectly just by lowering the optimization level or moving the compiler back to c++17. Appears to be the new ways chrono::duration in c++20 is being managed.

**Comment by tt4g** [comment]
> Appears to be the new ways chrono::duration in c++20 is being managed.

What do you mean?

**Comment by tt4g** [comment]
From the error message "async flush: thread pool doesn't exist anymore", this error is caused by calling `spdlog::async_logger::flush()` after `spdlog::shutdown()`.

NOTE: `spdlog::async_logger::flush_()` is called from `flush()`.

https://github.com/gabime/spdlog/blob/ac55e60488032b9acde8940a5de099541c4515da/include/spdlog/async_logger-inl.h#L45-L55

https://github.com/gabime/spdlog/blob/ac55e60488032b9acde8940a5de099541c4515da/include/spdlog/logger-inl.h#L97-L98

I don't think `std::chrono::duration` is involved.

If the error does not occur when the optimization level is lowered, then it is probably due to the fact that your project's code is built to cause problems when reordered with optimization.
Or a bug in the compiler.

---

Even if `spdlog::flush_every();` is called, the error as reported will not occur because the thread pool `tp_` is deleted after the flash worker `periodic_flusher_` is deleted first.

https://github.com/gabime/spdlog/blob/ac55e60488032b9acde8940a5de099541c4515da/include/spdlog/details/registry-inl.h#L202-L215

**Comment by tt4g** [comment]
There was another possible bug.
Your project's async logger is using a thread pool that is not registered in spdlog.
The lifecycle of thread pools not registered in spdlog are not managed by spdlog.

Wiki: https://github.com/gabime/spdlog/wiki/6.-Asynchronous-logging#construct-directly-and-use-a-custom-thread-pool

**Comment by develHector** [comment]
> re was another possible bug.
> Your project's async logger is using a thread pool that is not regist

Well, that should fail under c++17 and without 03, thing that doesn't.
We will switch the second logger to a sync one to circumvent the problem for now, in the possibility other affected users find a better way to express it, if any.
Thank you anyway.
