### ISSUE TITLE
How do I use the same logger in multiple dynamic libraries?

### ISSUE THREAD

**Issue by Mangomm** [gabime/spdlog#2950]
My program has many dynamic libraries. How do I share a spdlog logger among these dynamic libraries?

**Comment by tt4g** [comment]
See: https://github.com/gabime/spdlog/wiki/How-to-use-spdlog-in-DLLs

**Comment by artemyv** [comment]
What we do in our project:
There is one dll that contains logger registry and configures log levels and sinks for all loggers (based on toml file for exe)
All other binaries - instead of creating loggers by themselves - use API exported from this one dll to access the loggers from its registry (by name)

**Comment by tt4g** [comment]
@artemyv Are you working with @Mangomm on the same project as you are developing?
If not, please open a new issue.

> What we do in our project:
> There is one dll that contains logger registry and configures log levels and sinks for all loggers (based on toml file for exe)
All other binaries - instead of creating loggers by themselves - use API exported from this one dll to access the loggers from its registry (by name)

What does this post mean?
If you describe what you are having trouble with, I can answer you, but I don't know what you can't do from this comment, so I can't answer you either.

**Comment by tt4g** [comment]
> > What we do in our project:
> > There is one dll that contains logger registry and configures log levels and sinks for all loggers (based on toml file for exe)
> > All other binaries - instead of creating loggers by themselves - use API exported from this one dll to access the loggers from its registry (by name)
> 
> What does this post mean? If you describe what you are having trouble with, I can answer you, but I don't know what you can't do from this comment, so I can't answer you either.

I realized my mistake. This @artemyv's comment is in response to this issue.
I was stupid, sorry @artemyv.
