### ISSUE TITLE
LOG ERROR rotating_file_sink: failed renaming logs/master_log.txt to logs/master_log.1.txt: Improper link

### ISSUE THREAD

**Issue by simonevallifuoco** [gabime/spdlog#2961]
Any idea why I am getting this error when a rotation should happen?

**Comment by tt4g** [comment]
Since you did not provide any information about OS, I don't know where the error message came from.

**Comment by simonevallifuoco** [comment]
@tt4g I am working on QNX OS

**Comment by tt4g** [comment]
The error message "Improper link" was probably returned due to system error `EXDEV`: https://github.com/vocho/openqnx/blob/cc95df3543a1c481d4f8ad387e29f0d1ff0c87fe/trunk/lib/c/unix/sys_err.c#L43

This almost always occurs when trying to move files between different devices.
See: [mv on ext4 is doing copy\-and\-remove instead of inode relocation \- Unix & Linux Stack Exchange](https://unix.stackexchange.com/questions/694188/mv-on-ext4-is-doing-copy-and-remove-instead-of-inode-relocation)

Maybe the log file is a symbolic link?

**Comment by simonevallifuoco** [comment]
Maybe the problem could be I am writing log files in tmp folder. I don't know... Also rotation works fine on a QNX virtual machine, but it's returning this error when running on board

**Comment by tt4g** [comment]
Since this is a system call error, I think you should ask questions in the QNX forum to determine the cause of the problem.

**Comment by simonevallifuoco** [comment]
Sure, thank you @tt4g
