### ISSUE TITLE
file logging not working when application is running as systemd service

### ISSUE THREAD

**Issue by audi0615** [gabime/spdlog#2996]
Hi.

when running my application in linux console, file logging is working fine.
but application started as systemd service does not create any log file.

is it something to do with file permission? i would appreciate your help.

**Comment by tt4g** [comment]
Of course, permissions are affected.
However, the process should be run by `root` unless a run user is specified in the `Service` section in the Systemd unit file (`.service`).

**Comment by audi0615** [comment]
Thanks for your comment. The service is running as root. could you please tell me how to set file permission?

**Comment by tt4g** [comment]
If you are running as root, file permissions are not relevant.

Does your application perform logger flushes periodically?
If not, there may be a problem with the way your application terminates.

For example, if `KillSignal` is not set in the Systemd unit definition, the default is to terminate the process by `SIGTERM`.
The C++ cleanup process should not be executed from the default `SIGTERM` handler, so it is not surprising that the files are not flushed.

**Comment by audi0615** [comment]
Thanks for your comment. 

My application prints out almost 20 log messages every a few seconds. 
so It doesn't seem to be a flushing problem because when my app is started in a console, a file is generated and logged without issue. 

Perhaps spdlog does not support file logging in a systemd service. 

Has anyone else experienced the same issue?

**Comment by tt4g** [comment]
> Perhaps spdlog does not support file logging in a systemd service.

I don't think so; Systemd is the parent process of everything, SSH, etc. is run under Systemd's control.
The problem of different behavior between the terminal and Systemd is usually caused by the configuration of the Systemd unit file.

I don't know how much you know about Systemd, but are you aware that services started from Systemd run in a different environment than the shell (such as `bash` and `ksh`)?
For example, environment variables loaded from the shell, such as `.bash_profile`, will not be applied. Applications that depend on environment variables will change behavior if the environment variable is not specified in the `Environment=` of the Systemd unit file.
You should also check what is set `WorkingDir=` and `PrivateTmp=`.

**Comment by audi0615** [comment]
You were correct tt4g. It was working directory problem.

after changing the file name to full path, it works fine now.
`auto file_sink = make_shared<spdlog::sinks::rotating_file_sink_mt>("/usr/bin/myapp/log.txt", max_size, max_files);`

Thank you so much
