### ISSUE TITLE
I use spdlog library in my dll project and create console by calling AllocConsole.

### ISSUE THREAD

**Issue by kamenomi-dev** [gabime/spdlog#2998]
> I use machine translation to describe the problem. I'm sorry that there may be some problems. ;_;

spdlog version  : latest
c++ std version : ISO C++20
C   std version : ISO C17(2018)

Specific code initialization implementation:
```
if (dwReason == DLL_PROCESS_ATTACH) {
  DisableThreadLibraryCalls(hInstance);

  // debug
  AllocConsole();
  freopen_s((FILE**)stdout, "CONOUT$", "w+t", stdout);

  /* Sadness, it all doesn't work! */

  // spdlog::initialize_logger(std::make_shared<spdlog::logger>("Project", std::make_shared<spdlog::sinks::wincolor_stdout_sink_mt>()));
  // spdlog::default_logger_raw()->sinks().push_back(std::make_shared<spdlog::sinks::wincolor_stdout_sink_mt>());

  // spdlog::set_default_logger(spdlog::create<spdlog::sinks::wincolor_stdout_sink_mt>(""));
  // std::this_thread::sleep_for(std::chrono::milliseconds(25));
  spdlog::default_logger_raw()->flush();

  thLoop = std::thread([hInstance] { ThreadLoop(hInstance); });
  if (thLoop.joinable()) {
    thLoop.detach();

  };
};
```

I tried the solutions given from #2621  and #1629  issues, but this has a chance of not working, why.
This question comes from my repo: https://github.com/Kamen-akio/EmbeddingMusic

**Comment by tt4g** [comment]
Since the default logger is initialized at application startup, an invalid STDOUT handle is expected to be assigned.
Operations on invalid handles will result in undefined behavior, so log operations will always fail unless the default logger is replaced.

> [!Tip]
> With any luck, the error message will be reported to the error handler: https://github.com/gabime/spdlog/wiki/Error-handling

Therefore, all of the following code that do not remove the invalid STDOUT handler from the default logger will not work as expected.

```cpp
  // spdlog::default_logger_raw()->sinks().push_back(std::make_shared<spdlog::sinks::wincolor_stdout_sink_mt>());
```

The following code replaces the default logger, but should have reported a name conflict error from the spdlog global registry because it conflicts with the spdlog default logger name `""`.

```
spdlog::set_default_logger(spdlog::create<spdlog::sinks::wincolor_stdout_sink_mt>(""));
```

The default logger should be replaced by the following code

```diff
   AllocConsole();
   freopen_s((FILE**)stdout, "CONOUT$", "w+t", stdout);

+  auto new_default_logger = std::make_shared<spdlog::logger>("", std::make_shared<spdlog::sinks::wincolor_stdout_sink_mt>());
+  spdlog::set_default_logger(new_default_logger);

  spdlog::default_logger_raw()->flush();
```

**Comment by kamenomi-dev** [comment]
Nope, it doesn't work. I tried to add an error handle to find the reason, but it did not have any msg for me. ;_;

**Comment by tt4g** [comment]
The source code you provided is missing important information.
The source code for the issue was written in `DllMain()`.

https://github.com/Kamen-akio/EmbeddingMusic/blob/46ef52ac58accdd74fb82abeae07640322b48427/dllmain.cpp#L36-L70

Since `DllMain()` is there to initialize the resources and memory used by the shared library, spdlog will not work: #1530, #2304
Probably `AllocConsole()` is not working properly either.
This is not a problem with spdlog, but with the design of your project.

**Comment by kamenomi-dev** [comment]
I see. Refer to this https://github.com/gabime/spdlog/wiki/How-to-use-spdlog-in-DLLs? Do I need to wrap the spdlog library myself to make it run normally?

**Comment by tt4g** [comment]
If you shared the spdlog logger with a shared library and application, then yes.

**Comment by kamenomi-dev** [comment]
fine, but printf_s in the standard library API can output. I want to know why. 😞

**Comment by tt4g** [comment]
spdlog does not work properly because it uses atomic operations and threads but the resources to enable them to be used are not initialized in `DllMain()`.

**Comment by kamenomi-dev** [comment]
thanks a lot.
