### ISSUE TITLE
Trying to set different log levels on different sinks... but it's not working

### ISSUE THREAD

**Issue by htartisan** [gabime/spdlog#2999]
I have used SpdLog to create 2 different log "sinks":
- The 1st sink outputs to the console.  I want this sink to filter out everything but error and waning messages.
- The 2nd sink outputs to a file.  I want this sink to filter out only "trace" messages, and display all other messages.

I created the console log sink (console_logger) as a "spdlog::sinks::stdout_color_sink_mt", and set the loglevel for that sink to "warning".
I created a file log sink (file_logger) as a "spdlog::sinks::rotating_file_sink_mt", and set the loglevel for that sync to "debug".
I then created a main logger of type "spdlog::logger", and  then added the 2 log sinks to the main logger as follows:
  main_logger->sinks().push_back(console_logger);
  main_logger->sinks().push_back(file_logger); 
Lastly I made the main logger the default logger, as follows: 
  spdlog::set_default_logger(main_logger); 

The problem is that both logs (console and file) are displaying ONLY the log messages for the log level I set for the "console_logger".

How can I have 2 seperate log sinks with 2 different log levels???

**Comment by tt4g** [comment]
Since no source code is provided to reproduce the problem, I am not sure what is going on.

Just looking at what is written in the issue, it does not call `spdlog::logger::set_level()`.
Log messages below the debug level will not be passed to sink unless you call `spdlog::logger::set_level()`(by default `spdlog::level::info`) to change the logger level.

https://github.com/gabime/spdlog/blob/696db97f672e9082e50e50af315d0f4234c82397/include/spdlog/logger.h#L310
