### ISSUE TITLE
catch program exception

### ISSUE THREAD

**Issue by Crusoekid** [gabime/spdlog#3018]
Excuse me, how can I use the spdlog to capture the program crash message and report the error to the log. In addition, if the program exits abnormally, it will lead to the loss of information that is not flushed to the log, how to avoid this situation

**Comment by DominikGrabiec** [comment]
Capturing program crashes is generally platform specific, so more information is needed there.

As for flushing the log when something like a crash occurs, I've put in `spdlog::default_logger()->flush();` in my `ASSERT` handler code which seems to do the trick.
If you have more than the default logger you'd want to flush it in the same way in the same place as well.

**Comment by Crusoekid** [comment]
Do you mean, the code now writes all the logs in the code by default when the program crashes? When I tested with 0.13.0, the logs weren't written.
my test code is 
`auto m_logger = spdlog::daily_logger_mt<spdlog::async_factory>("daily_logger", "logs/daily.txt", 0, 0);
m_logger->info("test daily info231231{}", 1);
m_logger->error("test daily error2212312314");
m_logger->enable_backtrace(32);
for (int i = 0; i < 1; i++)
{
    m_logger->debug("Backtrace message {}", i); // not logged yet..
}
int *a;
a[0] = 1;`

**Comment by tt4g** [comment]
What is a program crash message?
If it means `std::exception`, please handle it by `try`-`catch` and get `std::exception::what()`.

If that means a fatal error, such as an access violation, you must first register a signal handler and devise a way to continue the program after a crash.
However, there is no guarantee in the C++ specification that the program will continue to work properly after the application crashes.
See also: #1607

**Comment by DominikGrabiec** [comment]
@Crusoekid  I apologise that I didn't make myself clear in the first statement. You still need to implement a crash handler yourself to handle crashes in your program. This is platform specific and will differ if you're using Linux, Mac, or Windows. I can't help here because I haven't implemented one yet for my own applications as I'm running them within the debugger almost exclusively.

What I did say was that in whatever crash handler you implement, you can call the default logger flush function to write out all the log messages at that point. In my case I added this to my assert handler, and in future I will add this to any crash handlers that I implement.

**Comment by Crusoekid** [comment]
Thank you for your reply, because when I was looking at the glog, there is a related function 'google::InstallFailureSignalHandler()', I would like to ask if spdlog has a similar function, and I will capture the crash signal myself to output the log. Thanks again

**Comment by tt4g** [comment]
> I would like to ask if spdlog has a similar function

Not supported yet.
