### ISSUE TITLE
fatal error: spdlog/cfg/env.h: No such file or directory

### ISSUE THREAD

**Issue by greatsharma** [gabime/spdlog#3030]
I am getting following error while including "spdlog/cfg/env.h" and "spdlog/fmt/ranges.h"

`fatal error: spdlog/cfg/env.h: No such file or directory`

I am installing like this in dockerfile
`RUN apt install -y libspdlog-dev`

Cmakelist:
`find_package (spdlog REQUIRED)`
`target_link_libraries(${PROJECT_NAME} PRIVATE spdlog::spdlog_header_only)`

**Comment by greatsharma** [comment]
Same for  "spdlog/fmt/ranges.h"

`fatal error: spdlog/fmt/ranges.h: No such file or directory
    8 | #include "spdlog/fmt/ranges.h"`

**Comment by tt4g** [comment]
`spdlog::spdlog_header_only' is a CMake target for header-only use of spdlog.
It is not expected to work properly since it is usually a pre-built library that is installed by `apt`.
You should use `spdlog::spdlog'.

And please ask the community of the distribution you are using how to use the `libspdlog-dev` package, as the `apt` package is not maintained here.

**Comment by greatsharma** [comment]
@tt4g thanks for the prompt reply. But now I am facing issue with installation.

I am no more using `libspdlog-dev` but installing from source.

Dockerfile:
`RUN git clone https://github.com/gabime/spdlog.git && cd spdlog && mkdir build && cd build && cmake .. && make -j
`

Cmakelist:
`target_link_libraries(${PROJECT_NAME} PRIVATE spdlog::spdlog)`

With the above settings I am getting below error:
```
#0 0.559 CMake Error at src/CMakeLists.txt:80 (target_link_libraries):
#0 0.559   Target "dtApp" links to:
#0 0.559 
#0 0.559     spdlog::spdlog
#0 0.559 
#0 0.559   but the target was not found.  Possible reasons include:
#0 0.559 
#0 0.559     * There is a typo in the target name.
#0 0.559     * A find_package call is missing for an IMPORTED target.
#0 0.559     * An ALIAS target is missing.
#0 0.559 
#0 0.559 
#0 0.559 
#0 0.559 -- Generating done
#0 0.560 CMake Generate step failed.  Build files cannot be regenerated correctly.
```


I even tried with this: 
`find_package (spdlog REQUIRED)` But got below error

```
#0 0.567 CMake Error at src/CMakeLists.txt:28 (find_package):
#0 0.567   By not providing "Findspdlog.cmake" in CMAKE_MODULE_PATH this project has
#0 0.567   asked CMake to find a package configuration file provided by "spdlog", but
#0 0.567   CMake did not find one.
#0 0.567 
#0 0.567   Could not find a package configuration file provided by "spdlog" with any
#0 0.567   of the following names:
#0 0.567 
#0 0.567     spdlogConfig.cmake
#0 0.567     spdlog-config.cmake
#0 0.567 
#0 0.567   Add the installation prefix of "spdlog" to CMAKE_PREFIX_PATH or set
#0 0.567   "spdlog_DIR" to a directory containing one of the above files.  If "spdlog"
#0 0.567   provides a separate development package or SDK, be sure it has been
#0 0.567   installed.
#0 0.567 
#0 0.567 
#0 0.567 -- Configuring incomplete, errors occurred!
```


I even copied the spdlog's include [folder](https://github.com/gabime/spdlog/tree/v1.x/include/spdlog) in my project's include folder and then in cmakelist added 
`target_include_directories(${PROJECT_NAME}  PRIVATE  ../include/spdlog/)`
 
 BUT I am still getting same error.
 
 Please help me in the installation process

**Comment by tt4g** [comment]
CMake cannot find spdlog because it was not installed by `make install` command.

```diff
-RUN git clone https://github.com/gabime/spdlog.git && cd spdlog && mkdir build && cd build && cmake .. && make -j
+RUN git clone https://github.com/gabime/spdlog.git && cd spdlog && mkdir build && cd build && cmake .. && make -j && make install
```

`find_package()` command searches for packages from the path defined in the `CMAKE_MODULE_PATH` variable.
The path in the `CMAKE_MODULE_PATH` variable is the system package installation path by default.
See: https://cmake.org/cmake/help/v3.29/command/find_package.html

If you want to use `find_package(spdlog)` without installing spdlog on your machine,
use the `add_subdirectory()` command to import  spdlog project as part of your project.

See: https://cmake.org/cmake/help/v3.29/command/add_subdirectory.html
See also: https://github.com/gabime/spdlog/issues/2758#issuecomment-1585863541

---

> I even copied the spdlog's include folder in my project's include folder and then in cmakelist added
> `target_include_directories(${PROJECT_NAME}  PRIVATE  ../include/spdlog/)`

`target_include_directories()` command is for adding include paths for your project and does not affect `find_package()`.
See: https://cmake.org/cmake/help/v3.29/command/target_include_directories.html

There will be spdlog header files installed on your machine and  spdlog header files in your project.
It will be difficult to tell which header file is being used.
You should not do this if there is no reason to do so.

**Comment by greatsharma** [comment]
@tt4g thanks, it worked. I have one more issue,

I am running following code but the multi-dimensional vectors are not getting printed on console.
```  
    std::vector<std::vector<std::vector<std::string>>> assignment_mapping;
    std::vector<std::vector<int>> feasible_fullJourney_paths;
    
    generate_mapping(camCfg_path.c_str(), assignment_mapping, feasible_fullJourney_paths))
    
    spdlog::info("Journey paths: ", feasible_fullJourney_paths);
    spdlog::info("Assignment mapping: ", assignment_mapping);
```

The logs look like below, everything is logged except `feasible_fullJourney_paths` and  `assignment_mapping`.

```
[2024-03-06 11:10:29.435] [info] Source type: zmq
[2024-03-06 11:10:29.435] [info] Cam count list: [[2, 2], [1, 1]]
[2024-03-06 11:10:29.435] [info] Journey paths: 
[2024-03-06 11:10:29.435] [info] Assignment mapping: 
[2024-03-06 11:10:29.435] [info] Total stations: 2
[2024-03-06 11:10:29.435] [info] Station lane count: [2, 2]
```

You can see that `Cam count list` is printed which is also 2-D vector but it is defined in the same file, whereas  `feasible_fullJourney_paths` and  `assignment_mapping` are populated inside `generate_mapping()` function which is in some other file. I don't know whether this is causing this issue.

When I manually printing on console using `std::cout` then array  values are printed on screen so the array is correctly populated for sure.

Also I am getting similar issue in below code as well,
```
    spdlog::info("Threshold: ", std::any_cast<float>(dt_model_config_map["Assignment_Similarity_Threshold"]));
```
In the output no float value is printed, output-
`[2024-03-06 11:10:29.441] [info] Threshold:`

**Comment by tt4g** [comment]
Use `{}` to print additional arguments in the log message in spdlog.
This is implemented by fmt.
fmt API: https://fmt.dev/9.1.0/

Example:

```cpp
spdlog::info("one {}", 1); // one 1
```

**Comment by greatsharma** [comment]
Thank you; that was a mistake on my part.
