### ISSUE TITLE
Compile-time check bypassed due to overloading.

### ISSUE THREAD

**Issue by Luffbee** [gabime/spdlog#3056]
``` c++
#include "spdlog/spdlog.h"
#include "fmt/format.h"

int main() {
    fmt::print("{}\n", 1);
    SPDLOG_INFO("{}", 2);
    // fmt::print("{}\n"); // compile error
    SPDLOG_INFO("{}");
    return 0;
}
```

see code here: [https://godbolt.org/z/9eWfb83PW](https://godbolt.org/z/9eWfb83PW)

The `SPDLOG_INFO("{}")` bypassed the compile-time check unexpectedly.
The reason is that it resolves to the following overload:
https://github.com/gabime/spdlog/blob/62302019babd8fdf63c1c6dc4c9faa48d441a7f0/include/spdlog/logger.h#L115

Is this the desired behavior? It seems this overload can be removed, as there is another overload that can cover the use cases of it:
https://github.com/gabime/spdlog/blob/62302019babd8fdf63c1c6dc4c9faa48d441a7f0/include/spdlog/logger.h#L93-L97

**Comment by tt4g** [comment]
Thank you for reporting.
Could you send PR?

**Comment by gabime** [comment]
This is kind of expected. If there are no args spdlog does’t treat the passed string as format string for performance reasons, and bypass the fmt formatting.

**Comment by tt4g** [comment]
@gabime Should I add a section to the FAQ page (https://github.com/gabime/spdlog/wiki/0.-FAQ) about this design?

**Comment by Luffbee** [comment]
> Is this the desired behavior? It seems this overload can be removed, as there is another overload that can cover the use cases of it:
> 
> https://github.com/gabime/spdlog/blob/62302019babd8fdf63c1c6dc4c9faa48d441a7f0/include/spdlog/logger.h#L93-L97

Firstly, my apology, I misunderstood the above overload, it is used to handle cases like `SPDLOG_INFO(type_can_fmt{})`.
The `std::string_view` fits the requirement of  `is_convertible_to_any_format_string`.

I tried to fix the problem by adding an overload of `logger::log_()`, which will bypass the fmt formatting if there are no arguments, like the following:
``` c++
    ...
    void log_(source_loc loc, level::level_enum lvl, string_view_t msg) {
        log_no_fmt_(loc, lvl, msg); 
    }
    // copy from the `log(..., string_view_t)`
    void log_no_fmt_(source_loc loc, level::level_enum lvl, string_view_t msg) {
        bool log_enabled = should_log(lvl);
        bool traceback_enabled = tracer_.enabled();
        if (!log_enabled && !traceback_enabled) {
            return;
        }

        details::log_msg log_msg(loc, name_, lvl, msg);
        log_it_(log_msg, log_enabled, traceback_enabled);
    }
```

However, it fails to compile with many errors of "error: the value of ‘msg’ is not usable in a constant expression", which is caused by using non-literal strings, e.g.:
``` c++
// bench/latency.cpp
void bench_c_string(benchmark::State &state, std::shared_ptr<spdlog::logger> logger) {
    const char *msg =
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum pharetra metus cursus "
        "lacus placerat congue. Nulla egestas, mauris a tincidunt tempus, enim lectus volutpat mi, "
        "eu consequat sem "
        "libero nec massa. In dapibus ipsum a diam rhoncus gravida. Etiam non dapibus eros. Donec "
        "fringilla dui sed "
        "augue pretium, nec scelerisque est maximus. Nullam convallis, sem nec blandit maximus, "
        "nisi turpis ornare "
        "nisl, sit amet volutpat neque massa eu odio. Maecenas malesuada quam ex, posuere congue "
        "nibh turpis duis.";

    for (auto _ : state) {
        logger->info(msg);
    }
}
```
So the problem now is how to correctly detect non-literal strings and dispatch them to `log_no_fmt_`?
Is there any effort to solve this problem before?

**Comment by tt4g** [comment]
Use `fmt::runtime()` for non-literal characters: #2786

---

It is returns runtime object `basic_runtime<char>` in fmt 9.1.0 (https://fmt.dev/9.1.0/api.html#_CPPv4N3fmt7runtimeE11string_view).

Note `fmt::runtime()` returns `runtime_format_string<>` fmt 10 and above (https://fmt.dev/10.0.0/api.html#_CPPv4N3fmt7runtimeE11string_view).

The template function `log(source_loc loc, level::level_enum lvl, const T &msg)` does not fit because `is_convertible_to_any_format_string<const T &>::value == true` when using `fmt::runtime()`.

https://github.com/gabime/spdlog/blob/62302019babd8fdf63c1c6dc4c9faa48d441a7f0/include/spdlog/common.h#L219-L223

https://github.com/gabime/spdlog/blob/62302019babd8fdf63c1c6dc4c9faa48d441a7f0/include/spdlog/common.h#L186-L201

**Comment by tt4g** [comment]
Looking at the logging template function signatures, it seems that it would be very difficult to change the current implementation.

The only way to make the compile time check work with just a literal string would be to directly call `log(source_loc loc, level::level_enum lvl, format_string_t<Args...> fmt, Args &&...args)` that calls `log_(source_loc loc, level::level_enum lvl, string_view_t fmt, Args &&...args)`.

https://github.com/gabime/spdlog/blob/62302019babd8fdf63c1c6dc4c9faa48d441a7f0/include/spdlog/logger.h#L78-L81

Since `info(const T &msg)` cannot call `log(source_loc loc, level::level_enum lvl, format_string_t<Args...> fmt, Args &&...args)`, try calling `log(source_loc loc, level::level_enum lvl, format_string_t<Args...> fmt, Args &&...args)` directly.

https://github.com/gabime/spdlog/blob/62302019babd8fdf63c1c6dc4c9faa48d441a7f0/include/spdlog/logger.h#L241-L244

**Comment by Luffbee** [comment]
> Since `info(const T &msg)` cannot call `log(source_loc loc, level::level_enum lvl, format_string_t<Args...> fmt, Args &&...args)`, try calling `log(source_loc loc, level::level_enum lvl, format_string_t<Args...> fmt, Args &&...args)` directly.
> 
> https://github.com/gabime/spdlog/blob/62302019babd8fdf63c1c6dc4c9faa48d441a7f0/include/spdlog/logger.h#L241-L244

There is another similar overload can achieve the compile-time check
https://github.com/gabime/spdlog/blob/62302019babd8fdf63c1c6dc4c9faa48d441a7f0/include/spdlog/logger.h#L138-L141

The problem is `info("{}")` will resolve to the `info(const T &msg)` overload.
Therefore, I tried to add the `!is_convertible_to_any_format_string` requirement to `info(const T &msg)`, which makes the `info("{}")` resolve to `info(format_string_t<Args...> fmt, Args &&...args)`, and compile-time check works for `info("{}")`.

``` c++
template <class T, 
           typename std::enable_if<!is_convertible_to_any_format_string<const T &>::value, 
                                   int>::type = 0> 
void info(const T &msg) { 
     log(level::info, msg); 
} 
```

However, this modification makes non-literal strings resolve to the compile-time check overload, too.
``` c++
std::string s = fmt::format("{}", 123);
// without modification: resolves to `info(const T&msg)`, compile ok
// with modification: resolves to `info(format_string_t<Args...> fmt, Args &&...args)`, compile fail (c++20) due to `s` is not constexpr
spdlog::info(s);
```

The problem here is there is no way to do different dispatch for constexpr argument and non-constexpr argument before c++23.
With c++23, the `if consteval` feature seems can help in this problem.

**Comment by tt4g** [comment]
Yes, this problem cannot be avoided because `if consteval` is not available in C++11.
If you really want to do a compile-time check when passing only string, you will have to call `log(source_loc loc, level::level_enum lvl, format_string_t<Args...> fmt, Args &&...args)`.

**Comment by gabime** [comment]
> @gabime Should I add a section to the FAQ page (https://github.com/gabime/spdlog/wiki/0.-FAQ) about this design?

If this is actually a FAQ then yes please

**Comment by tt4g** [comment]
> If this is actually a FAQ then yes please

Added: https://github.com/gabime/spdlog/wiki/0.-FAQ#format-string-compile-time-check-does-not-work-when-there-are-no-args
