### ISSUE TITLE
'parse': is not a member of 'fmt::v9::detail::fallback_formatter<std::basic_ostringstream<char,std::char_traits<char>,std::allocator<char>>,Char,void>'

### ISSUE THREAD

**Issue by m96fa-1** [gabime/spdlog#3063]
When I try to build my project I get the following error:
```
path\to\core.h(2746,12): error C2039: 'parse': is not a member of 'fmt::v9::detail::fallback_formatter<std::basic_ostringstream<char,std::char_traits<char>,std::allocator<char>>,Char,void>'
```
I tried to include sstream header file thinking it might be because it is not included but it didn't work, I'm using VS2022 with C++20 and yes, I tried using older versions but nothing seems to work!

**Comment by tt4g** [comment]
It is an fmt library error message and should be reported in [fmt repository](https://github.com/fmtlib/fmt).

I don't know for sure since you didn't provide the source code for your project that is causing the error, but I suspect that you are formatting a custom class that fmt does not support formatting for.

**Comment by tt4g** [comment]
See "Formatting User-Defined Types" section: https://fmt.dev/9.1.0/api.html#formatting-user-defined-types
