### ISSUE TITLE
Does SPDLOG support conditional logging?

### ISSUE THREAD

**Issue by 0KABE** [gabime/spdlog#3089]
I found an issue described about the conditional logging which has been merged into the master branch, but I could not find it in the v1.13.0 version. Was it deleted for some reason?

Reference: https://github.com/gabime/spdlog/pull/460

**Comment by tt4g** [comment]
Removed by dcc7b347caadca6d191c40c8ae59a3320ab277ac ([v0.16.0](https://github.com/gabime/spdlog/releases/tag/v0.16.0))

**Comment by iosiddhu** [comment]
do there is no conditional logging feature in the library ? I have already implemented library in the project and i do not want to download older versions with conditional logging.

**Comment by tt4g** [comment]
> do there is no conditional logging feature in the library ?

Not supported.

**Comment by tt4g** [comment]
Wouldn't this feature be the same as moving the logging API call into an `if` statement?

**Comment by iosiddhu** [comment]
cool man! reason give was it was redundant an confusing. can you explain me the reason if possible Because now I do have to download the previous version with conditional I just want to make sure it wont effect my create sinks and all. should not. can you give me some idea. I am short on time or I would have looked for alternatives.

**Comment by iosiddhu** [comment]
> Wouldn't this feature be the same as moving the logging API call into an `if` statement?

got it let me see if can implement my own conditional in it.
