### ISSUE TITLE
Not work stderr output

### ISSUE THREAD

**Issue by khromenokroman** [gabime/spdlog#3095]
The program runs through systemd, while everything is written to the log, but it is not output to the console in the formatting that I specify, and is not highlighted in color, is this how it should be?

code:
```
auto console = std::make_shared<spdlog::sinks::stderr_color_sink_st>();
    auto syslog = std::make_shared<spdlog::sinks::systemd_sink_st>("test", false);

    std::vector<spdlog::sink_ptr> sinks{console, syslog};
    auto logger = std::make_shared<spdlog::logger>("test", sinks.begin(), sinks.end());

    console->set_pattern("[%n] %^%v%$");

    syslog->set_level(spdlog::level::trace);
    logger->set_level(spdlog::level::trace);

    console->set_level(spdlog::level::trace);
    logger->log(spdlog::level::critical, "Base logger create", "test");
```

console:
```
➜  user 2024 May 24 22:59:22 ngfw Base logger create 
```

**Comment by tt4g** [comment]
It says that systemd_sink uses `sd_journal_send()`.
The format you specify is not respected because `sd_journal_send()` needs to pass a string in a defined format.
And `sd_journal_send()` is not a console, so colors are ignored.

https://github.com/gabime/spdlog/blob/c3aed4b68373955e1cc94307683d44dca1515d2b/include/spdlog/sinks/systemd_sink.h#L20-L24

If you want to output colors with ANSI escapes, use color_sink (stdout_color_sink or stderr_color_sink).
However, the color may be ignored depending on the output destination specified `StandardOutput` and `StandardError` in the Systemd unit file.
