### ISSUE TITLE
Log statements written in wrong order

### ISSUE THREAD

**Issue by ruipacheco** [gabime/spdlog#376]
I'm using spdlog on a library where performance is sensitive. I'm using a [multithreaded](https://github.com/gabime/spdlog/issues/371) sink because I don't want to block the main thread of my app to write log statements (at least that's how I think mt sinks are meant to be used).

The problem is that upon analysing the log file, log statements are written in the wrong order. I have a single method with warn() and debug() calls very close to each other and called in this order but on reading the generated log file I noticed that the debug() statement is printed before the warn().

How can I get statements printed in the right order without blocking the main execution thread of my app?

An example:

```
[2017-03-01 15:12:14.545] [Connection] [info] Creating connection object.
[2017-03-01 15:12:14.545] [Connection] [info] Application name not set, using XXX.
[2017-03-01 15:12:16.860] [Connection] [warning] Reading password file.
[2017-03-01 15:12:16.860] [Connection] [debug] HOME set to '/Users/ruipacheco'.
...
```

The last 2 statements should be swapped.

**Comment by gabime** [comment]
Is the same thread calls debug+info? because if not it is expected of course

**Comment by ruipacheco** [comment]
My code is single threaded, the log is configured as in the link above.

**Comment by gabime** [comment]
Strange... Could be related to flushing ? Can you post the code?

**Comment by ruipacheco** [comment]
Code is proprietary but basically I call debug() as the first line of code in a method and a warn() inside a condition no more than 5 lines of code after that. The code itself walks a byte array so nothing too fancy happening there.

I don't call flush() at all. How often/under which conditions should I do it?

**Comment by gabime** [comment]
Which sinks are you using?

**Comment by ruipacheco** [comment]
`auto daily_sink = std::make_shared<spdlog::sinks::daily_file_sink_mt>(base_path, 23, 59);`

You can check the way I'm setting up my logger on the link in my original post. It's a discussion we had a few days ago.

**Comment by gabime** [comment]
If i remember correctly your code use several async loggers? So the debug() and info() come from different loggers maybe?

**Comment by ruipacheco** [comment]
My application has a root class where I use the method we discussed in the link above to create a logger. Then I have a few methods where I create other loggers using the sink, so I have something like 3 or 4 logger, 5 tops.

In this case the statements are written by the same logger.

I really just need to log without blocking the main thread. What is the best way to do this?

**Comment by gabime** [comment]
I've run out of ideas. Could you post some code that reproduces this?

**Comment by ruipacheco** [comment]
Ugh. I'm going to close this for now because I won't have time to write a minimal sample for the new few months. But this is something I'm aware of so I'll reopen it when I can.

**Comment by gabime** [comment]
Ok, thanks for reporting

**Comment by iamantony** [comment]
Do you use `logger::flush_on( level )` in your code? Try to set level to `trace`.

As a workaround I could suggest edit sources and forcibly call flush() at the end of the function `daily_file_sink::_sink_it( msg )`.

**Comment by gvaidya** [comment]
Hi, I have a similar issue with log order getting switched. I am logging to a single sink from multiple async loggers. Sometimes statements which were sent earlier from one logger get logged after other statements which were sent later from a different logger. Even when the statements are switched, timestamps are correct. 
My guess is this can be happening because of queue flushing from one logger first and another later which causes statements to switch order. 

In the implementation do sinks have a queue which takes all logged statements or each logger has their own queue which is then sent to the sink at the time of flush?

**Comment by gabime** [comment]
Each async logger object has its own queue..

**Comment by linrongbin16** [comment]
Hi, I'm new to spdlog, Is `spdlog::basic_logger_mt` async or sync ?

**Comment by tt4g** [comment]
@linrongbin16 The logger determines sync / async.
Sync imsplementation `spdlog::logger`, Async implementation `spdlog::async_logger`


The `st` and` mt` at the end of the Sink's name determine the presence or absence of mutex protection.
`mt` is protected against multi-thread conflicts. `st` has no protection.

**Comment by linrongbin16** [comment]
@tt4g so it must be sync and multi-thread safe, since `spdlog::basic_logger_mt` returns `std::shared_ptr<spdlog::logger>`

**Comment by andrea1bergamini** [comment]
I can confirm the issue is still there with latest version.
I have a multithread application that outputs on a rotating log file and console:

```
static std::shared_ptr<spdlog::details::thread_pool> _tp = std::make_shared<spdlog::details::thread_pool>(51200, 4);

try
	{		
		spdlog::drop(m_logID.toStdString().c_str());

		auto logFilePath = m_logFilePath + m_logFileName;

		auto dist_sink = std::make_shared<spdlog::sinks::dist_sink_mt>();

#if defined _MSC_VER && defined QT_DEBUG
		dist_sink->add_sink(std::make_shared<spdlog::sinks::msvc_sink_mt>());
#endif // _MSC_VER

#ifdef Q_OS_ANDROID
        dist_sink->add_sink(std::make_shared<spdlog::sinks::android_sink_mt>());
#endif // Q_OS_ANDROID

		dist_sink->add_sink(std::make_shared<spdlog::sinks::stdout_color_sink_mt>());
		dist_sink->add_sink(std::make_shared<spdlog::sinks::rotating_file_sink_mt>(logFilePath.toStdString().c_str(), m_maxLogFileSize, m_maxNLogFile));
		
		auto logger = std::make_shared<spdlog::async_logger>(m_logID.toStdString().c_str(), dist_sink, /*spdlog::thread_pool()*/_tp, spdlog::async_overflow_policy::overrun_oldest);
		spdlog::register_logger(logger);

		spdlog::set_level(spdlog::level::trace);
		spdlog::set_pattern("%^[%Y-%m-%d %H:%M:%S.%e] [%L] %v%$");
		//spdlog::flush_every(std::chrono::seconds(1));
	}
	catch (const spdlog::spdlog_ex &ex)
	{
		qDebug() << "Log init failed: " << ex.what();
		return false;
	}
	return true;
```

Even if log statements come from a single thread, they're not sorted in the way they're output.
I can confirm by prepending a counter for each log operation.

The only workaround I've found is to create a custom thread pool and reduce the pool to 1 thread instead of 4 as the code above. So, my thinking is that the thread pool pick the messages from the queue without taking care of the order. 
I can understand the case when log messages come from multiple threads, but I can confirm they come from a single thread, so even if output it's async, the order should be kept (with any thread pool).
