### ISSUE TITLE
ANSI colors - Windows

### ISSUE THREAD

**Issue by H1X4Dev** [gabime/spdlog#398]
ANSI colors can be enabled on windows by setting console modes.
```
		HANDLE hOut = GetStdHandle(STD_OUTPUT_HANDLE);
		if (hOut != INVALID_HANDLE_VALUE)
		{
			DWORD dwMode = 0;
			GetConsoleMode(hOut, &dwMode);

			dwMode |= 0x0004;
			SetConsoleMode(hOut, dwMode);
		}
```
and also setting \033 to \x1b for acquiring color coded output.

Though I'm unsure how to handle it with non-msvc compilers

**Comment by agauniyal** [comment]
@russkiemafia I've something you might look into - https://github.com/agauniyal/rang/

**Comment by SteeleDynamics** [comment]
I have built the project using MinGW-64 and was able to see the ANSI colors in the terminal/command prompt (using [ansicon](https://github.com/adoxa/ansicon)) with example.exe. I have done nothing special otherwise.

**Comment by H1X4Dev** [comment]
That wasn't my point though.
Windows 8.1 and up supports NATIVE > ASCII < colors, without any external library.

There are two ways of printing colored stuff in Windows:
1. Is using simple way https://github.com/gabime/spdlog/blob/master/include/spdlog/sinks/wincolor_sink.h#L36
2. Using my code and also https://blogs.msdn.microsoft.com/commandline/2017/08/11/introducing-the-windows-console-colortool/ and https://blogs.msdn.microsoft.com/commandline/2017/08/02/updating-the-windows-console-colors/

There has been a quite development of windows console colors recently, which doesn't need an external library such as "ANSICON" or "rang".

**Comment by gabime** [comment]
@H1X4Dev Do you know what are the advantages of using the new 8.1 way instead of spdlogs simple way?

**Comment by agauniyal** [comment]
You need "rang" if you want to support earlier windows versions than Windows 10 anniversary update(yes even windows 10 before anniversary update will show garbage if you directly output escape codes). It definitely doesn't depend upon compiler version(vc140 or anything) and will fail again if you try to mix things like mingw/msys2/cywgwin :)

**Comment by H1X4Dev** [comment]
Well, this works across all compilers that have <Windows.h> header (I don't have experience in other than msvc and gcc so I might be wrong). Also, we can check based on the Windows version and only for MSVC compiler.

The following processor code is to define if, and only if the platform contains Windows 8 SDK where this feature has been added.
```
#if defined(_WIN32) && defined(_MSC_VER) && WINVER > 0x0602
.. stuff ..
#endif
```
The feature is mostly useful for highlighting specific areas of the text in the console, rather than full lines, but also vice-versa. It would also be useful for users that are swapping their code between GCC and MSVC based on activity and would not require too much front-end configuration to do so.

Since the feature doesn't exist in spdlog, there is a simple workaround:
`spdlog::set_pattern("\x1b[0m^ %Y-%m-%d %T.%e [%z] %v");`
Or you could set them by color for different warning versions and also, when logging text out, we would be able to include our ANSI colors:
`logger->info("\x1b[0;91mHello \x1b[0;92mWorld\x1b"); // Hello World`

**Comment by agauniyal** [comment]
I think one of us is misunderstanding the problem. Let me share what I've learnt while writing my library - Linux has 2 different ways of outputting colors to terminals 1. terminfo(the right way) and 2. ansi escape codes(slightly less right way). I say it _slightly less right way_ because it works for majority of popular terminals but still produces garbage on several old terminals(very few in numbers), but you can still get away with it. My library will soon have a release that'll move it to terminfo based output to support virtually every existing terminal.

On windows there are again 2 ways to print colors - 1. The old but works everywhere Get/SetConsoleMode and 2. ansi escape codes(similar to linux). The _old but works everywhere_ works in all versions of windows and will be supported indefinitely. The 2nd method is built upon first method iirc and is only available from anniversary update of windows 10.

Now the problem with your approach is you check compiler/windows version at compile time which is another way of saying I want to run the binaries only on the system I compiled them. If that's your use-case, it's fine to do checks at compile time. If you want to run your binaries on other systems where your compiler might not be available, you need 1. to do these checks at runtime 2. Fallback to old but works everywhere methods 3. Provide linux compatibility, which in nutshell is what 'rang' does.

**Comment by H1X4Dev** [comment]
There are some users that target their software to be Windows 8.1 and above, where ANSI colors are supported. The whole point of this, would be to reduce the library size and not to depend on other external library to create this functionality as it is handled natively. We are able to perform runtime checks for this as well (https://msdn.microsoft.com/en-us/library/windows/desktop/ms724429(v=vs.85).aspx) although, this would be replaced by the consumer within CMake or other build tool using defines and if wished, run-time checks.

Although, I do see your point regarding the compatibility, but we are more biased around Windows 8.1+ users regarding this support. I'm pretty sure, that Linux supports `\x1b` escape character for ANSI, so theory-wise it would be compatible wise-versa.

For now, I guess, it would be up to the consumer to decide how are they going to use the library as it's not that difficult to extend it to add this functionality with existing functions.
