### ISSUE TITLE
Add support for "Time since program launch" delta time custom formatter

### ISSUE THREAD

**Issue by jroweboy** [gabime/spdlog#434]
I'm currently migrating the logging for an application, and the time format for the logs is <Seconds/NanoSeconds> since the start of the program. This is probably very different from the average user of this library, but for our application it just makes sense; its not a program that will run for weeks on a server, but rather a program thats made to run on users machines. As the software is fairly complicated and still rather early in development, we often use logs to diagnose users problems, and knowing the HH:MM:SS that an event occurred isn't important. All that really matters in debugging these issues is the relative time since program launch.

This is something I'm very interested in, and I don't see anywhere in the current feature set. Before I opened a pull request, I wanted to gauge your impressions and see if it would be something you would want a pull request for.

**Comment by jroweboy** [comment]
Just as I clicked submit I reread the docs on custom formatter and noticed this https://github.com/gabime/spdlog/blob/master/include/spdlog/formatter.h I suppose this will suffice :)

**Comment by YukinoHayakawa** [comment]
I also want to see time since program start (or since logger creation since when exactly the program starts is not always easy to determine) for diagnosing our interactive applications where the real world time isn't very useful. Of course we can implement the formatter interface, principally. But time flies by and now we even have flags for elapsed time since previous message. I think we can just add another flags for elapsed time since program start to make the thing more convenient. So I suggest to reopen this issue and tag it as an enhancement.

**Comment by sylveon** [comment]
FYI, Windows can get time since process creation using `GetProcessTimes`. Then you can substract that from the result of `GetSystemTime` & `SystemTimeToFileTime` to get the number of 100s of nanoseconds since the program launched.

**Comment by berge2007** [comment]
Or you can use std::chrono::steady_clock to avoid dependency to any OS

**Comment by gabime** [comment]
@berge2007 How is  that can achieved? steady clock doesn't measure from start of the process.

**Comment by sylveon** [comment]
I believe they imply that you store a static variable from `std::chrono::steady_clock::now()`, since static variables are populated at process creation you would get a pretty good estimate of when the process was created. This wouldn't really work if spdlog is located in a module that is dynamically loaded, because then you'd get time since module load, and unloading/reloading the module would reset that stat to 0.

**Comment by gabime** [comment]
Closing. I can't find any reliable cross platform way to achieve this..
