### ISSUE TITLE
vs  build error

### ISSUE THREAD

**Issue by stonedreamforest** [gabime/spdlog#449]
fatal error C1083: Cannot open include file: “spdlog/tweakme.h”: No such file or directory

**Comment by stonedreamforest** [comment]
For #include "filename" the preprocessor searches in the same directory as the file containing the directive, and then like for #include <filename>. This method is normally used to include programmer-defined header files.

For #include <filename> the preprocessor searches in an implementation dependent manner, normally in search directories pre-designated by the compiler/IDE. This method is normally used to include standard library header files.

**Comment by gabime** [comment]
In which vs version it doent compile?  Please post the full error message

**Comment by stonedreamforest** [comment]
@gabime 
 vs2015 ：
1>------ Build started: Project: logtest, Configuration: Debug Win32 ------
1>  1.cpp
1>c:\users\administrator\documents\visual studio 2015\projects\test_vs2015\logtest\spdlog\spdlog.h(12): fatal error C1083: Cannot open include file: 'spdlog/tweakme.h': No such file or directory
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Projects build report:
  Status    | Project [Config|platform]
 -----------|---------------------------------------------------------------------------------------------------
  Failed    | logtest\logtest.vcxproj [Debug|Win32]

**Comment by stonedreamforest** [comment]
![newlogtest](https://cloud.githubusercontent.com/assets/16742566/26282513/680ed9c0-3e45-11e7-8b91-491866856968.jpg)

jpg->rar

**Comment by gabime** [comment]
See pull #182. No one complained since then about include files. What is your suggestion ?

**Comment by stonedreamforest** [comment]
Why do I compile errors? What changes do I need to make?
I think the best way:
`#include "spdlog/blah.h" ` instead of  `#include <spdlog/blah.h>`

**Comment by gabime** [comment]
Yes I agree, please issue a pr to change all of the spdlog includes

**Comment by gabime** [comment]
Fixes inpr #450

**Comment by daylanKifky** [comment]
I'm having the same problem using gcc.
The problem with #450 is that even if the `#include <>` where changed for `#include ""`, the paths on these are still pointing to the root of the library.
For example, inside `/include/spdlog/details/file_helper.h`

```
#include "spdlog/details/os.h"
```
This will look for `os.h` in `/include/spdlog/details/spdlog/details/` which doesn't exists.

should be:

```
#include "../details/os.h"
```

and so on..

I made a PR (#551) which works for me..

**Comment by arthur-tacca** [comment]
I wonder if @daylanKifky and @stonedreamforest have added to the wrong path to their compiler's list of include paths. 

Let's imagine you have put spdlog in `/some/path`, so that `/some/path/spdlog/spdlog.h` and `/some/path/spdlog/tweakme.h` are files that exist. Then:

* The correct setup is to add `/some/path` to your include paths, then use `#include <spdlog/spdlog.h>`
* My suspicion is that they have added `/some/path/spdlog` to the include path, then used `#include <spdlog.h>`

The reason I suspect this is because, if the setup is correct and the compiler can find `spdlog/spdlog.h`, then it surely can find `spdlog/tweakme.h` in the same list of paths.

As @daylanKifky says, changing angle brackets to quotation marks doesn't help because it just makes the compiler look for `/some/path/spdlog/spdlog/tweakme.h` (followed by the usual paths). But I disagree that the correct solution is to change to `#include "../details/os.h"` as that only masks the mistake in the user's configuration and user's `#include` statements. Instead the solution is for the user to fix their code and config. Using angle brackets in spdlog's `#include` statements was correct IMO.

**Comment by gabime** [comment]
@arthur-tacca I agreee, There are no relative includes in spdlog headers.
