### ISSUE TITLE
Are spdlog support in IOS?

### ISSUE THREAD

**Issue by tommyZZM** [gabime/spdlog#491]

**Comment by gabime** [comment]
Not officially. But you could try and tell us if it works.

**Comment by headupinclouds** [comment]
I've been using `spdlog` in iOS for a while now.  It works fine.

**Comment by gabime** [comment]
@headupinclouds That is good to know. Thanks for updating

**Comment by aisnote** [comment]
> I've been using `spdlog` in iOS for a while now. It works fine.

can you share something in detail for iOS? thanks.

**Comment by shidephen** [comment]
> @headupinclouds That is good to know. Thanks for updating

But which sink should I use in iOS? 
Do stdout_color_mt works?
3q

**Comment by NSShentu** [comment]
Anyone can give more details?

**Comment by bialasjaroslaw** [comment]
I tried to compile it for IOS, but Clang13 is crashing when compiling `file_sink` or `color_sink`. I tried to link with `spdlog_header_only` instead, but unfortunately I was unable to compile a single file with `spdlog` header or anything even remotely related through includes. I am assuming that this is caused by lot of templated code that clang is not able to handle correctly (I have to use machine with only 8gigs of ram, so that might be a problem as well), although I don't know what is causing so much problems. 
I moved `spdlog` calls into cpp file as I am already using `fmt` and I am able to pass `std::string` instead of forwarding arguments and that seems to work quite good. 

For logging I am using stdout sink, however I am not able to collect/see any logs outside of QtCreator. I have tried some build in tools as well as idevicesyslog (even when I have used syslog sink instead of stdout), but nothing is shown, even though I am setting log level to debug. Maybe some error/warnings will be displayed, but right now it is not enough and I will probably implement my own sink with use of some objective c calls as for now nothing else seems to work.
