### ISSUE TITLE
conditional log error

### ISSUE THREAD

**Issue by minhmoc** [gabime/spdlog#526]
The following code throw out-of-range exception:

`shared_ptr<spdlog::logger> console = spdlog::stdout_color_mt("console");
std::vector<int> list;
console->info_if(list.size() > 0, "List at 0 is: {}", list.at(0));`

Obviously, it should not. 
Any idea?

**Comment by godbyk** [comment]
Because arguments to a C++ function may be evaluated in any order and all arguments will be evaluated before the function is called. So `list.at(0)` will be evaluated before you get to the `if` statement inside the `info_if` function.

So the behavior you describe is expected as per the rules of C++.

If you need to only evaluate the arguments when the condition is true, then you'd have to use a macro. Something similar to this (untested):

```c++
#define SPDLOG_INFO_IF(logger, flag, ...) if (flag) { logger->info(__VA_ARGS__); }
```

**Comment by minhmoc** [comment]
Thank @godbyk. Dont know why it took me so much time with this bug. 
close issue now.
