### ISSUE TITLE
SPDLOG_TRACE and _DEBUG evaluate their arguments even when logging is off

### ISSUE THREAD

**Issue by sherm1** [gabime/spdlog#638]
When these macros are expanded (because NDEBUG is _not_ defined), they evaluate their arguments unconditionally, _before_ checking the logging level. When arguments are expensive to evaluate (common in code intended for debugging output), that can be very costly.

Please consider having these macros perform a runtime check of the level prior to invoking logger->trace() or logger->debug(). That is a very small extra cost that avoids evaluating the arguments. For example:
```c++
#ifdef SPDLOG_DEBUG_ON
  #define SPDLOG_DEBUG(logger, ...) \
  do {                                             \
    if (logger->level() <= spdlog::level::debug) { \
      SPDLOG_DEBUG(logger, __VA_ARGS__);           \
    }                                              \
  } while (0)
#else
  #define SPDLOG_DEBUG(logger, ...)
#endif
```

**Comment by gabime** [comment]
> because NDEBUG is not defined

NDEBUG is not used. Spdlog expands the macros only if SPDLOG_DEBUG_ON is defined..

**Comment by sherm1** [comment]
Thanks for that clarification! Would be great not to evaluate the arguments when SPDLOG_DEBUG_ON is defined but logging is off.

**Comment by gabime** [comment]
I agree. It might be worth the extra cost.
There is a handy ```logger->should_log(level)``` that can be used for this.

**Comment by chrahunt** [comment]
When/if this is implemented, heed the lessons learned [here](https://github.com/wxWidgets/wxWidgets/blob/20a98406f06f0392f0b303c0deb6c630e17704fd/include/wx/log.h#L1271).

**Comment by arthur-tacca** [comment]
Just a note that spdlog only formats a log message if it is going to be logged by the current logger. This means that a workaround (or arguably even correct solution) is to use a struct or class with an `operator<<()`:

    // bad: getDescriptionString() is called even if not logged, even if we use SPDLOG_DEBUG instead
    mylogger->debug("Starting {}", getDescriptionString(foo));
    // good: Foo::operator<< only called if it will be logged
    mylogger->debug("Starting {}", foo);

If you don't want to add an `operator<<` to the thing you want to log, or you want to log the result of an expensive function rather than an object, you can always create a little wrapper struct for the sole purpose of having an insertion operator:

    struct FooPrinter {
        explicit FooPrinter(const Foo& foo): foo(foo) {}
        const Foo& foo;
        std::ostream& operator<<(std::ostream& os, foo) {
            os << getDescriptionString(foo);
            return os;
        }
    };
    mylogger->debug("Starting {}", FooPrinter(foo));
    
    struct FuncPrinter {
        std::ostream& operator<<(std::ostream& os, foo) {
            os << someExpensiveFunction();
            return os;
        }
    };
    mylogger->debug("Starting {}", FuncPrinter());

When spdlog moves to fmt 5.0 you could [specialise `formatter<T>`](http://fmtlib.net/5.0.0/api.html#formatting-user-defined-types) for better performance.

Admittedly this quite a lot of code compared to just calling a function inside a macro argument (and overriding a fmt 5.0 formatter is even more verbose) so this enhancement still has some value.

**Comment by sherm1** [comment]
(Edited the code in the issue description per @chrahunt's comment.)

**Comment by NickeZ** [comment]
@chrahunt I'm pretty sure the de-facto standard hack for that is `do {} while(0);` but maybe this for-loop is like a merge of `do { if(condition){} } while(0);`. I still think I would write out the do-while since that is easier to read IMHO.

https://www.quora.com/What-is-the-purpose-of-using-do-while-0-in-macros

**Comment by chrahunt** [comment]
@NickeZ they are a little different. `do {} while(0);` is sufficient for standalone statements where the macro receives all necessary information. The for loop construction also allows for the macro to be used as part of an expression, like

```
LOG_DEBUG << some_expensive_function();
```

I only knew about one and not the other at the time. For this issue the do-while is more clear.

**Comment by gabime** [comment]
Implemented in trunk.

**Comment by sherm1** [comment]
Thanks, @gabime!
