### ISSUE TITLE
Upgrade to fmt 5.0

### ISSUE THREAD

**Issue by rivertam** [gabime/spdlog#708]
The glorious fmt library just [released 5.0.0](https://github.com/fmtlib/fmt/releases/tag/5.0.0).

I'd love to see a version of spdlog that utilizes the awesome new features. I'd make a PR but I don't exactly know how to manage the update.

**Comment by rivertam** [comment]
Additionally/alternatively, is there a way to provide your own version of fmt to spdlog?

**Comment by gabime** [comment]
You can define SPDLOG_FMT_EXTERNAL before including spdlog.h (not sure if spdlog will compile with fmt 5.0 though).

**Comment by stkw0** [comment]
I used SPDLOG_FMT_EXTERNAL, but seems that fmtlib removed fmt::MemoryWriter so spdlog will need to update their code before updating to fmt 5.0

**Comment by aldanor** [comment]
@gabime Is it anywhere in the plans to upgrade to fmt 5.0? (e.g. if you have a project that needs to make use of *both* fmt and spdlog)

The main thing is that `fmt::MemoryWriter` no longer exists (it's `memory_buffer` or something), so obviously it fails to compile.

**Comment by arthur-tacca** [comment]
The `MemoryWriter` class was removed because it is "superceded by the compile-time format API" (as stated [the message for this commit](https://github.com/fmtlib/fmt/commit/bb738c4c264cb4e860e09160b00e5536a310c854)). It's true that there is a `memory_buffer` class that seems to mostly serve the job that the `MemoryWriter` used to, but it looks like it is intended as more of an implementation detail than a user-facing API. Assuming your format string is not known at compile time, it seems like the intended API now is just `fmt::format()`.

**Comment by gabime** [comment]
@aldanor The plan is to upgrade spdlog v1.x to fmt 5.0. Release date- not sure but hopfully soon.

**Comment by arthur-tacca** [comment]
Just to add to my previous comment: I was pretty much saying spdlog will have to switch from MemoryWriter to format() because you might not know the format string at compile time. But actually requiring a pattern format string to be a compile time constant is probably a sensible idea. Note that even if you choose a format string at runtime from a small list of strings known at compile time, you can still use the fmtlib compile time format routines. This is likely to be fine for the vast majority of users, and those that don't can create their own spdlog::pattern_formatter child class as a last resort.

The main disadvantage of course is that this would be a breaking change in spdlog, not least because formats would go from the current %x notation to the fmt {x} notation. Furthermore it is not obvious what the performance cost would be of going from a vector of flag_formatter objects to named fmt::arg objects.

**Comment by gabime** [comment]
spdlog will likly use fmt::format_to(memory_buffer, fmt_string, args)..Should straight forward.

**Comment by VikingExplorer** [comment]
This really broke me.  I'd like to go back to using the bundled version temporarily, but it's not building either.

I commented out:  //#define SPDLOG_FMT_EXTERNAL
Renamed folder:  3pLibs\vcpkg\installed\x64\include\fmtX

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'bundled/format.h': No such file or directory c:\dev\abc\3plibs\vcpkg\installed\x64\include\spdlog\fmt\fmt.h	21

**Comment by VikingExplorer** [comment]
Updated to latest in vcpkg & again changed:

FROM:     static ObjectType Get(ValueType& v) { return v.GetObject(); }
TO:          static ObjectType Get(ValueType& v) { return v.get_object(); }

Because life is too short to be stubborn about using a name that causes other people lots and lots of problems.

I'm a rude person, but I don't go out of my way to cause complete strangers pain.

**Comment by Praying** [comment]
waiting upgrade to fmt 5.0, and then I can use in the vcpkg. If possible, I want know the how long will release.....

**Comment by gabime** [comment]
Already in the v1.x branch. You can try it out.

**Comment by ras0219-msft** [comment]
I've pushed a branch[1] to vcpkg that uses v1.x. @Praying let me know if this works for you and I'll merge it to master!

[1] https://github.com/Microsoft/vcpkg/tree/dev/roschuma/update-spdlog

**Comment by gabime** [comment]
@Praying The API has chabged. Please take a looke at the example.cpp on how to use.

**Comment by Praying** [comment]
Yeah! It works, Thanks so much. @gabime

**Comment by ras0219-msft** [comment]
Great! @gabime, do you have any plans at this point for when you will publish 1.x?

**Comment by gabime** [comment]
@ras0219-msft I am adding some finishing touches. I hope within the next couple of weeks.
I might as well wait for fmt 5.1 version that will be released soon by @vitaut .

**Comment by ras0219-msft** [comment]
Ok, sounds great. I'll go ahead and publish this one to vcpkg (since the current one is still broken due to fmt 5.0) and we'll make sure not to regress around the 5.1 release :)

**Comment by Milerius** [comment]
@ras0219-msft @gabime It's seems that a push of upgrade into 5.1 just happened, can we expect a tag in few days ?

**Comment by gabime** [comment]
Yes. It is already in the branch. You can try it now.

**Comment by Milerius** [comment]
@gabime I Will for sure, but since i use VCPKG as package manager, and vcpkg need a tag to update, i think i will wait for youre next tag ! as @ras0219-msft say he will update your port since it's a very important port used by many users in vcpkg

**Comment by franklinwesley** [comment]
Hello, the problem in the installation by vcpkg has already been solved?

**Comment by JoelTroch** [comment]
Just as FYI, version 5.1.0 has been released around 20 days ago.

**Comment by gocarlos** [comment]
Seems to be fixed by now...

**Comment by ras0219-msft** [comment]
@franklinwesley 1.0.0 is now in vcpkg :)
