### ISSUE TITLE
Request: extern C API 

### ISSUE THREAD

**Issue by MarkSwanson** [gabime/spdlog#71]
It would be nice to use spdlog from Rust (and perhaps other languages with a C FFI).

:-)

**Comment by gabime** [comment]
Any volunteers?

**Comment by JodiTheTigger** [comment]
#136 would probably be a precursor for a c-api.

**Comment by vitaut** [comment]
#136 has nothing to do with the C API because in the latter you translate exceptions to error codes or similar, not ignore them completely.

**Comment by SpriteOvO** [comment]
> It would be nice to use spdlog from Rust (and perhaps other languages with a C FFI).
> 
> :-)

@MarkSwanson I recently rewrote `spdlog` in Rust instead of based on FFI in order to use `spdlog` in Rust with similar API and performance.

[spdlog-rs] has been published on crates.io. It is still very new, any contributors and feedback are welcome!

And thanks a lot to @gabime for developing C++ `spdlog` and thus inspiring [spdlog-rs].

[spdlog-rs]: https://crates.io/crates/spdlog-rs
