### ISSUE TITLE
syslog formatting (request)

### ISSUE THREAD

**Issue by hramoser** [gabime/spdlog#729]
spdlog does not write formatted messages to syslog. In syslog_sink.h:
`::syslog(syslog_prio_from_level(msg), "%s", msg.raw.str().c_str());`

Is this behavior by design? 
I would prefer to get a formatted message also for syslog:
`::syslog(syslog_prio_from_level(msg), "%s", msg.formatted.str().c_str());`

**Comment by gabime** [comment]
Yes, it is by design, since syslog already formats the messages.

**Comment by singlaive** [comment]
@gabime , I understand why you design like this, but will you consider providing the option to format syslog as well?
In my case I would like the log formating done by spdlog and leave syslog only show the raw message. Because I need logs rendered both to console and syslog, and I need them in exactly the same format. 
Can I do the same formatting in syslog? Maybe, but first it is duplicated effort; secondly, I would like the log line display the current version of the software (form text file), to do that I might need to write a string generator for syslog. That's double waste of effort.
Does this make sense?

**Comment by gabime** [comment]
A possible approach would be to inherit syslog sink (override the sink_it_ method) to do what you need (for this the private section of the syslog sink should be comverted to protected though).

**Comment by singlaive** [comment]
Thanks for advice. Indeed that is the approach I had chosen. But to be honest, unless a user only uses a single syslog sink, he may face the awkward situation about replicating the formatting for syslog.

**Comment by gabime** [comment]
That happens anyway in spdlog. Each sink has it's own private formatter copy, and use it to format the message, so that's fine. Most of the time the formatting is so fast that this it doens't matter.

**Comment by gabime** [comment]
Implemented with additional boolean to ctor (true to format).
