### ISSUE TITLE
need journald sink

### ISSUE THREAD

**Issue by microcai** [gabime/spdlog#873]
does this logger support systemd-journald ?

**Comment by gabime** [comment]
Not directly, but it supports syslog.

**Comment by phinzphinz** [comment]
I think it should be possible to set the format such that systemd can understand the log level. From [here](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#SyslogLevel=):
`Note that individual lines output by executed processes may be prefixed with a different log level which can be used to override the default log level specified here.`
More precisely, it should be possible to prefix log messages with something from `<1>` to `<6>` in order to map the log levels from spdlog to their counterparts [as described here](https://www.loggly.com/blog/logging-in-new-style-daemons-with-systemd/):

```
<7>This is a DEBUG level message
<6>This is an INFO level message
<5>This is a NOTICE level message
<4>This is a WARNING level message
<3>This is an ERR level message
<2>This is a CRIT level message
<1>This is an ALERT level message
<0>This is an EMERG level message
```
I would love to have a pattern flag, call it `%G`, that gives

%L
%L
