### ISSUE TITLE
Multiple process logging to same file?

### ISSUE THREAD

**Issue by SharpSnake** [gabime/spdlog#937]
Does daily_file_sink support multiple process write to the same file at the same time?
I got a exception if multiple process use the same log filename.( Failed opening file xxxxx for writing ).
Thank you.

**Comment by SharpSnake** [comment]
To avoid this problem, I have to rewrite my custom FileNameCalc,  and make filename with hour + minute + second.
Like this : xxxx_2018-12-6_10-40-54.txt

**Comment by gabime** [comment]
There is no support for multiprocess. 
For example, not sure what will happen if 2 processes will try to rotate at same second.

**Comment by SharpSnake** [comment]
I did this already as you suggested, but this made so much log files in the log folder.
I wonder can this requirement be implemented? Just in in theory. 
I'm not very good at it.

**Comment by gabime** [comment]
Sure It can, using cross process locks or even better,  with a dedicated process that receives the log messages thru pipe or socket and does the actual logging.

**Comment by SharpSnake** [comment]
AH! Sounds like a database system.
Thanks, and best wishes.

**Comment by damageboy** [comment]
@gabime I just saw this issue, and I personally "vested" in getting this to work.

I'd like to discuss here if you feel that this can be perhaps added to spdlog in a more light-weight, staggred mannger:

* On linux/mac we do have `O_APPEND`:
  Key point: **The modification of the file offset and the write operation are performed as a single atomic step**
  ```
  O_APPEND
    The file is opened in append mode.  Before each write(2), the file offset is positioned at the end of the file, as if  with
    lseek(2).  The modification of the file offset and the write operation are performed as a single atomic step.

    O_APPEND  may  lead to corrupted files on NFS filesystems if more than one process appends data to a file at once.  This is
    because NFS does not support appending to a file, so the client kernel has to simulate it, which can't be  done  without  a
    race condition.
  ```

  * On NFS, this will of course not work, but I think that this is an acceptable outcome

* On Windows, it seems this can be "emulated" with use of oplocks and createfile2,
  following writes would need to request a lock with `DeviceIOControl` function and then pass in `FSCTL_REQUEST_OPLOCK` to obtain a lock before each seek + write.

This would *not* represent complete support for multi-process write, but could be exposed as some sort of a "concurrent_write" with the limitations:

* Works on windows+Posix only
* Supports append-only write, without rolling (which would require additional synchronization)

Thoughts?

**Comment by gabime** [comment]
I dont mind to give it a try, although it seems suitable only for basic file sink like you mentioned.
I suggest creating a new “multi_process_file_sink” and avoid modifying existing sinks.

**Comment by damageboy** [comment]
I'll give it a go. Is this supposed to happen on the 1.x / 2.x / dev branch?
Seems like the 1.x is the active one...?

**Comment by gabime** [comment]
1.x is the active branch.

**Comment by damageboy** [comment]
Thanks. Just did a basic check, and I see now that the basic file logger does call `fopen(..., "ab")` when the truncate flag is passed then spdlog does pass a less optimal flag to `fopen`: `fopen(..., "wb")` in order to force the truncation, but unfortunately `fopen` is limited in that way, in the sense that it is impossible to pass `O_TRUNC | O_APPEND` through the limited functionality surfaced by `fopen`.

So in some way, if all you are into is multi-process basic file logging on linux with no truncation... it is kind of there...? already? which I admit is surprising me a bit given this issue was opened.

Anyway, rethinking this, it NOW mostly sounds to me like `multi_process_file_sink` could basically do:
* the lower level tinkering required for append-only writing on Windows
* massaging the `fopen()` into `fdopen()` so that the `open()/openat()` syscall could be used to force the passing of `O_TRUNC | O_APPEND` both for truncation and non-truncation scenarios..

I'll implement this as `multi_process_file_sink` as requested by @gabime, but the more I look at this the more it looks to me as a tweak for the existing basic logger rather than a whole new logger.

But we can pick this up after I have something working.
Just sharing my findings for now...

**Comment by gabime** [comment]
> O_TRUNC | O_APPEND through the limited functionality

Why this combination needed? Is this the way to support mp?

**Comment by damageboy** [comment]
I'm perhaps slightly too focused on my own use-case where there is a tree of processes, all stemming from a root process, where the first process does wish to truncate the files before launching sub-processes which do not truncate the files. In this case, what *I* would do, is rely on the fact that *I* know who is the master process, and open the file with `O_TRUNC | O_APPEND`, and have the sub-processes never specify `O_TRUNC`, but rather just `O_APPNED`. This makes some sense for a this rather extreme/specific use-case.

So to answer you question, the `O_TRUNC | O_APPEND` is useful for cases where the order of process creation, between the processes sharing the log file in append mode is pre-determined.

In cases where the process launch is *not* predetermined this would make very little sense...

**Comment by gabime** [comment]
Sounds a common usecase. Master process creating log file and forking workers.. 
If you come up with such sink and document this intended usage, would be very useful.

**Comment by damageboy** [comment]
Sure. The technical implementation does not strike me very hard (although I've admittedly never used oplocks in Windows and I might regret this hibris very shortly).

I'll try and figure how to present an API like this, during the setup of the sinks to make it relatively easy to grok before resorting to prose on the wiki page :)

**Comment by gabime** [comment]
I am not even sure how much demand for this will be for windows as this is a typical unix use case. I am ok with supporting unix only in first stage.

**Comment by damageboy** [comment]
Well, for Windows, it's a slightly more useful code in general, since `O_APPEND` option is meaningless given that the windows kernel simply does not provide the atomicity of seek+write that would allow two processes to write to the same log-file in the first place.
So if we would even want to consider a cross-process sharing scenario on Windows we would have to do some heavier lifting by using oplocks to achieve an `O_APPEND`-like visage of competence :)

I'll give it a shot and we'll see where this goes.

**Comment by ysinsane** [comment]
Hi guys, may I ask anything new about this topic? I saw @damageboy  said he will give it a shot...

**Comment by damageboy** [comment]
@ysinsane Yeah, I kind of dropped to ball on this, let me try to restart my branch this weekend.

**Comment by iradization** [comment]
Hi @damageboy , I'm also interested in multiprocess logger, Perhaps you can share your branch name so I can take a look ? 

In fact, i'm working on solution of my own by extending the rotating file sink so that upon sink_it_, all actions will be made (open + write + flush + close)... I know it's much less efficient but unless serializing the logs using a manager process i couldn't see any other way. 

Also, I had to create a different open function that uses the os specific `flock` system call in order to lock the file and address to the cases where it didn't succeed. One special edge case I observed is when the file is successfully locked but renamed by another process (this operation doesn't require lock) - so it's taken care by opening the filename to another handler and compare their inodes.

Comments are mostly welcomes. 

Here's the code that I've added : 

in rotating_file_sink-inl.h 

```
template<typename Mutex>
SPDLOG_INLINE void rotating_file_sink<Mutex>::sink_it_(const details::log_msg &msg)
{
    memory_buf_t formatted;
    base_sink<Mutex>::formatter_->format(msg, formatted);
    file_helper_.exclusive_reopen(false);

    current_size_ += formatted.size();
    if (current_size_ > max_size_)
    {
        rotate_();
        current_size_ = formatted.size();
    }
    file_helper_.write(formatted);
    file_helper_.flush();
    file_helper_.close();
}

in file_helper-inl.h:

```
SPDLOG_INLINE void file_helper::exclusive_reopen(bool truncate)
{
    if (filename_.empty())
    {
        throw_spdlog_ex("Failed re opening file - was not opened before");
    }
    this->exclusive_open(filename_, truncate);
}

SPDLOG_INLINE void file_helper::exclusive_open(const filename_t &fname, bool truncate) {
    unsigned retryCount = 0;
    std::FILE *tmp;
    struct stat fd_stat, tmp_stat;

    while (!fd_ && retryCount < open_tries_) {
        retryCount++;
        os::fopen_s(&fd_, fname, "a+");
        
        if (fd_ == NULL) {
            return NULL;
        }
        
        fchmod( fileno( fd_ ), S_IRWXU | S_IRWXG | S_IRWXO );
        
        int rc = flock(fileno(fd_), LOCK_EX);
        
        if (rc == -1) {
            fclose(fd_);
            fclose(tmp);
            fd_ = tmp = NULL;
            continue;
        }
        
        // The following block check if file was renamed by another process while being locked by current process.
        os::fopen_s(&tmp, fname, "a+");
        
        if (tmp == NULL) {
            return NULL;
        }

        int ret = fstat (fileno(fd_), &fd_stat);
        int ret2 = fstat (fileno(tmp), &tmp_stat);
        
        if (ret < 0 || ret2 < 0)
        {
            fclose(fd_);
            fclose(tmp);
            fd_ = tmp = NULL;
            return NULL;
        }
        
        if (fd_stat.st_ino != tmp_stat.st_ino)
        {
            fclose(fd_);
            fclose(tmp);
            fd_ = tmp = NULL;
            continue;
        }
        
        fclose(tmp);
        details::os::sleep_for_millis(open_interval_);

    }
}

```

**Comment by zethon** [comment]
+1 for this feature!

**Comment by jiudianren** [comment]
> 

if no rotate or filename change  ,will that ok ?

**Comment by tt4g** [comment]
> if no rotate or filename change ,will that ok ?

@jiudianren No. If logs are written to the same position at the same time, the contents of the file will be corrupted.
